### ISSUE TITLE
TOC support broken after upgrade to latest QT

### ISSUE THREAD

**Issue by Jimbobnz** [wkhtmltopdf/wkhtmltopdf#1509]
Version: wkhtmltopdf 0.12.0
OS: Centos 6.4
No TOC is being created and no error generated. 

bin/wkhtmltopdf toc http://www.w3schools.com/html/html_headings.asp w3schools.com.pdf

Even when specifying to use xsl file, it has the same results. 

bin/wkhtmltopdf toc --xsl-style-sheet toc.xsl http://www.w3schools.com/html/html_headings.asp w3schools.com.pdf

**Comment by marmie1** [comment]
Just to make sure: I tried to use "toc --xsl-style-sheet C:\url" and this didn't work. How can I pass xsl url to wkhtmltopdf in version 0.12.2? Seems like the earlier doesn't work anymore, am I right? Works fine with "toc ", but then there is a problem if user want's to use customized xsl which is given as a parameter. So what is the command line args for giving xsl url to toc? Thank you and sorry for a bit noobish question since I just started working with xsl and wkhtmltopdf.

**Comment by jomarie** [comment]
Hi there. We recently had to upgrade our wkhtmltopdf version in changing servers - we are now running 0.12.2.1 with the latest QT patch, and I am experiencing the missing TOC issue. I understand from the last posts that this should be fixed - is it possible that something in the most recent wkhtml / QT build is causing problems again? There is just a blank page where the TOC is supposed to be. 

Thanks in advance!

**Comment by jomarie** [comment]
An update on this issue, for anyone else who might be experiencing it:
We use the following:
```toc --exclude-from-outline --toc-header-text \"\"```
which correctly sets the document to use a TOC, but takes out the "Table of Contents" heading. If I take this out, or put any other text for the TOC header, the TOC displays again, otherwise it just loads a blank page.

For interest, is there any other way to have the TOC without a specific header? I checked the latest documentation at http://wkhtmltopdf.org/usage/wkhtmltopdf.txt but couldn't see any such option.

**Comment by ashkulz** [comment]
What was the version you were using previously?

**Comment by jomarie** [comment]
Previous version was wkhtmltopdf 0.10.0 rc2. A previous developer implemented it and everything was working until our server change, so had no need to change before now

**Comment by ashkulz** [comment]
If you can produce a small, reproducible test case with the latest version -- please report as separate issue. If you want, you can still download the previous version from the downloads page (see archive).
