### ISSUE TITLE
rendering noticeably slower in the "Printing pages" phase

### ISSUE THREAD

**Issue by sanfords** [wkhtmltopdf/wkhtmltopdf#1510]
wkhtmltopdf is doing a much much better job at handling page breaks than PhantomJS (Qt4.8.4)...  There's no doubt about that.  What I've found though is that wkhtmltopdf is running much more slowly than PhantomJS.

On a single test here PhantomJS is rendering a 2 ½ page PDF in less than 4 seconds, while wkhtmltopdf is up at almost 14 seconds.

I'm wondering if there's some sort of debug flag or something that may be slowing things down.  Or maybe the page-break algorithm just more computationally expensive?

**Comment by Jesus1302** [comment]
There is not only a problem with border-radius. I have also a slowdown with gradients.
If I set the following line instead of the radius, it takes about 10 seconds :
background: -webkit-linear-gradient(top, #C2C2C2 0, #D1D1D1 20%, #C2C2C2 50%, #B8B8B8 80%, #C2C2C2 100%) no-repeat;

And only one second with this 2 lines (and the pdf file generated is smaller and faster to load with acrobat):
background-repeat: no-repeat;
background: -webkit-linear-gradient(top, #C2C2C2 0, #D1D1D1 20%, #C2C2C2 50%, #B8B8B8 80%, #C2C2C2 100%);

The following lines are slow again :
-webkit-background-origin: border !important;
background-repeat: no-repeat;
background: -webkit-linear-gradient(top, #C2C2C2 0, #D1D1D1 20%, #C2C2C2 50%, #B8B8B8 80%, #C2C2C2 100%);

It is quite hard to understand why it is slow or not.
Unfortunately, I need rounded corners and gradients in my pdf, seems I'm not lucky.

**Comment by ashkulz** [comment]
There was a link to a blog post regarding this in the [mailing list](https://groups.google.com/forum/#!topic/wkhtmltopdf-general/IZCgzfT7FBI) -- it is an issue in the [browser engine itself](http://perfectionkills.com/profiling-css-for-fun-and-profit-optimization-notes/). You may want to try and see if it is better with `0.13 alpha`.

**Comment by Jesus1302** [comment]
Thanks, the version 0.13 alpha is really faster. But unfortunalely there is some problems with colors  (color inversion) and the --zoom option doesn't work :
wkhtmltopdf.exe www.google.com --zoom 5 test.pdf

**Comment by navbhu** [comment]
I faced the same problem, but the performance increased not only when removing the border-radius but also by removing the background-color or border-style while keeping the border-radius.

The size of the PDF with all the style is very much higher (almost 10 times) when compared to the PDF generated after removing any one of the above styles.

I have also found there were images in the PDF when all these properties where there, and no images if any of those properties were removed. The images contain the background color of the two divs separately. The number of such images increases with the number of pages in the PDF. I used pdfimages command.

```
<html>
    <body>
        <div style="margin: 0px auto; width:1005px; border:1px solid  black; border-radius:6px; background-color:blue">
            <div style=" background-color:green; border:1px solid  red;border-radius:6px;margin-top:13px; position:relative;">
                1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>
                11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19<br>20<br>
                21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29<br>30<br>
            </div>
        </div>
    </body>
</html>
```

I tried in Ubuntu14.10 with wkhtmltopdf version 12.2.1

**Comment by san983** [comment]
Found this same behaviour with the following css, as well in Fedora & OSX  with 0.12.1 & 0.12.2.1. Also it spiked the CPU to 100%.
```
.br10fix        { position:relative; background-color:black; }
.br10fix:before { content:''; position:absolute; z-index:10; display:block; width:100%; height:100%;
                  background-color:white; border-radius:10px; }
.br10fix *      { position:relative; z-index:20; }
```
just removing these styles make the process went through fast & smooth :+1:

**Comment by navbhu** [comment]
@san983 check with --dpi option with value as 72.

**Comment by brendon** [comment]
@san983, I think the culprit is most likely to be `border-radius`. I had a document taking about 60 seconds to render and removing `border-radius` brought it down to a couple of seconds!

I'd be interested to hear how you get on with the `--dpi` option too :)

**Comment by san983** [comment]
Thanks @navbhu & @brendon!
Actually with the `--dpi` option it works faster with the original css file :+1: But I decided to keep those styles off since they are not actually needed for my purpose.

**Comment by navbhu** [comment]
@brendon : In wkhtmltopdf QPrinter is initialized with HighResolution (dpi=1200), when dpi argument is used the value is replaced soon after initializing the QPrinter. I checked in PhantomJS where the dpi is set to 72 by default. 

@ashkulz  : correct me if I'm wrong.

**Comment by rthakur** [comment]
@navbhu  Yes, you are correct slow down issues due high resolution dpi, if we use dpi=80 or less then it works perfectly. @ashkulz can you update default dpi, it is really hard to find devs why wkhtmltopdf getting too slow.

**Comment by brendon** [comment]
You're right in that it was the DPI setting causing problems for me too. 72dpi did the trick in the end. I'm going to see if `wicked_pdf` can set that as a reasonable default.

**Comment by P9GIT** [comment]
Just a note that might help others.

After this commit our PDF creation ceased to function resulting in empty PDFs (no exceptions) on some systems (a test machine using Ubuntu and a developer machine with Linux mint, but worked on another developers Linux Mint). We are using wkhtmltopdf 0.12.1.

I finally traced this back to the dpi defaulting to 72. Raising it to say 100 made it work.
I haven't tracked this issue deeper to find out what the underlying reason is, but still this might be helpful if you're experiencing breakage after getting wicked_pdf version 1.0.2.

Best regard,
Thomas.

**Comment by brendon** [comment]
Hi Thomas. Thanks for letting everyone know. `wicked_pdf` has released a new gem version that reverts that change.

If you have the time and inclination it'd be really good to know what the differences in the environments were. Were you using prebuilt packages in each?

**Comment by P9GIT** [comment]
Hi Brendon.

I've done some more digging and it seems this issue is related to this ticket (don't mind the windows stuff, the issue also found on linux): https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1863

I haven't found a way to test/print the qt_defaultdpi value, but setting dpi in wicked_pdf to 75 (supposed to be default on Ubuntu/Mint) made it work with wkhtmltopdf 0.12.1 and wicked_pdf 1.0.2.

Setting dpi below (74 or the 72 default in wicked_pdf 1.0.2) re-introduced the breakage.
Migrating to wkhtmltopdf 0.12.2.x also fixed the issue. Also when using wicked_pdf 1.0.2.

This seems to confirm that my qt default dpi is 75 and the issue seen by me is the same as reported in the github link.

Cheers,
Thomas.

**Comment by brendon** [comment]
Thanks Thomas, that's quite interesting. I'll let David know and see what he wants to do with a default in light of this :)

**Comment by tbrianjones** [comment]
CSS Radius was causing 95% of my render time.

I have a relatively simple html page (400 lines of code, half css, a few tables, and one small logo image). It was taking 6+ seconds per page to render the pdf (which resulted in two pdf pages because of a purposeful break i added). I tried a bunch of things and nothing made a difference until i removed a couple radii in my css. Processing dropped from six seconds to <0.5sec.

**Comment by brendon** [comment]
@tbrianjones, take a look at what resolution your documents are rendering at too. This makes a difference along with the radius. I guess there's a bug in the routine that draws the curves, and at high resolution it takes ages.

**Comment by frenkel** [comment]
I'm not sure whether my colleageus have this exact same issue, but we have a number of Macs that take more than ten seconds to render even the simples HTML files. One other Mac with the same hardware and software renders it in less than one second.

Using dtrace we've discoved that the slow Macs do ten times as much calls to `geteuid`, ranging from 9600 to 11300, while the fast Mac does it with only 500 such calls. Does this info help to find the cause?

You can test it yourself using: `sudo dtruss wkhtmltopdf in.html out.pdf 2> out.txt && grep geteuid out.txt | wc -l`

**Comment by frenkel** [comment]
We've solved it already by removing all custom fonts. Rendering speeds went from 10 seconds to 1 second. Hope this helps somebody.

**Comment by jtomaszewski** [comment]
@frenkel what version of wkhtmltopdf do u have on your Mac?

**Comment by frenkel** [comment]
They use 0.12.3, because 0.12.4 has a regression.

**Comment by mitchdowd** [comment]
Watermark text with a 0.5 opacity across each page took my processing time from 0.7 seconds to 47.5 seconds, and the size of the document from 180kb to 2.2MB.
