### ISSUE TITLE
proxy settings do not allow bypassing local addresses

### ISSUE THREAD

**Issue by elerch** [wkhtmltopdf/wkhtmltopdf#1565]
When specifying a proxy but pointing to a web page on localhost (or 127.0.0.1), one would expect that the proxy is bypassed for the page or any resource sourced from localhost.

I was having issues with this configuration and determined that the proxy is not bypassed. In line 197 of multipageloader.cc (https://github.com/wkhtmltopdf/wkhtmltopdf/blob/efbc7235c4239294e8de56821ad6bb2bf997bf1e/src/lib/multipageloader.cc#L197), setProxy is called, which sets all requests to the proxy set in the settings.

I believe this needs to be changed to the setProxyFactory (http://qt-project.org/doc/qt-5.0/qtnetwork/qnetworkaccessmanager.html#setProxyFactory) with the factory method in turn making a determination of local vs. remote and returning the appropriate QNetworkProxy.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
