### ISSUE TITLE
wkhtmltopdf grabs mobile site

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#1580]
OS: Debian 7.4 64bit
Version: 0.12.0 and d026b5bcddde0316c2a4e2d2d1907cb4184ca460

wkhtmltoimage
![anandtech](https://f.cloud.github.com/assets/5752208/2354644/ade513ee-a5c6-11e3-9724-e7bbf5cc211b.png)
![brc](https://f.cloud.github.com/assets/5752208/2354645/ade7503c-a5c6-11e3-8374-f80f95c5f4ac.png)

wkhtmltopdf

![failanandtech](http://i.imgur.com/0MKR7WN.png)

![failbrc](http://i.imgur.com/jVS9dXx.png)

I've tried anandtech.com and brandonchow.net. wkhtmltopdf grabs the mobile version, but wkhtmltoimage works fine. I've even tried patching this to a higher default screen resolution 1024*768 as mentioned in #1508 comment 2

![unpatched](http://i.imgur.com/86E45JF.png)

![patched](http://i.imgur.com/0NAgW89.png)

, but it still results in grabbing the mobile site. --disable-smart-shrinking does not fix it either.

**Comment by JD-Robbs** [comment]
I just tried adding `'viewport-size' => '1280x1024'` inside the `addOptions()` call and inside the options parameter when instantiating `\Knp\Snappy\Image`. However, unfortunately, this makes it fail without a notice. 

Would anyone know how this option can be added? Not sure, but maybe this option should be available within Snappy.

**Comment by Pagise** [comment]
I now use xvfb-run AND the viewport setting to get it closer to what it should be, but it's still a mess. Setting the orientation to landscape is a nice trick.. but then it is printed sideways (duh)... and I want it as portrait. How do I do this?

As I said, it's getting closer, but i still have problems with the menu at the top (totally wrong.. it takes a chunk off the left side and the rest of the page misses a chunk on the right side. Now since the xvfb and viewport are the same, does wkhtmltopdf add padding to the results.. which could take off chunks on both sides?

**Comment by aindong** [comment]
this is still an issue

**Comment by onzinsky** [comment]
@aindong I agree with you.  

I only get  **usable results** using -l or --lowquality which 

> Generates lower quality pdf/ps. Useful to
                                      shrink the result document space

as stated in the [Autogenerated Docs here](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt).

And **does not** at all prints a low quality pdf.

**Comment by saqibshaikh15** [comment]
you can pass argument for desktop eg.. htmlSourceFile + " " + "--viewport-size 1280x1024 " + outputPDF File;
