### ISSUE TITLE
PDF Accessibility

### ISSUE THREAD

**Issue by Htbaa** [wkhtmltopdf/wkhtmltopdf#1605]
Is it possible to create accessible PDF files with wkhtmltopdf? Such as using alternate text for images, proper document structure and tagging? The subject is rather new to me, but I do consider it to be an important one. Governments for example require PDF documents to be accessible.

I've tried analyzing some generated documents with wkhtmltopdf with this tool (http://www.access-for-all.ch/en/pdf-lab/pdf-accessibility-checker-pac.html) and I believe it can also be done with Adobe Acrobat Pro X. But so far the results aren't too good.

If it is supported, how can I utilize wkhtmltopdf to create accessible PDF files?

**Comment by srikanthvittal** [comment]
My sincere appreciation to ashkulz for his professional response.

**Comment by roelvangils** [comment]
I've read this discussion from 2015 with great interest. I think it's regrettable it had to end this way, although I do understand @ashkulz's response. I have a lot of respect for the open source community.

The matter of the fact is that there still lies a big opportunity in supporting heading levels (and alt attributes for images) in exported PDFs since there is still **no open source** (CLI) tool that supports these basic accessibility features (which have long been baked in into Adobe's export tools).

There is a new and important [European legislation](http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016L2102) regarding accessibility requirements that explicitly requires all documents published by governmental, NGOs etc. to be made accessible. It says:

> Content of websites and mobile applications includes textual as well as non-textual information, **downloadable documents** and forms, and two-way interaction such as the processing of digital forms and the completion of authentication, identification and payment processes.

I think the open source community would do tons of developers a huge favour by adding this — I hesitate to say, but I think in fact rather easy to implement — feature in wkhtmltopdf. I do have a background in server side scripting and front-end development, although I'm not at al an expert in building software.

Currently, the only solution to expert accessible ('tagged') PDF, is to use expense software by Adobe itself.

For those who don't know, these are the characteristics of a fully accessible PDF. An accessible can easily be read by, for example, blind uses (using screenreader technology).

- Valid reading order has been established for all page content
- Tags have been created and validated for all logical content
- Images are given correct alternate descriptions
- Tables are correctly tagged to represent the table structure
- Form-fields, links and other interactive and multimedia features are managed to ensure their maximum usability
- All characters include valid To Unicode assignments

Using Acrobat Professional, it's fairly easy to add these features to a PDF. Also, when one exports a PDF from MS Word using the Adobe Acrobat Export feature, it creates these tags automatically.

Unfortunately, I have no knowledge of the underlying technology of a PDF. However, I see that wkhtmltopdf very nicely exports an hierarchical table of contents (that I can access in Preview.app on the Mac and in Adobe Reader on PC). For that, it looks at the HTML heading elements (`<h1>` to `<h6>`). So I assume, instead of creating generic containers for these headings in the exported PDF, wkhtmltopdf could also borrow these tags somehow.

If you want me to do some research on this, or if I can answer any more questions, let me know. I'd be happy to work with you to make this a reality.

**Comment by mb21** [comment]
You can also [use ghostscript](https://superuser.com/a/189045/247552) for PDF -> PDF/A.

**Comment by Mariusmssj** [comment]
Have there been any news or developments in this area to get better PDF/A support?

**Comment by ashkulz** [comment]
Not really :disappointed:

**Comment by canvaspixels** [comment]
I will upload some examples shortly @ashkulz This would really benefit users with disabilities.

**Comment by Mariusmssj** [comment]
> 
> 
> I will upload some examples shortly @ashkulz This would really benefit users with disabilities.

Well it has also become an EU law to have PDF accessibility

**Comment by ga5tan** [comment]
So if I have accessible HTML I wont be able to convert it to accessible PDF with this tool ?

**Comment by ashkulz** [comment]
Nope, you can't :slightly_frowning_face:

**Comment by ajntc** [comment]
Accessibility checkers for PDF states that PDFs generated using `wkhtmltopdf` don't  have `/Lang` entry. Can this be achived somehow? I have tried setting lang for multiple elements on simple HTML page and `/Lang` had never been set.
