### ISSUE TITLE
--header-html not working if cover page is used

### ISSUE THREAD

**Issue by harmant** [wkhtmltopdf/wkhtmltopdf#1676]
Sample files:
https://gist.github.com/harmant/5eb432e5f9850a60991d

Test system: Ubuntu 14.04 64bit, Debian Jessie 32bit
1. Without cover page (0.12.X) - OK:
   wkhtmltopdf --header-html header.html test.html test.pdf
   ![2014-04-30 13 05 14](https://cloud.githubusercontent.com/assets/5616416/2840017/ff142ae0-d04e-11e3-9fae-1818a39b269f.png)
2. With cover page (0.12.X) (used page option) - BAD:
   wkhtmltopdf cover cover.html test.html --header-html header.html test.pdf
   ![2014-04-30 13 09 24](https://cloud.githubusercontent.com/assets/5616416/2840065/8604faac-d04f-11e3-82f3-e58b707174b4.png)
3. With cover page (0.12.X) (used global option) - BAD:
   wkhtmltopdf --header-html header.html cover cover.html test.html test.pdf
   ![2014-04-30 13 10 46](https://cloud.githubusercontent.com/assets/5616416/2840084/b776ccdc-d04f-11e3-8aa2-0fa8888e854b.png)
4. With cover page (0.10.rc2) (used global option) - OK:
   ./wkhtmltopdf-old --header-html header.html cover cover.html test.html test.pdf
   ![2014-04-30 13 11 52](https://cloud.githubusercontent.com/assets/5616416/2840099/e396b7fa-d04f-11e3-9ec1-61df01ca7703.png)
5. With cover page (0.10.rc2) (used page option) - OK:
   ./wkhtmltopdf-old cover cover.html test.html --header-html header.html test.pdf
   ![2014-04-30 13 14 14](https://cloud.githubusercontent.com/assets/5616416/2840120/33f02fd8-d050-11e3-8d4c-7906d6155018.png)

P.S. --header-left, --header-right, etc. working well with cover page, problem only with --header-html

Updated: --footer-html has the same problem.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by Shad0ko** [comment]
Great, thanks gonna test it soon.
Thank you for the work !

**Comment by Moskydesign** [comment]
I tried 0.12.2 but it still doesn't seem to work

wkhtmltopdf cover /tmp/stappenplan_pdf_cover.html --header-html /tmp/stappenplan_pdf_header.html --footer-html /tmp/stappenplan_pdf_footer.html --footer-left "Page [page] of [toPage]" /tmp/stappenplan_pdf_body.html stappenplan.pdf

**Comment by ashkulz** [comment]
Look up above to the first post on how a bug should be reported. Just saying it doesn't work is not proper etiquette.

**Comment by daviferreira** [comment]
Still happens to me, ```--footer-spacing``` and ```--header-spacing``` are being added to the cover page.

My command:

```
wkhtmltopdf --encoding utf8 --page-size A4 --footer-html footer.html --header-html header.html --margin-left 0 --margin-right 0 --footer-spacing 20 --header-spacing 20 --user-style-sheet pdf.css cover cover.html body.html out.pdf
```

On a side note, I'm trying this as a hack to get different margins on the cover page, would be nice to have this as a feature :smile:

**Comment by ashkulz** [comment]
@daviferreira: please report the `--footer-spacing`/`--header-spacing` problem as a separate issue. Not sure if the margin can be changed once printing has started with `QPrinter`.

**Comment by kohloth** [comment]
In reference to daviferreira commented on 30 Mar, I have this issue too. It is related to the cover.
The pdf requires margin-bottom to be set to a value (i.e. 20) for the footer to show on the PDFs pages, but setting margin-bottom means that you also get a white space at the bottom of the cover page too, which is a problem if your cover is a dark color. I issued a workaround whereby the footer-html page I specified outputs a block of color if the $page GET variable indicates its the "first page" (the cover), and then page numberings and a small logo if not. However, in my opinion it would be better if you didn't have to use margins to create a space for the footer to appear in, or if the cover did not show margins when set, only other pages.

**Comment by anvesh1** [comment]
I have a solution for this and you can put this code:-

        $snappy->setOption('margin-top', 20);
        $snappy->setOption('margin-bottom', 15);
        $snappy->setOption('margin-left', '0');
        $snappy->setOption('margin-right', '0');

        $snappy->setOption('cover', 'url'');
        $snappy->setOption('header-html', 'url');
        $snappy->setOption('footer-html', 'url');

It will definitely work because i am facing the same problem and the code above resolve this.

**Comment by RiddP** [comment]
I have exactly similar issues. 
My header is 55px, footer 20px. To make header and footer visible, i have to use margin-top 55px and margin bottom 20px. 
By doing so, all pages except Cover, works fine BUT, Cover gets 55px blank space at bottom and 20px blank space on bottom.
If I remove Margin-top or make it 0, Cover pages start from starting of page i.e works fine but from 2nd page onward, i lose header i.e no header at all. 
So no solution is working for me. 

Please help us. We have 15 pages dynamic PDF already generated and work done by consuming many hours. but we stuck with cover page white space and have to use some other html to pdf generating tool because of this one issue.
By unknowing i added same issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2738

**Comment by tarekmonjur** [comment]
Please anybody help me.
my footer working good,but header not working. I try this..
```   
 \PDF::loadView('resume', $data)
      ->setPaper('a4')   
      ->setPaper('a4')
      ->setOption('margin-top', 16)
      ->setOption('margin-bottom', 12)
      ->setOption('margin-left', 0)
      ->setOption('margin-right', 0)
      ->setOption('header-html', url('load-pdf-header'))
      ->setOption('footer-html', url('load-pdf-footer'))
 ```
 I use this binary..
            'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
and my system is ubuntu-14.04 LTS

**Comment by krazyest** [comment]
I can confirm that wkhtmltopdf 0.12.2.4 (with patched qt) have a problem when you have header-html / footer-html and full size cover page image. 

The problem is that either you have a perfect cover page (using -T 0 -B 0 -L 0 -R 0), but then you have no headers and no footers on other pages, OR you have your headers and footers, but your cover page has blank space at the top (the size of the header).

So, currently, you can't have a full size cover page image and have headers and footers on other pages.

**Comment by jossef** [comment]
## @tarekmonjur, :+1: 

faced the same issue, as a workaround i'm duplicating my app, creating 2 pdfs
- cover.pdf
- content.pdf

using [this](http://stackoverflow.com/questions/4184174/how-to-merge-many-pdf-files-into-a-single-one) approach, i'm merging these into one file 

hopes this helps for now

**Comment by krazyest** [comment]
@jossef Little bit of pain, but your solution works! I am now using command line Pdftk to get the final document from the two. The pain was with the broken in-document links, but I have figured how to deal with that by adding a dummy cover page to the main document. So all good!

**Comment by mauriciojaramillo** [comment]
Hi All

"daviferreira commented on 30 Mar 2015
Still happens to me, --footer-spacing and --header-spacing are being added to the cover page.

My command:

wkhtmltopdf --encoding utf8 --page-size A4 --footer-html footer.html --header-html header.html --margin-left 0 --margin-right 0 --footer-spacing 20 --header-spacing 20 --user-style-sheet pdf.css cover cover.html body.html out.pdf

On a side note, I'm trying this as a hack to get different margins on the cover page, would be nice to have this as a feature "

This post was very usefull for me to understand the command line parameters order, thanks.

**Comment by ionut-ai** [comment]
Hey,

I've been trying to get around this header / footer issue also (on version wkhtmltopdf 0.12.2.4 (with patched qt). I found a workaround that was starring me in the face.

I believe that the margins should be per section ('page', 'cover', 'toc' etc.) and not document wide, but I don't know about the QT Printer limitations. As far as I can tell, the whole pdf "printing" process is done in stages, one for the content sections (all 'page's), one for the toc, and one for the headers/footers.

First, I think the term "page" is a bit unfortunate, and I prefer to call it "section" when referring to document parts.

So, considering the scenario for my document:
- I have a cover page (or multipe one page covers) that needs to fill the entire page, without any header and footer
- All my document pages have headers and footers (including TOC)

As mentioned before, adding a margin-top/bottom will also add them to the cover page. I need the _**cover page**_ (which in my case is _**ONLY one page**_, this is important) to disregard margins, also, I do not want to use third party tools to generate my PDF.

What I found out is that:

- Left and right margins apply also to the header and footer which is BAD. A workaround is that these will be managed by the container element style in the page.
- Top and bottom margin do not apply to header and footer but rather the text offset from top/bottom (section margins per page).
- The margins do however influence the available space for the header / footer. Size for header/footer should reflect this.
- Header/footer can bleed to content, but content cannot bleed to header/footer (out-of-bounds/negative margins do not apply).

Following my findings, and the last item above, I came up with the following solution for my cover page: 
- I am using a normal section ('page') for my cover. This means that the normal sections ('pages') need to have a `page-offset` of '-1' (or minus the number of covers).
- Instead of using the content for the cover I am using the header-html (this also opens the possibility to use variables in the template). This also requires some blank content. Because webkit allows data urls I am using `data:text/html,` as content url.
- In order for the header to fill the entire page the header spacing value must be the result of "margin-top" minus `page-height` in mm (e.g. `margin-top = 31.7`, A4 page results in a `header-spacing` of 31.7 - 297 = -265.3. As you can see negative and non integers work too.

So, to make it all work for my pseudo-cover the command should be something like this:

`... --margin-top 31.7 --page-size A4 page data:text/html, --exclude-from-outline --header-spacing -265.3 --no-header-line --disable-toc-back-links --header-html cover.html page page-offset -1 ...`

Hopefully this saves you some time.

**Comment by GCSBOSS** [comment]
@ionut-ai, I could not understand how to overcome the horizontal margins on header. Would you explain it to me in more detail?

By the way, is any of you guys ever going to fix this issue?

**Comment by stguitar** [comment]
@krazyest Wow, i had not thought of using a dummy pdf, but thats what im now doing.  For others, what i did was create an essentially blank page that goes into the WKHTMLTOPDF input list of files.  my cover page is actually already a PDF file.  once the main full doc is generated, i use PDFKit to strip that dummy cover page off, and then again to append the actual PDF cover page to the document.

**Comment by Jc-L** [comment]
@stguitar Doesn't playing with PDFKit break all bookmarks, links, and table of content in the pdf ?

**Comment by stguitar** [comment]
@Jc-L for my use case, I actually generate the table of contents in the source HTML as just another page. This was because I have to style things appropriately.  As far as links and bookmarks, the only thing i have for my documents are html anchor based links in the source HTML, and those are not impacted by my approach as mentioned above.  My application compiles several HTML pages into one source html doc that goes into WKHTMLTOPDF.

**Comment by Jc-L** [comment]
@stguitar : you can style and generate all the table of contents by providing an xml (dump the default with --dump-default-toc-xsl and provide it after adjustments with --xsl-style-sheet). One issue is that external css does not work well in this case, but inline css does.

**Comment by jlongbottom** [comment]
I have been struggling with this use case for a while now. It sounds like there is simply no way to have a full-page cover using only wkhtmltopdf while still having headers and footers on subsequent pages.

**Comment by PleaseCallMeXiuye** [comment]
我猜测，参数 --footer-* 和 -L -R -T -B 有冲突。
;可以正常显示页码, it work.
wkhtmltopdf   --footer-right '[page]/[topage]'  https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1676 test.pdf
;不正常，显示不了页码, it don't work.
wkhtmltopdf   --footer-right '[page]/[topage]'  -L 0mm -R 0mm -T 0mm -B 0mm  https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1676 test.pdf

**Comment by yukagi** [comment]
Is there even a way to get a full page cover (with the top and bottom margins) with header and footer on subsequent pages? I'm using header_html and footer_html for the headers/footers. This is the command I'm using:
```/usr/local/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 cover <PATH_TO>/cover_output.html --header-html <PATH_TO>/header_output.html --header-spacing 3 --footer-html <PATH_TO>/footer_output.html --footer-spacing 6 toc --xsl-style-sheet <PATH_TO>/plan.xsl - -```

And I'm still just getting a cover sheet without the headers/footers.

**Comment by Jc-L** [comment]
@yukagi : You cannot have both headers/footers and full-page cover. Mixing both will make the reserved space for footer/headers appear on the cover page.
You can achieve what you want my cobining wkhtmltopdf with other pdf edition tools, however this is likely to break your table of contents.

**Comment by yukagi** [comment]
@Jc-L I'm fine with the empty space (no content in header/footers) on the cover page, but I do want header/footers on the content pages. What I'm seeing is no header content anywhere when using a cover page.

**Comment by netwons** [comment]
hi
I run these code but it does not get a header؟
`wkhtmltopdf --header-html morg header.html simple1help.pdf`

**Comment by qweluke** [comment]
any news about it? having the same issue :/

**Comment by CrisConter** [comment]
Hi Everyone. I had this problem before. My solution was put cover at least parameter:
`--footer-right "Page [page]" --header-html header.hmtl content.html cover cover.html pdf.pdf`

**Comment by ahmedfahmy2003** [comment]
> ionut-ai

Wow , it was aa great solution.
Thank you so much @ionut-ai
