### ISSUE TITLE
Cover page without margins not working

### ISSUE THREAD

**Issue by alex3305** [wkhtmltopdf/wkhtmltopdf#1720]
In the man-page/manual it is defined that cover pages without margins are supported, however when I tried this with various versions (since 0.9.9) covers don't seem to work without margins. I still get the default margins for the other pages on my cover.

Is this fixable, a workaround or am I just doing it wrong? The syntax I'm using is:
`wkhtmltopdf cover cover.html index.html output.pdf`

I could also remove all the margins with:
`wkhtmltopdf -B 0 -T 0 -L 0 -R 0 cover cover.html index.html output.pdf`
but that's not what I want since I also want to set a footer and header for the rest of my pages.

**Comment by julienkrs** [comment]
I would like to add that this issue is not resolved for me, unless I am missing something.
Please help me out there.

Using wkhtmltopdf 0.12.2.1 (with patched qt) under Ubuntu 15.04 I want to achieve the following:

- keep margins everywhere EXCEPT on the frontpage
- on the frontpage, I do not want any margins

Let's try the following (for this I'll put wikipedia as the cover for my pdf, google being the content - just for the example):

a) wkhtmltopdf --margin-top '0' cover http://www.google.de http://wikipedia.de test.pdf
As expected, I get a pdf with cover and content, both have margin top set to 0.

b) wkhtmltopdf cover http://www.google.de --margin-top '0' http://wikipedia.de test.pdf
Doesn't work..
Now the documentation tells me this:
cover <input url/file name> [PAGE OPTION]...

So how is it that I cannot do case B ? Software bug or did I do something wrong ?
