### ISSUE TITLE
Hyphenation with soft-hyphens (&shy;) does not work

### ISSUE THREAD

**Issue by mn4367** [wkhtmltopdf/wkhtmltopdf#1722]
wkhtmltopdf no longer respects soft-hyphens so words are not broken at positions where a manual break is suggested. A sample document to test is [here](https://gist.github.com/mn4367/57bbed35f643a9a0f40f). This is a bit strange since this worked with earlier versions like 0.11.0rc2.

Tested with version 0.12.1-7fac78c on OS X (Carbon and Cocoa) and 0.12.1-c22928d on Windows 7 64 (MSVC 2013).

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by xdestiny** [comment]
Can confirm that visible hyphenation is working in 0.12.2.1. 

There is, however, one big difference to how hyphens are present in the PDF file. Copying or searching through a PDF with Acrobat becomes impossible (other PDF viewers like Foxit Reader might work).

This happens to text that has been prepared with &shy; elements but has no visibly hyphenation in the PDF file because it does not need to fold around the document's edge, for example "major&shy;ity" in the middle of a line. The text "majority" cannot be found in the document and will have spaces instead of the soft hyphens when copied to a text document. The example would appear as "major ity".

This was not true for PDFs created with 0.11rc1, although this may not directly relate to the issue at hand.
