### ISSUE TITLE
Support osmesa for server-side WebGL

### ISSUE THREAD

**Issue by t-oster** [wkhtmltopdf/wkhtmltopdf#1742]
For browsers/devices which do not support WebGL we'd like to use wkhtmltopdf/image to render our WebGL scene (three.js) server-side and just transmit the image to the client.
Basically everything works, but only with canvas-renderer. Of cause most servers do not have any graphics card, so there is no hardware OpenGL support.

Anyhow, I recently learned about osmesa (http://www.mesa3d.org/osmesa.html). Since wkhtmltopdf is using webkit, and chromium, which also uses webkit has osmesa support (https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/NpsDdbtSRsU). I thought it may be not so much work.

It would make wkhtmltopdf the no. 1 server side rendering tool for all three.js users at least (see http://stackoverflow.com/questions/14015073/server-side-fallback-rendering)

**Comment by fractalawareness** [comment]
I also need osmesa support. Is it possible to hack it together using alpha release which uses Qt 5.4.2? Any hints will be appreciated.
Using Chromium-dev instead of wkhtmltopdf is not possible in my case due the poor quality images with css filters in PDF produced by Chromium built-in "print" feature and lack of header/footer etc.
