### ISSUE TITLE
wkhtmltopdf 0.12.0-OSX: Massively large PDF file size and non-selectable text

### ISSUE THREAD

**Issue by gnapse** [wkhtmltopdf/wkhtmltopdf#1747]
I'm having the exact same problem stated [here](https://code.google.com/p/wkhtmltopdf/issues/detail?id=886) and I can't see any corresponding issue here on github, so I'm bringing it up.

I have an app that generates some html documents that are then converted to PDF using wkhtmltopdf. Also, I cannot use versions below 0.12.0 because they truncate ttable rows, and this is a problem with the documents I'm dealing with.

So the problem is that, with wkhtmltopdf 0.12.0 in OSX, the resulting PDF files are around 40+ megabytes in size, even when the original HTML files are no larger than 1.5 megabytes, all text, no images at all. After finding that thread linked above, I realized that the problem is exclusive of OSX versions from 0.11.0 on. I went on a to a Linux box to test this myself, and the very same html file I tested on OSX, resulted in a 300k PDF file (!!!).

Also, as stated in the title of this issue, in the large PDFs the text is not selectable, as if the pages are images, which could explain the large file size.

Fortunately, in production, this app of mine will be working in Linux, so I won't be having this problem, but it's very annoying when developing on Mac, since also the generation process takes more time and CPU or memory, whereas in Linux the same html file was processed much quicker, it's smaller, and the text is selectable.

**Comment by lmeurs** [comment]
I encountered the same on Windows 7 + `wkhtmltoimage 0.12.2.2 (with patched qt)` when loading the fonts in the default way (opposed to installing the fonts on the Windows):

1. Large files: >1MB for a simple text PDF,
2. Unselectable text,
3. The PDF's document properties did not show the fonts as embedded.

This could be circumvented by not loading the web fonts.

## Obfuscated fonts
But I noticed some other fonts *did* make it into the PDF correctly. After many tests my conclusion is that only fonts bought at MyFonts.com cause trouble, probably since these files [can be obfuscated](http://blog.typekit.com/2009/07/21/serving-and-protecting-fonts-on-the-web/) to prevent theft.

Though I am not a font expert and I doubt the purchased license of the font allows me to do so, but the easiest way I could think of to rebuild the fonts (for testing purposes only!) is by turning the [SVG file into TFT](https://cloudconvert.com/svg-to-ttf) and using this TFT to [generate a new font-face pack](http://www.fontsquirrel.com/tools/webfont-generator). Again, only for testing purposes..........

The generated PDF is now <50KB, text is selectable and the fonts show up as embedded in the document properties window.

**Comment by sbitproz** [comment]
For people still landing here, I experienced a similar issue with the specific line in my 

`<style type="text/css">@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);</style>`

My PDF files were around 29MB and the server would fall over.

Thankfully I didn't need the fonts and simply removed them.
