### ISSUE TITLE
Single page & full size rendering

### ISSUE THREAD

**Issue by marc-ic3** [wkhtmltopdf/wkhtmltopdf#1782]
I'd like to generate a single PDF page (A4) with my HTML using the whole available space. So I've created a simple HTML and set an explicit A4 size to the body in mm with a bunch of div with explicit sizes and absolute positions to check the PDF rendering.

The HTML is available here:

http://www.iccube.com/downloads/wk/html.html

Then using the command line:

wkhtmltopdf -T 0 -R 0 -B 0 -L 0 --orientation Portrait --page-size A4

The results are here:

http://www.iccube.com/downloads/wk/linux_result.pdf
http://www.iccube.com/downloads/wk/windows_result.pdf

On Linux, the page is rendered quite as expected (merely a tiny margin on the right and bottom I guess I can live with). 

But on Windows, there is a marge of several cm at the bottom and the width of the div are wrong of several cm.

Is that the expected rendering ? Any way to generate the PDF as expected ?

Why so much differences in the rendering between Linux & Windows. I would expect WebKit performing the same rendering on the both platform for that very simple HTML ?

Thx.
_ 

Linux ( Ubuntu 64 bits 12.10 ) 32 bits version of wkhtmltopdf:

wkhtmltopdf --version
wkhtmltopdf 0.12.1-9615f00 (with patched qt)

Windows ( 7 64 bits ) 32 bits version of wkhtmltopdf:

wkhtmltopdf.exe --version
wkhtmltopdf 0.12.1-9615f00 (with patched qt)

_

**Comment by rainabba** [comment]
I've been developing with 12.3 and running 12.2 in production. I just noticed after another issue (blank PDFs) creeped up in production so I updated to 12.3. Now I'm seeing this same scaling issue where on my development machine (Windows 10 Pro x64), things have been good for as long as I can remember, but in production (Windows Server 2012 where things have also always been good), suddenly it's as if I'm zoomed way out (content is too small), but everything still stretches to fit the page appropriately. I've been using DPI: 96 for as long as I can remember.

I applied zoom: 1.33 and on my dev machine, content was now too large and in production, larger, but still too small.

Something suddenly occurred to me! Last night I'd RDP'd to my server from my Surface Book which has a 3000x2000 13.5" display and uses 200% scaling. When I RDP'd into the server today FROM MY WORKSTATION (which is using 96DPI @ 100%) where I typically do it from, the scaling was off and everything was huge; still scaled for my Surface Book I'd say. I checked the scaling setting and it was still set to 100%, but I changed it away and back then hit apply which prompted me to sign out. I did, reverted the zoom setting and now scaling is fine.

CONCLUSION: Without a doubt, the resulting PDF is affected by zoom AND the windows UI scaling state. If nothing else, this explains the difference between Windows and other OS's because results generated on Windows will be subject to scaling but may OR may not be on other OS's.

**Comment by zardilior** [comment]
I would say that a so needed feature is to ignore the os's and be able to specify in the options the sizes, and units, and everything else should be calculated to fit. For example minimum font size on 0.12.3 was particularly troublesome.
