### ISSUE TITLE
*** buffer overflow detected ***: wkhtmltopdf terminated

### ISSUE THREAD

**Issue by fitterfly-fenil** [wkhtmltopdf/wkhtmltopdf#1819]
Hi,
While trying to generate large PDFs with more than 150 pages with header and footer I get an error - **\* buffer overflow detected ***: wkhtmltopdf terminated. Could anyone let me know what could be the possible reason for this?

**Comment by avoinea** [comment]
Same issue here. 
PDF size: 226 pages
ulimit -n 4096
ulimit -u 4096

It works without header or footer, but it doesn't with both. 

```
wkhtmltopdf --page-size A4 --page-offset 2 --print-media-type --encoding utf-8 --debug-javascript --margin-top 32 --margin-bottom 32 --margin-left 20 --margin-right 20 --no-outline --javascript-delay 200 toc --xsl-style-sheet toc.xls --disable-toc-links http://example.com/countries/pdf.body --load-error-handling ignore --header-html http://example.com/countries/pdf.header --header-font-size 9 --header-spacing 5 --header-font-name Verdana --footer-html http://example.com/countries/pdf.footer --footer-font-size 9 --footer-font-name Verdana --footer-spacing 5 out.pdf
```

**Comment by joshuapinter** [comment]
Having the _exact_ same issue here.

I'm generating PDFs that are between 500 - 1000 pages in length, although very simple data tables. Including the header and footer causes this buffer overflow issues.

The original problem was "Too many open files." which was fixed by adjusting the `nofile` limit on the servers. 

Any updates or suggestions with this, guys?

Many Thanks!

**Comment by ashkulz** [comment]
@joshuapinter: please post a reproducible test case in a gist or upload it somewhere.

**Comment by joshuapinter** [comment]
Thanks for the response, @ashkulz. I was able to work around the issue by doing two things: 

1. I increased the open file limit and stack size limit of my servers by adding the following config to `/etc/security/limits.conf`:

  ```bash
*    hard nofile 1000000
*    soft nofile 1000000
*    soft stack  81920
root hard nofile 1000000 # Need these two lines as wildcards (above)
root soft nofile 1000000 # are not applied to root.
root soft stack  81920
```

2. Instead of using a S3 image in the header, I store the image locally. Not doing this seemed to required more resources.

You're gonna have to play with the limits to see what works with the size of the PDFs you're generating but it's surprising how high these limits have to be to prevent issues. Ideally, we could refactor wkhtmltopdf to not use so many resources but this is a decent workaround.

**Comment by daniar23** [comment]
Unfortunately increasing stack size and open file limit didn't bring me anything. But then I found out that the problem was in setting up pathes of footer and header with http urls. So I've changed them to local pathes and it solved the problem.

**Comment by joshuapinter** [comment]
@daniar23 Can you give an example of what your header and footer paths looked like before and then after you changed them?
