### ISSUE TITLE
Relative links not working

### ISSUE THREAD

**Issue by jedvardsson** [wkhtmltopdf/wkhtmltopdf#1843]
It seems like relative links aren't working. For example,

wkhtmltopdf http://docs.oracle.com/javase/8/docs/api/java/util/AbstractMap.html test.pdf

open test.pdf in a pdf-viewer and click on "overview" at the top of the first page. A browser window displaying "http://docs.oracle.com/javase/8/docs/api/overview-summary.html". However, on my Mac, the pdf viewer complains that it cannot open the link since it is relative "../../overview-summary.html".

I used wkhtmltox-0.12.1_linux-precise-amd64.deb to generate the pdf, and opened it on a Mac OS X Mavericks.

Edit: Fixing typos and grammar in third paragraph.

**Comment by juzzlin** [comment]
Why is this bug invalid? 

For example, the online demo at http://www.essentialobjects.com/Products/EOPdf/UrlToPdf.aspx renders the links in that Oracle page correctly. 

I run into this with a page that had links like <a href="videos/video.mpg">Download video</a>. Other converters I tried concatenated the base url of the site to the links to make the links work in the pdf, but wkhtmltopdf didn't.

**Comment by pixelb** [comment]
This used to work on older versions. I would also expect the old behavior that,
relative links are converted into absolute ones with respect to the url given on command line.

**Comment by KAYLukas** [comment]
Hi, we updated our wkhtmltopdf version on our server and now we are having issues as well. The old behavior seems to be more logical, as PDFs are normally not relative: the whole idea of a PDF is that it contains the whole source no matter where the PDF is opened. Moreover, on OS X opening such a pdf and clicking on a relative link doesn't open the file relative to the document, but causes an 'unknown protocol' message.

That being said, can we revert this change by reverting issue a97c797 in the current source code?

**Comment by ashkulz** [comment]
@KAYLukas: try it and see if it works :smiley:

**Comment by KAYLukas** [comment]
Done seems to work correctly. Also added a flag to be able to toggle this behavior, such that everyone can be happy. (We actually, do also have some usage for keeping the relative links).

I'm not to familiar with the project structure, so I hope someone can review my changes.

**Comment by ashkulz** [comment]
What is the use case for keeping the current behavior? I'd prefer not add an option, because even in your PR you mention that
> Actually, it seems to not resolve relative links, the comment above seem to be incorrect?

So unless there is a valid scenario, I'd prefer simply reverting the change. Thoughts?

**Comment by KAYLukas** [comment]
The comment suggests that it resolves links, while it just keeps relative links as relative links. While the comment suggests it shouldn't behave like it actually did, I do have some usage for these relative links.

I added the flag, because for my use case we need to generate relative links in a pdf, for usage in a mobile app where, where the relative links are used to denote files in the same package as the pdf.

I see this option appear in other products as well (https://www.bluebeam.com/us/support/articles/ask-greg/7-11.asp, http://stackoverflow.com/questions/17800596/relative-file-links-in-pdf-files). I think the main usage would be when considering a package of pdfs that link to eachother. 

Currently, I left the current behavior as the default behavior, I guess it would be better to let the default behavior be the new behavior.

Any ideas?

**Comment by ashkulz** [comment]
The fix has been merged

**Comment by debian00001** [comment]
Hello, I guess I don't quite understand if this is fixed or not reading this?
Should we expect relative links to work or not?

Thanks!

**Comment by ashkulz** [comment]
Read the commit message for bac3fbf9eed3061399a4b528238c39535c2206c0, both behaviors are supported.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by ashkulz** [comment]
[`0.12.3`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Note that the preview downloads mentioned above have been removed*.

**Comment by bismaya123** [comment]
Hi Even i have the same issue, while converting html to pdf using wkhtmltopdf, the page number in the index has link to specific page number in html file. but the link somewhere is breaking and always targeting to the default home page irrespective of the page number in pdf.
