### ISSUE TITLE
Faulty javascript when css media queries are used 

### ISSUE THREAD

**Issue by aleskafka** [wkhtmltopdf/wkhtmltopdf#1861]
When html page uses media queries (e.g. media="screen and (min-width: 768px)"), then javascript doesn't reflect css rules in those files. CSS are loaded and rendered correctly, only javascript is faulty.
#### index.html

``` html
<!DOCTYPE html>
<html>
<head>
    <style type="text/css" media="all">
        body {background: blue; width: 1200px; height: 800px; }
        #test { width: 1px; height: 1px; }
    </style>
    <style type="text/css" media="screen and (min-width: 768px)">
        body {background: green; }
        #test { width: 100px; height: 100px; border: 1px solid black; }
    </style>
</head>
<body>
    <div id="test"></div>
</body>
</html>
```
#### Command:

wkhtmltopdf --viewport-size 1200x800 --debug-javascript --run-script "console.log(document.getElementById("test").offsetWidth)"
#### Expected result:

rendered: green pdf document with 100x100px box with 1px black border starting at [8px,8px] position.
javascript logs '102' into console
#### Result:

rendered correctly, but javascript logs '1' into console. When media queries are removed, javascript behave correctly.
## Versions

wkhtmltopdf 0.12.1 (with patched qt)
Macbook Pro, OS X Mavericks

**Comment by tcopestake** [comment]
I came across this post while I was searching for something else, but just thought this might help: JavaScript doesn't always report the correct size of responsive elements until the page has fully loaded. If you bind your code to window.onload or similar, it may/should work.

**Comment by Jovve** [comment]
Not sure how this relates to the problem, but I found this area in the jquery.datatable.js which deals with the .offsetWidth issue stated above.  I am using jquery datatable v1.10.7 with <th> elements assigned percentages instead of solid px values.  What happens is that a <DIV style="width: 39%;"/> is created and attached to the underlying table object for sizing purposes.  In any modern browser, the header portion of the represented table renders correctly.  Wkhtmltopdf's webkit seems to return a zero (0) when the .offsetWidth is called.  This messes up the header by rendering in the PDF as a compressed header instead of "breathing" like the body of the table does.  Albeit, the jquery data table splits the header and body into two separate tables to the scrollbar is not crossing the header in the Y direction.  This function below is supposed to adjust the header table's headers to match that seen in the body table's headers.  None of this makes sense as to why the body's table is rendered correctly but the header's table does not...well, it depends on the offsetWidth being returned, at least.  What I have done to work around this is to employ some old fashioned modification of the table to strip off the disjointed portion and reenstate the original body's header.  This also takes away the scrollbars on the right to allow the table to display the entire contents at once.


// Work-around code:
<pre>
<code>
    callbackComplete: function(){
        $('div.dataTables_scrollHead').remove();
        var scrollBody = $('div.dataTables_scrollBody');
        scrollBody.addClass('dataTables_scrollHead').css({ "width":"", "height":"", "overflow":"" });
        scrollBody.find('thead').find('*').css({"height":"", "padding-top":"", "padding-bottom":""});
        scrollBody.find('thead div.dataTables_sizing').removeClass('dataTables_sizing');
    }
</code>
</pre>


// This is the jquery datatable function:
<pre>
<code>
	/**
	 * Convert a CSS unit width to pixels (e.g. 2em)
	 *  @param {string} width width to be converted
	 *  @param {node} parent parent to get the with for (required for relative widths) - optional
	 *  @returns {int} width in pixels
	 *  @memberof DataTable#oApi
	 */
	function _fnConvertToWidth ( width, parent )
	{
		if ( ! width ) {
			return 0;
		}
		var n = $('&lt;div/&gt;')
			.css( 'width', _fnStringToCss( width ) )
			.appendTo( parent || document.body );

// Added this debug to monitor the activity
console.debug("________________  fn*width = "+_fnStringToCss( width )+
              ",    div="+$('&lt;div/&gt;').css( 'width', _fnStringToCss( width ))[0].outerHTML+
              ",    offsetWidth="+n[0].offsetWidth+",    clientWidth="+n[0].clientWidth+
              ",    parent="+parent.outerHTML+
              ",    n="+n[0].outerHTML);

		var val = n[0].offsetWidth;
		n.remove();
		return val;
	}
</code>
</pre>
