### ISSUE TITLE
error when convert a local html to pdf 

### ISSUE THREAD

**Issue by thnguyenwk** [wkhtmltopdf/wkhtmltopdf#1886]
Version: wkhtmltopdf 0.12.1  for windows 7 32-bit.
I used it to convert a local html file, this is the error:
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
Exit with code 1 due to network error: ProtocolUnknownError

How do I correct or make it ignore the QNetwork check?

Thank you

**Comment by francoisjacquet** [comment]
We recently experienced this issue on Windows (OK on Linux) where wkhtmltopdf would never finish laoding the PDF from PHP using RosarioSIS.
When executed from the command line, the PDF is generated but this same error or notice was printed

> QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files

The fix was simply to prepend `file:///` to every CSS, JS and image file absolute path, see https://github.com/francoisjacquet/rosariosis/commit/b082b6de2ad90a8fde4f5c3209b291737810e24c

**Comment by sehe** [comment]
That's hardly a fix, since not everybody controls all of the HTML. Rather a good fix would be to support custom protocol handlers or filter the exception

**Comment by Zswdhy** [comment]
![3](https://user-images.githubusercontent.com/52588645/97952911-da268b80-1dd9-11eb-88f3-4ee6df33757b.png)

Using THE HTML set up by the Vue framework, when using WkhtmltopDF, can not be perfectly converted to PDF, display CSS style and JS code load failure, using the enable-local-file- Access command

**Comment by Eesha-Jain** [comment]
Here is a great video! This integrates both HTML + CSS + images into a PDF: https://www.youtube.com/watch?v=zmJV6VN2h2E . Hopefully this helps with your error
