### ISSUE TITLE
Access to Current Page [page] and Number of Pages [toPage] outside of headers and footers

### ISSUE THREAD

**Issue by RafaPolit** [wkhtmltopdf/wkhtmltopdf#1889]
There are many situations where I need to access the page number inside the 'body' of the PDF and not only on headers and footers.  Is there a way to do that, or any implementation that can be made to access the data?

Thanks,
Rafael Pólit.

**Comment by lssilveira11** [comment]
I need this feature too!

Actually, this feature can be veeeery powerfull. Think this way: you have many figures in you webpage. Each figure have a ```div``` bellow them with a ```span``` to show the legend text and a ```input[type=hidden]``` with the value [page] or [frompage]. 

What you can do with this? TABLE OF FIGURES!!

In javascript, you can build a ```ul``` grabbing all the legend of the figures, and then check the value of the ```input[type=hidden]``` to get the page number of that element, **because the process will have replaced the [page] text in the value of these inputs with the actual page number value**.

But, we don't have this feature (yet) ... :(

**Comment by CaroEvans** [comment]
Is this feature still not available?

**Comment by faheemhameed** [comment]
Would be great and very useful to have this feature. Thanks!

**Comment by deruiter2** [comment]
Is there any news on this feature. Would be very useful for a project i'm working on.

**Comment by flyingangel** [comment]
Source: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
Scroll down to example of `function subst()`

**Comment by louissmsfactor** [comment]
@flyingangel Can you please read the subject? They need outside header or footer!

**Comment by aliencrash** [comment]
I have another way we could use this.
For example for invoices that break for different pages, it requires us for the first page create the subtotal and the start of the next page the transported value. At the end the next page, if there is more pages always have a transported value summed up with the rest of the tables.

**Comment by admcfajn** [comment]
@louissmsfactor Could you please not revive topics that are years-old just to correct someone else who is trying to help?

**Comment by louissmsfactor** [comment]
@admcfajn he wrote his answer in september... and he helped nobody, his answer is irrelevant.
@aliencrash did you find a workaround to accomplish this?

**Comment by admcfajn** [comment]
@louissmsfactor you're coming across a bit rude is my point. Frankly cross-posting that relevant info may have helped somebody

**Comment by ashkulz** [comment]
I'm locking this conversation. Although this is obviously good to have, I'm not sure how it can be implemented right now -- the focus right now is upgrading the browser engine (read the project status), this will come after/if it gets upgraded.
