### ISSUE TITLE
Problem with blank page at the beginning of result PDF (associated with issue #1870)

### ISSUE THREAD

**Issue by serovpetr** [wkhtmltopdf/wkhtmltopdf#1903]
wkhtmltopdf Version : 0.12.1.0

Operating System and Version: Windows 7 Enterprise x64 Service Pack 1
Application based on ASP.Net

Description:
Earlier, i had problem with duplicate request headers (issue #1870). Following the recommendations, I put parameter `[page]` before  `--cookie` argument. Now i have problem with blank page before the document's content. Is there any solution to disable render first page? And a big plus will be the ability to save the correct page numbering.

My command line is:

`wkhtmltopdf --zoom 1.5 --no-stop-slow-scripts --page-size A4 --footer-html "http://test" --footer-spacing 0 --orientation portrait --margin-top 10 --margin-bottom 45 --margin-left 10 --margin-right 10 --enable-javascript --print-media-type --load-error-handling abort [page] --cookie <here i put my authentificate cookie> "http://testpage" test.pdf`

**Comment by 0lukasz0** [comment]
I confirm same problem, please reopen.

**Comment by ashkulz** [comment]
Please do not post the same message for related issues.

**Comment by sanjay205** [comment]
Adding Cookie in custom header like "--custom-header Cookie" instead of using [page] worked for me.

This is my sample command :

wkhtmltopdf --header-html http://localhost:52127/ProposalDocument/_Header --footer-html http://localhost:52127/ProposalDocument/_Footer --custom-header Cookie ".AspNetCore.Antiforgery.5uYu5VgZzcE=abc123;JWTToken=xyz123;.AspNetCore.Cookies=xyzabc123" --no-custom-header-propagation http://localhost:52127/ProposalDocument/ProposalDocument D:\htmltopdfTest\test.pdf
