### ISSUE TITLE
Image on header not shown

### ISSUE THREAD

**Issue by bbn-bernard** [wkhtmltopdf/wkhtmltopdf#1925]
I create html header that consist image in binary in table. The image is shown in wkhtmltopdf version 0.11, but not in recent version, 0.12.1 (with patched qt).

**Comment by ashkulz** [comment]
Looks like a duplicate of #2083, using a higher `--javascript-delay` should fix this issue after the regression in #2183 is fixed.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
