### ISSUE TITLE
css border-width not correct

### ISSUE THREAD

**Issue by kwnet** [wkhtmltopdf/wkhtmltopdf#1967]
border-widh style with four entries is not interpreted correct.
"border-width:1px 0px 0px 0px:" results in a border on all four sites.
tested in "td" element on ubuntu (version 0.11.0 rc1)
(Workaround: using border-color to render it white)

**Comment by KFoxder** [comment]
+1

**Comment by PhilterPaper** [comment]
Kind of a shot in the dark, but many graphics applications treat 0 (or negative) width as "give me the narrowest line you can", rather than "give me 0 width". I don't know what the formal definition in CSS is (my books say nothing on that). If it works OK in a browser, one solution would be to specify the border for only the one side (border-left) and don't say anything about the other three sides. If it's a pain to change the HTML, it might require a fix to WebKit.

**Comment by erikmoren** [comment]
I get this also, using 0.12.3.

**Comment by sagarvora** [comment]
+1

**Comment by bilgin1812** [comment]
i have the same problem, if you put border
<tr style="height: 80px;border-top:solid 3px;border-collapse: collapse;font-size: larger">
                    <td>   
                    </td>
                     test
                    </td>
                </tr>

All borders have same thickness

**Comment by Tomsgu** [comment]
This seems to be resolved. I can't reproduce the issue in `0.12.5` Chromium and evince gives the same results. Please feel free to re-open if you are still experiencing this issue.
