### ISSUE TITLE
Temp HTML files are not being removed after execution

### ISSUE THREAD

**Issue by kalbasit** [wkhtmltopdf/wkhtmltopdf#2011]
This might be related to #1981

Our servers are currently getting 'No space left on disk' because of the number of html files left in `/tmp`. We're executing a command that looks like this:

```
stdin="<html><head><title>OK</title></head><body><h1>wkhtmltopdf</h1></body></html>"
echo $stdin | /home/wmn/code/talentoday/talentoday/bin/wkhtmltoimage-amd64 --height 900 --width 960 --quality 60 --format png - -
```

This will convert the HTML to an image correctly, but it will leave the html file lying in `/tmp/wktemp-a7318d30-6c2d-4e16-8e2d-7b5c0404456d.html`

I suspect that the HTML file is being created [here](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/7058a0405ca3b2747e10113b2891016197bc2e1a/src/lib/multipageloader.cc#L582-L602) but I might be wrong as I did not dig too deep.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
