### ISSUE TITLE
Page Numbers are incorrect

### ISSUE THREAD

**Issue by ulugbekov** [wkhtmltopdf/wkhtmltopdf#2038]
Hi, 

I have 10 cover pages, 1 table content, 14 real page content.
Table content's starting page is 2. (I think it should be 1).
Page Footer:
1) Table content's footer is (11 of 16)
2) Real page content footer (first page starts from 12 of 16 )
3) Last page ends with ( 25 of 16 )

wkhtmltopdf  --footer-line -B 10mm --print-media-type --footer-center "Page [page] of [toPage]"   cover  api.html   --footer-center "Page [page] of [toPage]" toc url.html book.pdf

What is wrong with this code?
Thanks

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by chourie2** [comment]
I wasn't able to find time to reproduce this issue on 0.12.5.

But I encounter a similar issue on 0.12.2.4: I was force to use a --page-offset -1 on the cover object to ensure that the page number are correct (with a cover object that actually generate 1 page). But that fix doesn't work for cover that take more than one page (kind of odd but who knows), and it seems that we can't set a greater negative page-offset.

I also notice when trying to fix this issue that the option --exclude-from-outline doesn't seem to work on a cover object : I only get the man page instead of the actual work being done. Might be related ?

In my case we use a html file for the footer instead of the footer-xxx options. We also use an adapted version of the suggered function subst in [here](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt). I'm not sure for now if that's not alterating the issue I've got.

I think there are more than one subject behind this issue: 
* Should wkhtmltopdf fully handle a cover object with multiple page ?
* Should wkhtmltopdf start counting page at the cover object or at the first non cover object (toc, or page) ? Or should it allow the user to change that behavior with an option ? (might be usefull with something is done in the issue #3910)
* Does the include-from-outline and exclude-from-outline on the first or the last object impact or should the number of the page / or the total number of the page (example: if someone exclude the cover for exemple, it might have some sense to not count the page within it) ?

Potential workaround for you @ulugbekov : you can add a page object before the toc object, instead of a cover object. Your page number will be good, but you'll also have a footer and a header on theses 10 page, which might be what you're trying to avoid here I guess !

**Comment by smuglet** [comment]
Is it possible to re-open this issue?  I experience it consistently when using a cover that is two pages.  I immediately get the 10/9 on the page counter.  Like the total pages forgot to count the second page of the cover.
