### ISSUE TITLE
CSS flex-box support doesn't exist?

### ISSUE THREAD

**Issue by rainabba** [wkhtmltopdf/wkhtmltopdf#2100]
I've included a s screenshot to clarify the expected vs actual behavior. It seems that display:flex isn't supported at all. I've tested with 12.2 and 12.1.

Here is a fiddle with source: http://jsfiddle.net/z2caddkd/

![flextest](https://cloud.githubusercontent.com/assets/553630/5403291/ef9025d2-8148-11e4-8e59-b007791adbc4.PNG)

**Comment by srlakhotia** [comment]
Any updates here?

**Comment by ashkulz** [comment]
Try the 0.13 alpha builds.

**Comment by srlakhotia** [comment]
Hi @ashkulz , 
Thanks for quick response.
I am using 0.12.2.1 (with patched qt) version. Is there any chance if I can get over this issue without changing the version, or I really need to go up for 0.13 builds?
Just want to make sure if that's possible, because I really do not want to get in some surprises by changing the version of it.

Thanks

**Comment by ashkulz** [comment]
Nope. 0.13 is lacking the patched Qt but has an updated browsing engine. Things may break, it's an alpha release after all.

**Comment by srlakhotia** [comment]
Thanks @ashkulz

**Comment by muchweb** [comment]
+1 for browser upgrade
