### ISSUE TITLE
localhost is accessed through the proxy

### ISSUE THREAD

**Issue by nickrussler** [wkhtmltopdf/wkhtmltopdf#2130]
It seems that localhost is accessed through the proxy, when one is specified.

Thank you very much for this awesome tool btw. :+1:

**Comment by ashkulz** [comment]
Duplicate of #1565, a patch is needed to implement this behavior.

**Comment by ashkulz** [comment]
A patch regarding this has been merged and should be available in the next release (0.12.3).

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
