### ISSUE TITLE
Provide persistent download urls for specific versions

### ISSUE THREAD

**Issue by Yogu** [wkhtmltopdf/wkhtmltopdf#2158]
The current deployment strategy of wkhtmltopdf seems to be to publish the new version to the root directory on sourceforge and move the previously latest version to the `archive` directory. This means that the link to the latest version can not be relied on because it will produce a 404 error as soon as the next release is published.

This is problematic for a setup like ours where we automatically install a tested version of wkhtmltopdf on the server. We could now either do some magic of trying two download urls, one without and one with the `archive` part, or just never use the latest version, neither of which is appealing.

I'm not sure what the best solution is. Maybe you could publish the most recent version both in the root directory and in the `archive`, so that the persistent archive url is available as sonn as a release is published.

I hope you consider this issue.

**Comment by ashkulz** [comment]
@Yogu: is this for CI or for actual deployment on servers? If it is for actual deployment, I'd recommend that you setup a cache at your end and install from there. If it is for CI, it is good that it breaks ... you know a new version has been published. If you can't test/update it, you can just update the URL.

I'm willing to change the current release strategy, but `wkhtmltopdf` is improving with each release and I cannot provide support for older versions (which continue to get used even now, even though they have multiple security vulnerabilities).

**Comment by Yogu** [comment]
@ashkulz We use it for the production server as well as for the vagrant configuration of our developer's boxes. Caching would certainly be a possibility, though it would imply a significant overhead to our small chef-solo environment. Of course it's good to be informed about new software version, but I'd prefer it in a way that does not break all the developer's boxes and possibly production.

> I'm willing to change the current release strategy

That would be awesome!

> wkhtmltopdf is improving with each release and I cannot provide support for older versions

That's for sure. We don't want support for old versions, we just don't want them to be gone the minute after a new release is out.

**Comment by tmertens** [comment]
@Yogu :+1: 

This has been causing some serious pains in the past couple of weeks.

@ashkulz 

> If it is for CI, it is good that it breaks ... you know a new version has been published. If you can't test/update it, you can just update the URL.

Most organizations do not use edge versions of anything unless they have a good reason.  This is why things like RHEL and package managers exist (read: yum, apt, maven, npm, rubygems, ...), rather than simply just downloading the latest everything every time a server or piece of software is deployed.

Let us suppose that the fictional package `octo-kitty` exists and has undergone several major revisions, now at v4.5.  On installation, it downloads the required version of a separate library `awesome-cats`, let us say version 1.0.  It verifies the download against a known good hash and then installs / uses `awesome-cats` however it needs to.

`octo-kitty` releases a new major version 5.0. **Yay** its users rejoice! But many do not switch immediately because:
* They don't have an immediate need to.
* They don't have the resources
* The risk is higher than the reward of upgrading
* ... put other reasons here ...

`octo-kitty` continues to support old editions via major bug/security patches but otherwise largely focus on new versions/features.

Over time, the `awesome-cats` maintainers release versions 1.1, 1.2, 1.3. As part of each release, they not only post new binaries, but move/archive the old ones.

After each `awesome-cats` release, `octo-kitty`users say 'boo! My deploys fail because the download url is wrong! YUNOUPDATE `awesome-cats`?!! :rage1:'  So, `octo-kitty` maintainers must then release patches for _their_ app to update the binary urls for its `awesome-cats` dependencies.  They must do this for not only their current major release, but also ALL HISTORICAL VERSIONS they are still supporting if a binary that was moved was referenced there.  Furthermore, ALL users of ALL affected versions must update their `octo-kitty` dependency - not because of a bug fix in that library - but because some third-party dependency decided to move their binaries.

At this point, users and maintainers of `octo-kitty` are reasonably frustrated with having to update their dependencies when there have been in fact no changes in their requirements nor the implementation of their library itself.

Then  `awesome-cats` maintainers release version 2.0.  Oh glorious day!  Such an epic release!   Amazing new features!  So. Many. Cats!!!  _They delete their archived binaries._  Not just move ... _DELETE_.

Now, `octo-kitty` is in a bind.  Now they must not only update the URL to the binary - they must either:

1. Find copies of the historical binary version(s) they depend on, include the appropriate versions in their repository or a self-hosted mirror and release patches to all supported versions including the relevant changes.  **OR**
2. Update ALL supported versions of their library to the newly published major version of `awesome-cats` 2.0.  As a result, they find that breaking changes in `awesome-cats` 2.0 break ALL current and historical versions of `octo-kitty`.  They fix the current version but then must backport all supported versions to the new version of octo-kitty, or use approach (1) above to restore old versions to working order.  Furthermore, `awesome-cats` 2.0 forces `octo-kitty` to also implement breaking changes to their own interface.  Now not only must end user dependencies on `octo-kitty` be updated; but also their own code because the interface changed.

Furthermore, the `awesome-cats` release just broke the deploy process for all of their heroku users because their build packs can't download the binary they need anymore.  But hey! The code deploy succeeded anyways and accidentally deleted the old binary, so they can't even roll back to the previous version because the binary they need is GONE.  They should have cached it somewhere, but of course with the advent of modern packaging systems someone had made the reasonable assumption that every organization on earth need not store and distribute their own copy of every binary or library they use when they are available in publicly available and vetted sources.

Now, everyone is all :rage4: and :scream_cat: and :sob: just because `awesome-cats` maintainers moved and deleted some files from their public binary mirror. Oops?

I would propose:

1. Eliminate the `archive` directory and put a folder for each version or at least each major version in the top level directory.
2. Do not rename/move/remove directories without a very, very, very good reason.
3. If you _really_ need to remove a binary, announce it loud and clear first ahead of time with ample warning.
4. As version numbers increase, it will be obvious which folder is the most recent release; while not breaking things for people still using older versions.
5. Don't make the cats :crying_cat_face:

**Comment by ashkulz** [comment]
> We use it for the production server as well as for the vagrant configuration of our developer's boxes. Caching would certainly be a possibility, though it would imply a significant overhead to our small chef-solo environment. Of course it's good to be informed about new software version, but I'd prefer it in a way that does not break all the developer's boxes and possibly production.

@Yogu: I was under the impression that most people were using the download links from the webpage, which I kept in sync. Good to know it is being used other setups as well :smile:

Are you interested in a stable version-specific URL or just a link to the latest version would be OK? e.g. `/latest/wkhtmltopdf-linux-wheezy.deb`?

**Comment by Yogu** [comment]
> Are you interested in a stable version-specific URL or just a link to the latest version would be OK? e.g. /latest/wkhtmltopdf-linux-wheezy.deb?

@ashkulz It should be the url to a specific version, because we test our application with that specific version of wkhtmltopdf and would like to use exactly the same version on the production server.

**Comment by ashkulz** [comment]
@tmertens: I find your post condescending and offensive. What most open source projects do is just provide the source, or maybe a Windows/OS X build if they have the ability to do so. Very few provide a comprehensive set of binaries for Linux (and that too packaged for specific distributions with proper dependencies) -- especially when the project is a one-man project done in spare time, like this one is. And on top of that, you take a sarcastic tone about a scenario I didn't know about and which I honestly don't care about.

**Comment by ashkulz** [comment]
> It should be the url to a specific version, because we test our application with that specific version of wkhtmltopdf and would like to use exactly the same version on the production server.

@Yogu: I'll see if I can create a symbolic link in `archive` or make the top-level folder a symlink, but there may be [an issue](http://sourceforge.net/p/forge/site-support/6130/) -- let me try and see if it works this weekend.

**Comment by tmertens** [comment]
@ashkulz 

:smirk_cat: I was not trying to be sar:cat:stic - my point was to demonstrate the problem in an amusing and enlightening way while also highlighting the seriousness of the issue since you were clearly unaware of it based on your earlier post.  I was not trying to be offensive and apologize if you took it that way.  As far as a user story goes, I thought it was both comprehensive and rather amusing.

I fully understand that it is neither your fault nor problem that you did not realize the effect that seemingly harmless changes were having elsewhere around the globe.  That became quite obvious when those changes were made, and then changed again not long after the prior release resulting in yet another "breaking" change.  But it did have such an effect to the point that servers were broken unexpectedly, deploys delayed, and many lives lost (ok, so no lives were actually lost ... to my knowledge).

It is a token of appreciation to have your creation used in unexpected ways.  This is not unexpected given wkhtmltopdf is, to my knowledge, one of the most popular OSS pdf libraries I know of.  One just has to look at https://www.ruby-toolbox.com/categories/pdf_generation to see this - three of the top four gems rely on wkhtmltopdf.

Here is some :beers: and :cake: for your excellent work, although I do recommend consuming them separately. Beer and cake do not pair well.  Except maybe a coffee stout. Hmm... I must ponder this.

**Comment by macfanatic** [comment]
If at all possible, I would love to see a release URL that is more predictable - currently we're using a custom Heroku build pack to install the binary for our production and staging apps, and when a new version is released I have 2 options:

* Update the build back to reference the same binary as before, but at a new URL
* Update the build pack to reference the new binary, which breaks as soon as there is a new deploy in the future.

I don't like the idea of just picking up untested versions without knowing it on a deploy, but maybe having a simplified folder structure as others have suggested letting me pick what version to link to, even if it is the latest, would be awesome!

Appreciate the hard work, we can certainly make do as things are now, but just sharing how we are using this setup on our app.

**Comment by ashkulz** [comment]
You can refer to e3b1a907bb11181b3d15e666a5d5cc5d67238568 on how to get a stable download URL for any version (I wasn't able to get a symlink working). I'm planning to have a structure similar to follows:
```
0.12
    0.12.0
    0.12.1
    0.12.2
    0.12.2.1
    ... and so on ...
0.13
    0.13.0
    ... and so on ...
prerelease
   0.13.0-alpha
   0.13.0-beta
   0.12.3-dev
    ... and so on ...
```

I'll probably do the reorganization in a few weeks, after the `0.13.0-alpha` release. If you know any repository where the URL needs to be corrected, feel free to submit a PR referring to this issue or let me know, I will submit a PR myself.

**Comment by Yogu** [comment]
Thanks @ashkulz! The unique-file thing seems to work.

**Comment by ashkulz** [comment]
Please note that downloads for the 0.12 series are now hosted at gna.org. All migrated downloads will be removed from SourceForge on 11-July-2015, so if you download it via an automated script it is going to break then. Please update the URLs before that happens.
