### ISSUE TITLE
wkhtmltopdf with tiff support

### ISSUE THREAD

**Issue by evildav** [wkhtmltopdf/wkhtmltopdf#2308]
Are there any plans in future to release wkhtmltopdf binaries with default tiff support? 

We discussed earlier about compiling from the source code with libtiff support. But I faced a lot of dependency failures when doing so and I scrapped the whole thing.

**Comment by ashkulz** [comment]
Please continue the discussion in #2089 instead of a new issue. For `0.12.x`, there is no such plan (or any development in general) scheduled to happen. For Qt5, TIFF support has moved to qtimageformats and uses bundled codecs which could be a [security risk](http://doc.qt.io/qt-5/qtimageformats-index.html#security-considerations) i.e. it too is unlikely to happen in the near future. There is also no way to disable support for individual image formats like it was present in Qt4 e.g. `-no-mng`.
