### ISSUE TITLE
Some bookmarks garbled

### ISSUE THREAD

**Issue by 446r** [wkhtmltopdf/wkhtmltopdf#2492]
Some bookmarks(non English characters) garbled.

U+7D0D 納 -> U+7D0A 紊
U+540D 名 -> U+540A 吊
...
....

![1](https://cloud.githubusercontent.com/assets/3156875/8949456/a92719ba-35ee-11e5-9253-e9fc7187fa73.png)

**Comment by ashkulz** [comment]
Thank you for your interest in wkhtmltopdf/wkhtmltoimage. Without a minimal, reproducible test case as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further. Please reopen this issue once you have provided the details instead of creating a new issue.

**Comment by dbzhang800** [comment]
Hi @ashkulz , the bug can be reproduced using following html file

```
    <!DOCTYPE html>
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body>
    <h1>名字</h1>
    </body>
    </html>
```

run

    wkhtmltopdf --outline t.html t.pdf

Then open the pdf with adobe reader.
