### ISSUE TITLE
Barcode is not rendered in private network

### ISSUE THREAD

**Issue by bharat-S** [wkhtmltopdf/wkhtmltopdf#2498]
Hi,
   At our on-premise private network, barcode is not rendered in pdf

Html is ::
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
"http://www.w3.org/TR/html4/loose.dtd">
<html><style type='text/css'>
	@font-face {font-family: 'IDAutomationHC39M'; src: url(data:font/truetype;charset=utf-8;base64,AAEAAAARAQAABAAQTFRTSI2KMfcAAJB......(large text)......3AAA=)format('truetype');}</style><body><div style="margin-bottom: 5px; height: 190px">
	<div style="font-size:10.8pt; z-index: 9999; position: absolute;top:26px; right:3.5%; display:block">
		<font id="barcodeDataValue" face="IDAutomationHC39M">*ABC1000001222*</font>
	</div>	
</div><body><html>

**Comment by ajit-prax** [comment]
+ 1

**Comment by ajit-prax** [comment]
Having the same issue

**Comment by ashkulz** [comment]
Thank you for taking the time to report an issue for wkhtmltopdf/wkhtmltoimage. Unfortunately, without a minimal/reproducible test case and environment/command line details as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further. Please reopen this issue once you have provided the details instead of creating a new issue.
