### ISSUE TITLE
Variable "topage" is 3 and my pdf has only 2 pages

### ISSUE THREAD

**Issue by tcheymol** [wkhtmltopdf/wkhtmltopdf#2506]
Hello, I have the following issue.
Sometimes, when the body reaches the footer, the variable "topage" is one higher that the actual number of pages in my pdf. Then, the the pdf has only 2 pages and the last page is numbered 2/3. As my last footer is different from the others, I got the wrong footer on this page.
Did someone faced the same issue ?
ps : I use nodejs and use Wkhtmltopdf with js call.

Thank you all

**Comment by ashkulz** [comment]
Unfortunately, without a minimal/reproducible test case and environment/command line details as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further. Please reopen this issue once you have provided the details instead of creating a new issue.

**Comment by seanthebean** [comment]
Duplicate of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1771
