### ISSUE TITLE
Base64-encoded Background Image Does Not Render

### ISSUE THREAD

**Issue by smnsc** [wkhtmltopdf/wkhtmltopdf#2552]
I have a DIV element that uses inline-CSS to have a background image.

For some reason, wkhtmltoimage is unable to render this and uses the default inherited styles from the external CSS file.

Regular web browsers render this just fine.

Here is a shortened version of the markup below:

```
<div style="background: url(data:image/png;base64,{BASE-64-DATA}) 50% 50% / 100% no-repeat;"></div>
```

Test platform:
- Mac OS X 10.10
- wkhtmltopdf 12.2.1

**Comment by Sef1995** [comment]
I've got the same problem!

**Comment by real21c** [comment]
I solved it.

1) Save {base64 content} as a file.
2) Load the file path with the <img tag or background style's url.

**Comment by PhilterPaper** [comment]
The whole point is that the OP apparently wants the image content _in line_, rather than as a separate _file_. I'm a bit confused over the statement "is unable to render this and uses the default inherited styles from the external CSS file". Does that mean that the image is not being rendered at all, or the image shows up but is not obeying the in-line CSS? If the image doesn't show up at all, or does but is mangled, I can't see how you can say it's not doing the CSS properly. You would need to get the image displayed first, and then worry about CSS.

If this works OK in browsers, I would first try separating the background into background-image and other background-* properties. Maybe wkHTMLto* is having problems with the combined background settings. That might at least give a clue with where the problem lies. You might also try giving an **id** to the `<div>` and defining a proper `<style>` for it in the `<head>`. That might give more clues. It's always possible, too, that the browsers you tried are more lenient abut malformed tags and attributes, and are passing (if not quite properly handling) this in-line image, while wkHTMLto* is stricter about it.

**Comment by Tomsgu** [comment]
Closing as there is no feedback since 2016.

**Comment by RichardLindhout** [comment]
Still does not work on MacOS Catalana

**Comment by RichardLindhout** [comment]
```html
<div  style="width:256px;height:256px;border:2px solid #000;background-image:url('{{ .QRCodeImageURL }}');">
	</div>
```
Also don't works in img tag, (Chrome does render it btw)
```html
<img id="qr-code" src="{{ .QRCodeImageURL }}" width="256" height="256"/>
```

QrCodeImageURL is like this ```data:image/png;base64,_________BASE64STRING_________=```

**Comment by RichardLindhout** [comment]
Looks like it's my qr code package since it's rendering other base64 images (also png) fine

**Comment by RichardLindhout** [comment]
It was the golang html/template which encoded the data url in a different way than expected (XSS security I think)
So I switched it for text/template which works perfectly!

**Comment by Xoma163** [comment]
> It was the golang html/template which encoded the data url in a different way than expected (XSS security I think)
> So I switched it for text/template which works perfectly!

Not quite sure what you did, can you explain please?
