### ISSUE TITLE
Wrong Japanese/Chinese word is converted in bookmarks.

### ISSUE THREAD

**Issue by jimxie2012** [wkhtmltopdf/wkhtmltopdf#2582]
Dears,
I found a bug of bookmarks convert (The word “不” will be converted to “上”).
Reproduce steps:
1:  Create test.html as :

```
   <html><head><meta charset="utf-8"></head>
        <h1>不</h1>
   </html>
```

2:  Run script:
     ./wkhtmltopdf --outline ./test.html ./test.pdf

3:  test.pdf was generated with wrong bookmarks “上”.

![pdf](https://cloud.githubusercontent.com/assets/14324798/9925382/747a1aca-5d3d-11e5-87b7-803205dcc733.png)

My PDF reader is Adobe Reader.

So far, The only word (“不” ) I found is converted error, others are converted successfully.

I will be very appreciated for any help!

Great thanks!

Jim

**Comment by jimxie2012** [comment]
Hi  Ashkulz,
   
    Can you reproduce this issue or has some plans ?  thanks!

Jim

**Comment by painyeph** [comment]
I also encountered this issue, where “名” was converted to “吊”, and “服” is converted to “朊”.

不 (U+4e0d) -> 上 (U+4e0a)
名 (U+540d) -> 吊 (U+540a)
服 (U+670d) -> 朊 (U+670a)

So it happens when a unicode character ends with "0d" and then replaced with "0a".

I guess it is related to newline character conversion.

**Comment by shaofuzhang** [comment]
Problems with adobe readers. Not using this problem with other readers

**Comment by PhilterPaper** [comment]
See #3841 for same problem and possible fix.

**Comment by Tomsgu** [comment]
Closing in expense of #3841
