### ISSUE TITLE
Limit page count.

### ISSUE THREAD

**Issue by imemohit** [wkhtmltopdf/wkhtmltopdf#2637]
I want to limit the page count of the PDF to print just one page.
Checked the reference manual couldn't find it. Is there any feature do that?

**Comment by PhilterPaper** [comment]
Are you asking to *create* just one page (out of multiple pages), or *print* one page in a PDF viewer? I'm not sure much will be gained in creating just one page, as (at least) all the pages before the desired one will have to be created and then discarded. There are plenty of tools out there to *extract* selected pages out of a PDF file, and of course, any PDF viewer will permit printing of selected pages. Would one of those fulfill your needs?

**Comment by imemohit** [comment]
I am asking to create just one page (out of multiple pages). The thing is the second page is coming up to be an empty long page. The actual content is just on one page, but the second page is completely empty.

**Comment by PhilterPaper** [comment]
I think I've seen that kind of thing before, and the fix is probably in WebKit (meaning... "who knows when?"). I would suggest either just explicitly printing only the first page, or if that's a nuisance to keep doing that (page is to be printed many times), to use a utility to extract just the first page.

**Comment by imemohit** [comment]
I just used a static height in my content to fix it. Thanks!
