### ISSUE TITLE
https image support

### ISSUE THREAD

**Issue by mohdmohsin** [wkhtmltopdf/wkhtmltopdf#2648]
Https Images are not working in wkhtmltopdf conversion. Please find below the image URL and command. Kindly help me on this issue.

COMMAND: 

wkhtmltopdf D:/input.html D:/output.pdf

image: https://media.asicdn.com/images/jpgo/20900000/20901191.jpg

**Comment by kengruven** [comment]
HTTPS images work fine for me.  Could it be something else?

With more information, this issue is going to be impossible to track down.

**Comment by PhilterPaper** [comment]
Does the exact same HTML code for displaying an image work OK with an `http:` URL? If `https:` is the *only* difference, that sounds like a WebKit bug. Is the page in question under SSL (https) or not? With browsers, I've seen problems (security issues reported) when trying to display non-SSL (http) images etc. on an SSL (https) page, but I don't recall if I've seen any problems doing the reverse. If the entire page is https, and on the same domain as the image, you could just give the absolute or relative *path* to the image, rather than the full URL. That certainly works in HTML, but who knows if WebKit will accept it. Anyway, something to try if you can.

**Comment by kopertop** [comment]
I've been hitting this issue too, so I'm guessing it's not fixed. The problem appears to be on sites that are not SSL, but have images that are, and only for certain images. In my example, images from *googleusercontent.com* work, while images from *2.bp.blogspot.com* don't.

Example:

```
wkhtmltopdf --javascript-delay 30000 http://blog.coredumped.org/2016/08/converting-old-mac-pro-into-lockable.html images.pdf
```

Results in:

```
Loading pages (1/6)
Warning: SSL error ignored                                        
Warning: SSL error ignored                                        
Warning: SSL error ignored                                        
Warning: SSL error ignored
Warning: SSL error ignored                                         
Warning: SSL error ignored                                        
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored                                        
Warning: SSL error ignored
....
```
 After everything is done, the PDF is available, but without most of the images.

**Comment by Tomsgu** [comment]
This was fixed. Please upgrade to the newest version.
