### ISSUE TITLE
How to set timeout?

### ISSUE THREAD

**Issue by Dingo64** [wkhtmltopdf/wkhtmltopdf#2671]
I've just found wkhtmltopdf on my linux machine was working for the last 28 minutes eating 99% of CPU and effectively killing the server. Can I set some kind of timeout so it it can't create a PDF within 30 seconds it dies?

**Comment by bgadoury** [comment]
You'd have to do that outside of wkhtmltopdf.

**Comment by Tomsgu** [comment]
Closing as the answer was provided.

**Comment by optyler** [comment]
Is something like this viable ?

```bash
xvfb-run -a -s "-screen 0 640x480x16" \
    timeout --preserve-status 40 -k 60 \
    wkhtmltopdf http://www.qwamci.com/ /tmp/qwam.pdf
```

**Comment by diegobill** [comment]
@optyler , this timeout solution is not working in python: https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server

**Comment by optyler** [comment]
Well, as the OP did not ask specificaly about a python issue, I was not answering for that kind of situation, I tried to answer with linux tools only because I have the same kind of situation here...

I think it is out of scope for this repo to answer here but : 
Maybe you could ask directly in the [python-pdfkit](https://github.com/JazzCore/python-pdfkit.git) repository for what you need because, to me and I am not a python expert, it could be done with Python directly. 

As you could see in the [source code](https://github.com/JazzCore/python-pdfkit/blob/master/pdfkit/configuration.py#L25-L29), they use a `subprocess.Popen().communicate()` method to call `wkhtmltopdf`, and the `communicate()` method could be called with a `timeout` value per the [python documentation](https://docs.python.org/fr/3.6/library/subprocess.html#subprocess.Popen.communicate)

I see that you already forked the lib, you could maybe try it yourself :)

( btw, Downvoting because it is not answering your own issue / situation with your specific config is a bit mean ^_^ )
