### ISSUE TITLE
Weird character when using hex unicode character

### ISSUE THREAD

**Issue by borkdude** [wkhtmltopdf/wkhtmltopdf#2685]
See http://stackoverflow.com/questions/33901625/smiley-emoticon-showed-as-weird-character-in-pdf-made-with-wkhtmltopdf?stw=2

**Comment by PhilterPaper** [comment]
Since it works when you specify the character differently, I'd chalk it up to WebKit (the core of wkHTMLtoPDF) not handling exotic Unicode characters (yet). For the time being, it looks like you'll have to modify the HTML to use acceptable character codes instead of this emoticon trash (sorry, I despise emoticons and emojis... another sign of the dumbing down of society and the coming Apocalypse :( ).

By the way, please post at least an abstract of the problem on this group, rather than just a link to another group (e.g., StackOverflow). It's OK to leave details to the older post, but at least tell us something about the problem here.

**Comment by Tomsgu** [comment]
Please continue here http://stackoverflow.com/questions/33901625/smiley-emoticon-showed-as-weird-character-in-pdf-made-with-wkhtmltopdf?stw=2
