### ISSUE TITLE
cannot install wkhtmltopdf on ubutnu 8.08

### ISSUE THREAD

**Issue by tdelob** [wkhtmltopdf/wkhtmltopdf#2696]
Hello,

I am trying to install wkhtmltopdf on a old version of ubuntu 8.04, I need this packet immediateley but I cannot upgarde the version of ubuntu right now.
I have downloaded the sources code.
Then I have used the tar -xvf ....
I have copied the directory wkhtmltox-0.12.2.1  into /usr/bin/wkhtmltopdf
Then I have restarted the server but after restart the command  wkhtmltopdf or  wkhtmltox  is not recognized :+1: 

root@Aphrodite:/usr/bin#  wkhtmltox
-bash: wkhtmltox: command not found
root@Aphrodite:/usr/bin#  wkhtmltopdf
-bash: wkhtmltopdf: command not found

Is there something I missing in my installation ?

With best regards,

**Comment by PhilterPaper** [comment]
Is /usr/bin/wkhtmltopdf/ in your search path? Is that where the executables ended up? Do you need to manually update the path?

**Comment by tdelob** [comment]
hello,

The following is the content of my :/usr/bin/wkhtmltopdf :
root@Aphrodite:/usr/bin/wkhtmltopdf# ls
AUTHORS        common.pri  examples    qt         src              wkhtmltopdf.qrc
CHANGELOG.md   COPYING     include     README.md  VERSION          wkhtmltox.nsi
CHANGELOG-OLD  Doxyfile    INSTALL.md  scripts    wkhtmltopdf.pro

How to put in my search path ?
Do I need to execute a file ?

With best regards

**Comment by PhilterPaper** [comment]
It's been a long time since I played with Ubuntu from 2008, but there should be some sort of "profile" file that can be used for (among other things) to append to $path or whatever it's called. Do a little googling on Linux/Ubuntu/path/profile and see what you find. There is probably some sort of common profile for all users, and then each user has their own profile to customize. I don't think there is an "add this directory to the path" command as such -- you have to customize a profile.

Adding directories to the command search path is probably the most basic thing a system administrator ever does. You really ought to know how to do this if you're going to running a Ubuntu (or other Linux) system!

**Comment by tdelob** [comment]
Ok PhilterPaper thanks for this information
 I have found where the path are defined in /etc/environement :

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"

my directory called wkhtmltopdf is in usr/local/sbin 

the rights are correctly set, I have restarted the server but the command wkhtmltopdf still does not work.

The following is the content of my directory ;

-rwxrwxrwx 1 root root  1489 2015-11-30 21:10 AUTHORS
-rwxrwxrwx 1 root root  5300 2015-11-30 21:10 CHANGELOG.md
-rwxrwxrwx 1 root root  9397 2015-11-30 21:10 CHANGELOG-OLD
-rwxrwxrwx 1 root root  1468 2015-11-30 21:10 common.pri
-rwxrwxrwx 1 root root  7651 2015-11-30 21:10 COPYING
-rwxrwxrwx 1 root root 63632 2015-11-30 21:10 Doxyfile
drwxrwxrwx 2 root root  4096 2015-11-30 21:10 examples
drwxrwxrwx 3 root root  4096 2015-11-30 21:10 include
-rwxrwxrwx 1 root root  7606 2015-11-30 21:10 INSTALL.md
drwxrwxrwx 9 root root  4096 2015-11-30 21:10 qt
-rwxrwxrwx 1 root root   336 2015-11-30 21:10 README.md
drwxrwxrwx 2 root root  4096 2015-11-30 21:10 scripts
drwxrwxrwx 6 root root  4096 2015-11-30 21:10 src
-rwxrwxrwx 1 root root     8 2015-11-30 21:10 VERSION
-rwxrwxrwx 1 root root   802 2015-11-30 21:10 wkhtmltopdf.pro
-rwxrwxrwx 1 root root   120 2015-11-30 21:10 wkhtmltopdf.qrc
-rwxrwxrwx 1 root root  4518 2015-11-30 21:10 wkhtmltox.nsi


IS there anything else to do for that to work ?

With best regards

**Comment by PhilterPaper** [comment]
Did you *build* the executable somewhere? Then you have two choices: 1) make a soft link (ln -s) from the directory where you've built the executable to one of the directories already *in* $PATH, such as /usr/sbin/, OR 2) add the directory that the executable is in to $PATH, e.g., **$PATH = $PATH . ":/usr/local/sbin/wkhhtmltopdf"**. Actually, there's a third choice: always fully specify the directory the executable is in: /usr/local/sbin/wkhtmltopdf/wkhtmltopdf...

**Comment by tdelob** [comment]
Hello,

I did not build the executable yet.
Are those the executables :

root@Aphrodite:/usr/local/sbin/wkhtmltopdf/scripts# ls
build.py  release.py  sync-headers.sh

Do I need to make a link to headers.sh ?

**Comment by PhilterPaper** [comment]
Those are *not* the "executables" I was talking about. They are things like "wkhtmltopdf" or "wkhtmltopdf.exe" (whatever name they use for Linux) that are built during the install process. They are what are actually *run* when you're using wkHTMLtoPDF. The *.py and *.sh files appear to be build and maintenance tools, but I don't know if they're used in building wkHTMLtoPDF. Usually that's done with a "makefile", but I'm not familiar with this product's Linux build process.

I fear that you know so little about installing, building, and running software on Ubuntu that you are going to have a ton of trouble trying to get this going. See if there is a local Open Source or Linux or even Ubuntu interest group, where someone could watch over your shoulder and guide you. Otherwise you're going to be learning by a very long process of trial and error.

**Comment by tdelob** [comment]
hello,
yes I am not a expert in Linux I am an windows administartor, but I have already manage to install new servers on ubuntu, install and configure a lot of application like apache, ruby, redmine.... I am new with linux and not use to make installation from binaries has the command apt-get install works on recents distributions, this is the first time I have to install an application with the method.
But thanks for your helpfull help !!
