### ISSUE TITLE
"?" in URL creates error

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#2748]
I have links like: aaa.com/render?page=home

when trying to execute: wkhtmltoimage --load-error-handling ignore http://aaa.com/render?page=home
i get errors like below even though I have no iframes:

Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.

Can anyone help please ?

Best
-Mel

**Comment by PhilterPaper** [comment]
Perhaps your operating system (command line processor) is treating ? as a special character (e.g., a wildcard). Try enclosing the whole http: address portion in " and see if that helps.

**Comment by Melify** [comment]
Thanks

-n 
Did the job



-Mel

646.303.1234

**Comment by ArtemZag** [comment]
I have similar issue. But "?" symbol is used inside of css class. 
Like this:
`background: url('my/picture.png?longhashgeneratedbywebpack')
So, I cannot just wrap it with quotes. Any ideas/recommendations?

**Comment by PhilterPaper** [comment]
Without **http://domain/**, is it actually running picture.png to generate an image? What kind of error are you getting? Maybe on a browser, the UQS is being ignored by the server (since.png is not normally executable), but with WebKit it's attempting to process it somehow? If this is being used inside of CSS, I doubt it's the same issue as a ? on the command line. Can you get rid of the ?longhash bit, and it works? Is the problem actually that my/ is not a subdirectory under your current directory, and thus it's not finding the image at all? Under what cases does this CSS work? Is it exactly the same code as works on a browser?

**Comment by ArtemZag** [comment]
I don't get an error.
Just a warning:
`Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.`

> Can you get rid of the ?longhash bit, and it works? 
My fault. Actually it's not related to "?" symbol. I get this warning always when I have background: url... in my css file.

**Comment by PhilterPaper** [comment]
And is the directory with the image ("my/" in your example) a child of the directory you're running this in? If not, it probably won't find the file.

**Comment by ArtemZag** [comment]
Physically the file is there. If I open my html page using chrome or any other browser then I see it. 

I tried also to install QtWebkit and to open my html file using its internal browser. It doesn't display the image. So, looks like it is not related to wkhtmltopdf but it's how QtWebkit renders the page.

**Comment by Tomsgu** [comment]
Closing as it has been resolved.
