### ISSUE TITLE
Exception in Wkhtml2pdf.php line 885:

### ISSUE THREAD

**Issue by rahulhimm** [wkhtmltopdf/wkhtmltopdf#2896]
i am using wkhtml to but the error is System error <pre>/var/www/html/VHRM/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64: 1: /var/www/html/VHRM/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64: Syntax error: word unexpected (expecting ")")
</pre>

**Comment by luzfcb** [comment]
@rahulhimm since this project does not provide any interface with PHP, probably you should report this error here: https://github.com/NitMedia/wkhtml2pdf

said that, provide the exact HTML code that causes the error and better describe what steps you took to this problem to occur also be quite useful to help find a solution.
