### ISSUE TITLE
Can't fetch data from Google.

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#2904]
Hi All,

I have try to convert url like this [https://www.google.co.in/#q=wikipedia+search](url) . But it gives empty pdf output. I have used wkhtmltopdf 12.2.4 in windows8. If u have any concern let me know.

Thanks,
Viswa.

**Comment by PhilterPaper** [comment]
No _concerns_, but I do have several _questions_. Your link (to github.com) gives me a 404. What exactly is the URL you're trying to convert? Does it display correctly in several browsers? What is the command line you use in Windows to do the conversion?

**Comment by viswa18** [comment]
Thanks for your reply. Please use this link [https://www.google.co.in/#q=wikipedia] . In browsers this link works correctly. 
I have used below command for the conversion.
C:\Program Files\wkhtmltopdf\bin>wkhtmltopdf.exe https://www.google.co.in/#q=wikipedia GoogleSearch.pdf

**Comment by PhilterPaper** [comment]
Be sure to put " around the C:\Program Files... command (contains a space). You may also need them around the https:... parameter, if it contains characters such as _?_. On my 0.12.2.4, it hangs up at the first 10% of Loading Pages, so I don't seem to be getting as far as you. By the way, you may have some hidden characters in the command you gave -- I had to type mine in manually instead of copy and pasting.

**Comment by viswa18** [comment]
For this url It gives empty PDF output. At same comment I have use some other link it works fine

**Comment by PhilterPaper** [comment]
If using *exactly* the same command line syntax works for other sites, that would prove that there's something in this particular site that wkHTMLtoPDF chokes on. I ran it through validator.w3.org, which reported all sorts of problems with conflicting character encodings and a bunch of obsolete markup. Maybe that could explain it. Just for giggles, you might try using a *copy* of that page (as local files), and start cleaning up the HTML markup (that the validator complains about) until you find the offending markup. Then it can be discussed whether WebKit should reasonably handle such a case (since many browsers can).

**Comment by viswa18** [comment]
I have save the url (https://www.google.co.in/#q=wiki+search) to local file. Then it converts to pdf. now output was fine. But while giving the url as input but it did not work.
I don't know whats problem in the url. Why it did not work while giving this url?

**Comment by PhilterPaper** [comment]
Well, the only other thing I can think of at the moment is that using **#** to delineate the URL Query String, rather than **?**, is a bit unusual, and might be confusing WebKit. Normally, **#** is used for target addresses, not the UQS. Is **#** used on other sites, and if so, does it work or fail with wkHTMLtoPDF?

I tried your URL with ? instead of #, and the Google site changed it to #. I'll have to read up on this, but if anyone knows more about it, please chime in.

**Comment by antonellopasella** [comment]
Please disable javascript and open your link (https://www.google.co.in/#q=wiki+search).
You'll will see a blank page like the one generated by wkhtmltopdf

**Comment by PhilterPaper** [comment]
If I disable JS (Firefox), I get the Google India home page (rather than the search results, or a blank page). If I give a URL with ? replacing # (with JS off), it is _not_ changed back to #, and I get the home page again. Apparently, Javascript is involved with this whole thing, and my guess would be that WebKit is not handling it as desired. Can someone find a WebKit-based browser and try it out?

**Comment by viswa18** [comment]
I have checked in chrome browser. Im also get home page. Not a blank page.

**Comment by antonellopasella** [comment]
My "Blank" means "without results".
Because search is triggered client side by javascript.

Can you confirm?

Il lunedì 2 maggio 2016, viswa18 <notifications@github.com> ha scritto:

> I have checked in chrome browser. Im also get home page. Not a blank page.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2904#issuecomment-216118862>
>


-- 
Antonello Pasella http://www.pasella.it

**Comment by viswa18** [comment]
Yes, In chrome It gives output without results. It gives google page. Search was not triggered if we disable java script.

**Comment by viswa18** [comment]
Any update On this..

**Comment by viswa18** [comment]
When it will be get resolved??

**Comment by antonellopasella** [comment]
I don't think is wkhtmltopdf related.

You need to save as PDF after some javascript execution (AJAX requests and so on) but it out of wkhtmlcontrol

For this kind of requests you can use phantomjs or nightmarejs as well
