### ISSUE TITLE
PHP exec() url with parameters

### ISSUE THREAD

**Issue by sorinbuda** [wkhtmltopdf/wkhtmltopdf#2909]
Can't make it work

exec(C:\folder\wkhtmltoimage.exe "http://localhost/webpage.php?p1=276&p2=325" C:\test\1.png);

also tried with no luck
exec('C:\folder\wkhtmltoimage.exe "http://localhost/webpage.php?p1=276&p2=325" C:\test\1.png');
exec(cmd.exe /c C:\folder\wkhtmltoimage.exe "http://localhost/webpage.php?p1=276&p2=325" C:\test\1.png);
exec('cmd.exe /c C:\folder\wkhtmltoimage.exe "http://localhost/webpage.php?p1=276&p2=325" C:\test\1.png');

despite the following works excellent
exec(C:\folder\wkhtmltoimage.exe http://www.google.com C:\test\1.png);

The first one works also well from Command Prompt.
Any ideas?
kind regards,
Sorin

PS: I Am using IIS 7 with PHP 5.6 and WK2Tools 0.12.3.2-win64

**Comment by rw3iss** [comment]
Same issue for me. Nothing from localhost works, however the page is dead simple, just a local CSS file, no JS, no images, plain text. :(

**Comment by PhilterPaper** [comment]
For starters, exec() expects a single _string_ for the entire command (see http://php.net/manual/en/function.exec.php). Then, any \ should be doubled because \ is an escape character. Any " or ' within the string should be escaped. I'm a bit surprised that sometimes it works without following these rules.

If that doesn't do it, perhaps "localhost" is just a little bit _odd_ for your PHP, and it isn't going to the right place (as with a regular domain name). Since this is a local file, why not just give the direct file path rather than http: and localhost?

**Comment by rw3iss** [comment]
Well, the command works just fine in one case with the same exact
parameters but with a non-localhost url. But with localhost, I am escaping
the \'s, and it is a single string, ie:


$filePath = 'C:\\wtserver\\tmp\\order_' . $orderId . '.pdf';
                $scriptCmd = 'wkhtmltopdf
http://localhost:8082/service/viewOrderPDF/' . $orderId . ' ' . $filePath .
' > C:\tmp\out_error.txt 2> C:\tmp\out.txt';
exec($scriptCmd);

And the url I'm trying to use (viewOrderPDF) is a route within a
codeigniter-like PHP solution, and the page requires the rest of the
framework to retrieve data before it creates the html output that
wkhtmltopdf will convert to a PDF.

**Comment by PhilterPaper** [comment]
Any improvement when you complete the escaping:

    ' > C:\\tmp\\out_error.txt 2> C:\\tmp\\out.txt';

**Comment by rw3iss** [comment]
Ah, thank you. It is still hanging :(

**Comment by PhilterPaper** [comment]
All I can suggest at this stage is that you make a test .exe program to see if the command and its parameters are being passed correctly by exec(). This would tell you whether you've got all the escaping done right and needed quotes (' or ") are where they're needed (and properly escaped, if nested). You might even be able to do it with a Perl program or a shell script of some sort, rather than compiling an .exe file. 

If everything is being passed correctly to your test (and thus likely also to wkHTMLtoPDF), and http calls to localhost work fine, then I'm out of ideas for now.

**Comment by bmros** [comment]
I had the same issue and here a possible **explanation and solution**.
When the app (let say the php script containing the _exec()_ call) runs on the **PHP built-in server** for example, it runs on one single-threaded process. From this script you can't request and thus serve localhost since the process is already working for your script (one thread!). The solution here is to use a full-featured web server. I tested with **Apache** and everything works fine on a same domain (localhost). If Apache is not a solution, it is still possible to put the script (php) and the html file that you want to _pdfify_ on a different server.
Hope this could help someone.

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please feel free to re-open the issue if it's not resolved for you.
