### ISSUE TITLE
HTML in the picture did not produce pdf

### ISSUE THREAD

**Issue by wangrui00** [wkhtmltopdf/wkhtmltopdf#2931]
I am running under windows;
wkhtmltopdf 0.12.2.4
Using the command:
wkhtmltopdf allow-local-file-access -s A4 -q {$file_path_prefix}.{$ext} {$file_path_prefix}.pdf
But, HTML in the picture did not produce pdf.

**Comment by PhilterPaper** [comment]
"HTML in the picture" means what? Are you talking about the source HTML, and it failed to produce a PDF? Did you get *any* error messages? Was an output file produced? If so, was it completely empty, or did it contain no useful material? Or did you get most of your document, but it was missing certain parts, such as images?

If this HTML produced output when given a URL, check if it is specifying URLs, absolute paths, or relative paths to content (such as images). URLs and absolute paths (starting with /) can cause problems with wkHTMLtoPDF looking in the wrong place (/ as absolute filesystem origin, rather than as HTML origin). Relative paths can cause problems if resources such as images are not in the correct place relative to where wkHTMLtoPDF is running.

**Comment by wangrui00** [comment]
Thinks

**Comment by wangrui00** [comment]
but,website can't use absolute paths.

**Comment by ashkulz** [comment]
Please post a minimal, reproducible testcase to investigate the issue.
