### ISSUE TITLE
QPainter::begin(): Returned false Error: Unable to write to destination

### ISSUE THREAD

**Issue by mazba** [wkhtmltopdf/wkhtmltopdf#2934]
When I run the executable wkhtmltopdf(linux) i got the error.
[stdout] => 
[stderr] => Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[==============================>                             ] 50%
[============================================================] 100%
QPainter::begin(): Returned false
Error: Unable to write to destination                              
Exit with code 1, due to unknown error.

**Comment by ashkulz** [comment]
You probably specified a filename which it is unable to write the output.

**Comment by mazba** [comment]
i am used "/usr/bin/wkhtmltopdf --encoding 'UTF-8' - -". for _proc_open_ in PHP.

**Comment by miccarr** [comment]
same problem with stdout

**Comment by cgaete** [comment]
Same error:
Loading pages (1/6) 
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination
Exit with code 1, due to unknown error.

use x64 on Windows 10

**Comment by Nagendra217** [comment]
Any Solution for this?
wkhtmltopdf reported an error:
Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[============>                                               ] 20%
[===================>                                        ] 33%
[==============================>                             ] 50%
[============================================================] 100%
QPainter::begin(): Returned false
Error: Unable to write to destination                              
Exit with code 1, due to unknown error.

**Comment by cgaete** [comment]
> You probably specified a filename which it is unable to write the output.

Especificar la salida del archivo .pdf e.g. /home/user/Desktop/out.pdf

**Comment by StefanTheiner** [comment]
**Make sure the target directory exists.**

I got the same exact same error output as @Nagendra217.
In my case it could be solved by ensuring that the target directory exists.
Beforehand I had deleted the subdirectory where the pdf should be written. The error was resolved by creating it again.

In my opinion the "QPainter::begin(): Returned false" log line distracts from the real error cause.

**Comment by carkod** [comment]
I've had this exact problem and I had it multiple times. This happens especially when you have an automated system where you don't know what kind of file names are being input. So in my case it happened with accented characters, forward slashes, especial symbols... none of these work. So before you send it to wkthtmltopdf to render PDF, make sure you replace characters.

**Comment by m93a** [comment]
I was unable to write to my home directory on Windows 10 (using the x64 version). As a walkaround I created a `C:\out` folder and added proper permissions.

**Comment by lassari** [comment]
I got the same error when running: pdfkit.from_url(current_url, filename) in a loop 

OSError: wkhtmltopdf reported an error:
Loading pages (1/6)
QPainter::begin(): Returned false
Error: Unable to write to destination                              
Exit with code 1, due to unknown error.

In my case, there was a slash in the name of the input file.  
the file name was: TCP/IP, which would mean IP is located inside TCP.

if in your case the files are meant to be in different directories: make sure the directory exists.

**Comment by mrer100** [comment]
open CMD as Administrator

**Comment by el07694** [comment]
Any advice to solve this?
