### ISSUE TITLE
Typesetting quality compared to (La)TeX

### ISSUE THREAD

**Issue by ginzel** [wkhtmltopdf/wkhtmltopdf#2951]
What is the typesetting quality compared to ([La](https://en.wikipedia.org/wiki/LaTeX))[TeX](https://en.wikipedia.org/wiki/TeX)? [Ligatures](https://en.wikipedia.org/wiki/Typographic_ligature), [Kerning](https://en.wikipedia.org/wiki/Kerning), [spacing](https://en.wikipedia.org/wiki/Sentence_spacing),…? See [The Beauty of LaTeX](http://nitens.org/taraborelli/latex).

**Comment by PhilterPaper** [comment]
At this point, LaTeX is likely to produce much higher quality typesetting than a browser-based rendering. wkHTMLtoPDF uses the WebKit engine to render the text, so whatever it can do, and the fonts in use can do (e.g., built-in kerning tables), will determine wkHTMLtoPDF's output. Quality of type has not traditionally been a strong point of HTML rendering, as most HTML display has been on relatively low resolution display screens rather than the printed page. If highest quality in the PDF is your goal, LaTeX to PDF output is probably a better bet. Keep in mind that ligatures and spacing are language-dependent: English has different rules than French or German, much less Hindi or Mandarin.

**Comment by ashkulz** [comment]
One word: **pathetic** (and I'm the maintainer). If you want perfect typesetting, HTML isn't what you want to use. On the other hand, if you want a good-enough approach which doesn't require you to learn anything new, then approaches like wkhtmltopdf takes are acceptable.

**Comment by ashkulz** [comment]
OTOH, using a much better rendering commercial engine like [Prince](http://www.princexml.com/) can give you acceptable results, but YMMV.
