### ISSUE TITLE
columns goes to out of boundary more than 8 columns

### ISSUE THREAD

**Issue by ponm** [wkhtmltopdf/wkhtmltopdf#2985]
Could you help me? columns goes to out of boundary more than 8 columns.
![out-of boundary](https://cloud.githubusercontent.com/assets/19732273/15822268/5e370968-2c12-11e6-8a2e-a7f30d451695.PNG)

**Comment by PhilterPaper** [comment]
What happens when displaying in a browser? How are your column widths defined: absolute measurements or relative (percentage)? It looks like you may be defining columns of a certain width, and running out of room after accounting for the media width, margin, padding, etc. Does everything show up if you temporarily increase your media width?

**Comment by ponm** [comment]
I want to  relative (percentage) width. i didn't increase media width. because client requirement for USA standard format.

**Comment by slawe02** [comment]
(sorry for my english)
Any solution? 
I have same problem - print from browser - OK, generated on Windows via 0.12.3.2 - OK, generated on CentOS via 0.12.3.0 - FAIL.
Set table width in %, px, pt, mm have same result - cut from right...
options: -q --encoding windows-1250 --enable-smart-shrinking --disable-external-links --margin-top 45 --margin-bottom 22 --margin-left 15 --margin-right 15

**Comment by travis5555** [comment]
any resolution or workarounds for this?

**Comment by hgxuquan** [comment]
how to solve the issue, columns goes to out of boundary

**Comment by Tomsgu** [comment]
Closing as there is no feedback and the issue seems to be resolved. Please feel free to re-open it if you think it's a still an issue.
