### ISSUE TITLE
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files

### ISSUE THREAD

**Issue by grassit** [wkhtmltopdf/wkhtmltopdf#2992]
I have 551 urls in a file called `urls`, see http://paste.ubuntu.com/17255465/.

I want to convert them into a pdf file by 

```
$ wkhtmltopdf --javascript-delay 10000 $(cat urls) all.pdf
Loading pages (1/6)
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
Aborted (core dumped)

```

But why does it fail, and is there a solution? 
Thanks.

**Comment by timlee1** [comment]
Update

The cause of the problem seems to be that there are too many urls in the input file for wkhtmltopdf to handle.

It works when I reduce the number of urls in the input file to some small number, but what is the maximum limit on the number of urls?

Also splitting the url input file into several files seems an somewhat awkward solution, because when combining the generated pdf files into one, it isn't trivial to combine their outlines/bookmarks. Is there a better solution?

Thanks.

**Comment by Tomsgu** [comment]
You can see this question https://stackoverflow.com/a/31862185/3422586. The problem is on OS side.
