### ISSUE TITLE
Bad font rendering of Montserrat

### ISSUE THREAD

**Issue by andywaite** [wkhtmltopdf/wkhtmltopdf#2999]
It looks like wkhtmltopdf has converted the font to a vector and applied some over-zealous smoothing. Look in particular at the 'p' and 'o':

![reportforglitch](https://cloud.githubusercontent.com/assets/6773151/16040071/6270145c-3225-11e6-9679-6668b766d66c.png)

Additional details on my [Stack Overflow](http://stackoverflow.com/questions/37809737/how-to-fix-bad-font-rendering-of-montserrat-in-wkhtmltopdf) question post.

**Comment by graingert** [comment]
I get a much better rendering with `npm install @typopro/dtp-montserrat`

**Comment by graingert** [comment]
![pdf-render-dtp](https://cloud.githubusercontent.com/assets/413772/17432960/e7b225b8-5af9-11e6-9acb-0e90e3034fb6.png)

**Comment by benjaminprojas** [comment]
@andywaite I am also having this issue. Did you make any progress with this?

**Comment by graingert** [comment]
@ashkulz @Jmuccigr ^ any clues?

**Comment by graingert** [comment]
@rse do you think this might be to do with the font preprocessing in TypoPro?

**Comment by benjaminprojas** [comment]
I am not using TypoPro if it makes any difference. I'm just importing directly from Google.

**Comment by graingert** [comment]
might be worth messing with https://github.com/graingert/bad-fonts-wkhtmltopdf/blob/master/index.js and trying out svg, ttf woff woff2

**Comment by bartonseo** [comment]
Any word on this? I am still having this issue.

**Comment by graingert** [comment]
@ashkulz @Jmuccigr ^ any clues?

**Comment by ezraw** [comment]
I am also seeing this issue with Google fonts. Using Muli.

**Comment by marciobera** [comment]
Guys, I found a solution that worked for me. I downloaded the Montserrat SGV version (https://google-webfonts-helper.herokuapp.com/fonts/montserrat?subsets=latin) and I'm using only this version for PDF building. I hope that it help you! (=

**Comment by xmontero** [comment]
For me, the SVG trick "improves" but not completely "solves" the problem.

My font is `font-family: 'Titillium Web'` from google fonts. I used that herokuapp trick to download the SVGs.

My orginal PDF (getting the font from google-fonts, thus in `woff2` format) was formatted like this:

![image](https://user-images.githubusercontent.com/5641621/40549216-271fd0e4-6037-11e8-92e5-1eb2d970e160.png)

As you can see, the problem is in several characters like the number `8` and the letter `o` for example.

After placing the fonts locally and just forcing the `svg` format, I get this:

![image](https://user-images.githubusercontent.com/5641621/40549291-51bed57a-6037-11e8-8b11-fdedb16efa01.png)

This clearly improves the `o`.

Instead if we look at a closer zoom, we still see problems:

This is how it SHOULD look like (renders like this in a browser):

![image](https://user-images.githubusercontent.com/5641621/40549342-7f7d5a90-6037-11e8-9891-5d407448ec21.png)

This is how it looked BEFORE the `svg` trick:

![image](https://user-images.githubusercontent.com/5641621/40549388-9ca1172e-6037-11e8-9181-6ba3dbc8e567.png)

And AFTER the trick, a closer zoom reveals that the `8` is still bad, and the `o` now suffers from other defects:

![image](https://user-images.githubusercontent.com/5641621/40549447-bf37032a-6037-11e8-999a-bacfd53ad5df.png)

So... QUESTION:
===

How can we make wkhtmltopdf to render the fonts correctly?

PD:

    $ ./wkhtmltopdf-amd64 --version
    wkhtmltopdf 0.12.4 (with patched qt)

**Comment by PhilterPaper** [comment]
A few questions to ask, when trying to diagnose this:

1. Is the text stored in the PDF as ASCII text, UTF-8 text, or as a graphics image or graphics instructions?
2. Is this Montserrat font embedded in the PDF file, or is it found on the PC with the PDF reader?
3. When used with a browser or PDF created with something other than wkHTMLtoPDF (e.g., Word), is the same problem seen when using this font?
4. What font format is this Montserrat? Has anyone tried a different source or format for this font?

The idea is to isolate which party (the font itself, the PDF viewer, or the PDF maker) is at fault. Whether the font is embedded, or found on the reader's PC, I would be surprised if wkHTMLtoPDF is outputting vector graphics instructions (as surmised in the first post) -- it would seem to be completely unnecessary.

**Comment by graingert** [comment]
You should be able to get the answers from the example PDFs I posted

**Comment by xmontero** [comment]
@PhilterPaper for question 1, if I open the PDF in a notepad, I see mainly binary data:

![image](https://user-images.githubusercontent.com/5641621/40585245-9fd152c8-61af-11e8-9f63-eb15f7b698cb.png)

How can I "de-compress" the content to differentiate if the text in the PDF was placed as text or it was converted to curves?

**Comment by xmontero** [comment]
This is the "ending part", I don't know if there's any trick there:

![image](https://user-images.githubusercontent.com/5641621/40585269-ffca888e-61af-11e8-9a8f-54783a9e753c.png)

**Comment by PhilterPaper** [comment]
I think that a utility such as PDFtk can do this: `PDFtk doc.pdf output doc.unc.pdf uncompress`. Then you can see if there's some text matching "HelloTrip", etc. Note that it's possible that there's microjustification going on, and characters may be laid down and positioned one at a time so you won't see big chunks of the expected text. I see you use DejaVuSans font, are there any others?

**Comment by xmontero** [comment]
@PhilterPaper Once uncompressed, I can see the text itself is **not** there. It seems rendered by "text-converted-to-curves", instead.

This is coherent with these two facts:

1. The problem was mainly in the "shape of some letters". If it was text, this would probably lack of sense.
2. In my regular PDF viewer I can't select the text. I didn't try it before, but when testing this, I just wanted to "select" a part of the text. I could not. Simply, there's no "text" there, just a bunch of graphics with shapes ressembling letters.

# So my *new* questions are:

Q1) How can I tell wkhtmltopdf to render the document by placing text instead of converting text to curves?

Q2) How can I ensure that wkhtmltopdf embeds the needed fonts inside the document just in case the destination machine does not have it?

**Comment by PhilterPaper** [comment]
Well, at least you've figured out what's going on! I have no idea why it would choose to render text as graphics (curves) rather than text (with either an embedded font or counting on it being on the reader). I would think it would be very little space savings, and a lot of extra prep time. If this is a choice of WebKit rather than wkHTMLtoPDF's code, I don't know what to do about it.

**Comment by xmontero** [comment]
Well I'd rather resist to believe that an important tool like `wkhtmltopdf`, so widely used, cannot really render text instead of curves...

I wonder...

Do "all" other users get curves? Or is there anybody out there that gets text?

I'd like to distinguish if "wkhtmltopdf itself is not able to render text", or "I did not manage to use/configure it".

**Comment by PhilterPaper** [comment]
Does this happen (rending text as graphics) only happen on certain font files, or all of them? Those that it happens on -- do they have any characteristics that make them different from those which render as text? Internally, perhaps they're SVG or something instead of TTF/OTF? That's all I can think of.

**Comment by Tomsgu** [comment]
Closing as it is a duplicate of #2022.
