### ISSUE TITLE
wkhtmltopdf breaking line with negative values

### ISSUE THREAD

**Issue by hellvix** [wkhtmltopdf/wkhtmltopdf#3017]
I am using wkhtmltopdf on a Ubuntu server. The problem I have been facing is that negative big numbers break lines. I saw this thread: http://stackoverflow.com/questions/22061036/prevent-breaking-of-negative-numbers. My values are read directly from the database, and differently from this guy I don't add a hyphen.
### Negative numbers:

[![enter image description here](http://i.stack.imgur.com/AO5eS.png)](http://i.stack.imgur.com/AO5eS.png)
### Positive:

[![enter image description here](http://i.stack.imgur.com/0ic4Q.png)](http://i.stack.imgur.com/0ic4Q.png)

This is after I upgraded to version wkhtmltopdf 0.12.2.1 (with patched qt). On version 0.9.9, which I had been using I had no problem with PDF generation. I upgraded because in Django, Views which inherited the PDF class from `django-wkhtmltopdf` would give an error code 1, not generating PDF.

PDFs are generated through command line:

```
command = 'xvfb-run wkhtmltopdf --footer-right "[page]/[topage]" {s} {o}'.format(
            s=html_file.name,
            o=target.name
        )
```

I tried to add `--zoom 0.5` as a parameter to that command, but only made the PDF worse. Half of the text got cut out off the page and can't be read.

**Comment by PhilterPaper** [comment]
What happens in various browsers? It's obvious that -119000.00 is a bit too wide for the **Total** column, and WebKit finds a hypen - to be a convenient place to break the line. Do browsers simply widen the column, or do they overflow to the left or right? The suggestion in stackoverflow was to replace the ordinary hyphen with a similar-looking character that would not allow a line break there -- what did you use, and what were the results?

Since the value is too wide for the column, consider either reducing the font-size (in that column) or increasing the width of the column. That would be better than fudging the process by forcing an overflow to the left or right.

**Comment by hellvix** [comment]
On SO the guy was setting a hyphen manually instead of a minus sign. I am
reading directly from the database. I don't think that's a hyphen right
there. Smaller values also have that problem. As I mentioned, this problem
didn't happen on version 0.9.
The row expands with the value. I don't think I'll solve anything.
Den 23. jun. 2016 16.14 skrev "PhilterPaper" <notifications@github.com>:

**Comment by juanm4** [comment]
I had the same issue. After much time of investigation, I discovered that you can solve the issue if you put min-width (css) in the column (td).

You must be sure that the min-width is enought for the value of td.

After that all work like a charm!

Good Look!

**Comment by Tomsgu** [comment]
Closing as this is not an issue with wkhtmltopdf itself.
