### ISSUE TITLE
Allow bleeding?

### ISSUE THREAD

**Issue by kuanyui** [wkhtmltopdf/wkhtmltopdf#3037]
Following is using scenario. (0.12.3)

Original output like this:

``` shell
wkhtmltopdf main.html main.pdf 
```

![p1](https://cloud.githubusercontent.com/assets/1370070/16893811/0539d786-4b76-11e6-9d20-c3b5037f14ac.png)

I want let the colored title out of margin (e.g. `margin-left: -200px`), so I use:

```
wkhtmltopdf -L 0 -R 0 -T 0 main.html main.pdf 
```

![p2](https://cloud.githubusercontent.com/assets/1370070/16893812/05ca1fe4-4b76-11e6-9e27-e48ba9f97eeb.png)

Though the colored headers are placed just like what, the other parts doesn't. I still need pages has padding. For example, the joints between pages:
![p3](https://cloud.githubusercontent.com/assets/1370070/16893910/d8eefd7a-4b78-11e6-89ff-acd6149cf855.png)

I found that `wkhtmltopdf` trims everything beyond margins, (e.g. `.colored-title {margin-left:-200; padding-left:200}` ). Can `wkhtmltopdf` allow bleeding to solve this problem?

**Comment by kuanyui** [comment]
Or, let each pages can have their own settings, instead off all pages apply the same ` -L 0 -R 0 -T 0`

**Comment by PhilterPaper** [comment]
Is this intended to be physically _printed_ on paper, or just displayed? If printing on paper, you need to be aware that very few printers can put down toner or ink _all the way_ to the physical edge of the paper. They need at least 3 or 4mm of clean paper for the pinch rollers and other paper-handling mechanisms. If you want to end up with a bleed to the edge of the _finished_ page, you will have to plan to **crop** the paper (physically cut it) after printing. From the outside-in, you have media box (paper size), bleedbox (smaller than the media, due to paper-handling concerns), and a possibly smaller cropbox, to where you will cut to a finished page size. I don't know if wkHTMLtoPDF offers crop marks (location to cut to).

For online display only, you should be able to set your cropbox = bleedbox = mediabox to the same size, and your margins to 0. Is that what you tried? I'm not sure what facilities wkHTMLtoPDF has for setting cropbox or bleedbox, or what their defaults are (I would guess they are equal to the mediabox, but I won't say so for sure). Also don't forget any _binding_ margin on page inside edges (it should be 0 for display-only pages).

If the problem is that setting margins to 0 is putting text itself uncomfortably close to the edge of the paper or screen, I'm not sure that wkHTMLtoPDF has the facilities to allow fill boxes to bleed to whatever edge, while keeping text and other content away from physical edges. That sounds kind of like what you're looking for. Certainly that can be done if you have control at a very low level (such as the PDF::API2 library), but something like wkHTMLtoPDF that formats the page as for a browser, and then slices it into pages, probably doesn't have the flexibility to set different margins for different content types (box fills versus other content). Anyone else have experience in this area? Has anyone tried _post-processing_ the resulting PDF to extend filled areas out to the nearest edges? It would involve reading in and disassembling the PDF, looking for filled areas that go to some outer margin (the "physical" page edge), resizing them (extend towards the outside of the media), and writing the revised PDF back out. I'm sure that would be complicated!
