### ISSUE TITLE
Using as a library and ability for simpler API usage. 

### ISSUE THREAD

**Issue by fxfactorial** [wkhtmltopdf/wkhtmltopdf#3046]
Excellent project! 

I'm very curious about using this at the C level and I see that its possible to write such bindings given https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3045. My questions are 
1. Any easy way to get `libwkhtmltox` installed on both OS X and linux? I didn't see it on brew. 
2. Can the API do the following? I assume it could since its rather simple, I want to provide JavaScript which I want to be evaled and get back the resultant values. So basically like calling `ReactDOM.renderToStaticMarkUp` and getting back the resultant HTML.

Much appreciated.

**Comment by anowell** [comment]
[author of the in-progress [Rust bindings](https://github.com/anowell/wkhtmltopdf-rs)]

1. Also curious. I'm tempted to write my own shell script for a classic `curl ... | sudo sh` install.
2. I believe this can be accomplished via setting `load.runScript` on the object settings. It's [not well-documented](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/050dd18d9ed70aa23fb97f8a8b46b5e8a0ad3485/src/lib/pdf_c_bindings.cc#L83), but it [appears to be wired up](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/076322dd10a05fcac4913fd6f313783d8f22e772/src/lib/multipageloader.cc#L276-L277). I just tried a quick test of it using my rust bindings and it segfaulted, but I can't clearly pin the blame on wkhtmktopdf yet because I'm still debugging other segfaults with other more basic settings.

**Comment by fxfactorial** [comment]
@anowell Great! Can you tell me at least the initial setting of the build? I don't think my brew install brought in the `.so`s or the `.h`, could you share the steps at least to get to compiling/linking?

**Comment by anowell** [comment]
I've been building on linux, so maybe not a ton of help for OS X, but the [official linux tarball](http://wkhtmltopdf.org/downloads.html) has the `.so` and `.h` files:
```
~/tmp/wkhtmltox$ ls lib
libwkhtmltox.so  libwkhtmltox.so.0  libwkhtmltox.so.0.12  libwkhtmltox.so.0.12.3
~/tmp/wkhtmltox$ ls include/wkhtmltox 
dllbegin.inc  dllend.inc  image.h  pdf.h
```
For the time being, I just copied said files to `/usr/lib` and `/usr/include` (and cringe that they aren't package managed, but I wasn't ready to battle `LD_LIBRARY_PATH` or `C_INCLUDE_PATH` or whatever).

I have a minimal C example [here](https://github.com/anowell/wkhtmltox-sys/blob/master/examples/convert-string.c) that I was building with: 
```
gcc -g -Wall examples/convert-string.c -o target/convert-string-c -lwkhtmltox
```

**Comment by fxfactorial** [comment]
@anowell Perfect! That's golden!
