### ISSUE TITLE
wkhtmltoimage - cannot load leafletjs map tiles

### ISSUE THREAD

**Issue by indywatch** [wkhtmltopdf/wkhtmltopdf#3076]
wkhtmltoimage 

cannot find setting to allow the entire visible portion of a javascript map to load, ie here:
http://arabia.conflictwatch.net/yemen.html

This command takes the capture:
xvfb-run -a -s "-screen 0 640x480x16" wkhtmltoimage --javascript-delay 15500 --height 350 --width 450 --quality 60 --no-stop-slow-scripts --use-xserver --disable-smart-width "$@"

Help? Am I missing something obvious?

**Comment by DanielCeregatti** [comment]
Doesn't leaflet trigger an event for when map tiles are finished loading? If so, you should listen for that event, set windows.status to someString in the listener's callback, and use --window-status someString in your command line instead of --javascript-delay. Otherwise you're relying on everything happening within that 15.5 second time frame you've allotted. If leaflet doesn't support this (which is my map tech's case, as it's old) then use something like jquery's waitforimage plugin. It's what I use.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.

**Comment by 1kastner** [comment]
I just struggled with this issue...
