### ISSUE TITLE
problem when site run on https://

### ISSUE THREAD

**Issue by ZAJDAN** [wkhtmltopdf/wkhtmltopdf#3115]
Hello,
I am using phpwkhtmltopdf and everything worked nice, but from the moment, when I have put web site on https://
is problem generate PDF
**Fatal error: Uncaught exception 'Exception' with message ' Could not create PDF: Loading pages (1/6)' ....**

in apache2 I have config which contains:

```
 <IfModule mod_headers.c>

       Header set   Content-Security-Policy   " script-src 'self' https://code.jquery.com https://ajax.googleapis.com http://maps.googleapis.com 'unsafe-inline' 'unsafe-eval' ; font-src  'self' https://fonts.googleapis.com https:$
       Header set X-Content-Security-Policy   " script-src 'self' https://code.jquery.com https://ajax.googleapis.com http://maps.googleapis.com 'unsafe-inline' 'unsafe-eval' ; font-src  'self' https://fonts.googleapis.com https:$

       Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

       Header unset X-WebKit-CSP
       Header add X-WebKit-CSP "default-src 'self'"

       Header set X-Content-Type-Options "nosniff"
       Header set X-XSS-Protection "1; mode=block"
       Header set X-Frame-Options "SAMEORIGIN"
       Header set Strict-Transport-Security "max-age=63072000; includeSubDomains"

 </IfModule>
```

thanks for any hint

**Comment by PhilterPaper** [comment]
I take it the page works fine (under SSL) on a browser? Are there any problems (sometimes hidden by certain browsers) with non-SSL (http) page content being used? This would be anything not a link: images, .js, .css, etc. That would be the first thing to check, that it's clean under SSL.

**Comment by ZAJDAN** [comment]
Actually the website it self works fine. On one the page I have a button which call php page whwrw is used phpwkhtmltopdf and from there is called wkhtmltopdf engine which runs on same server.
After that I click on the button, so I also see that the page is redirected to http: // , but in apache I have also directive '**Redirect permanent / https://www.example.com**' and this makes the conflict,
But I do not understand, that even though I everywhere use links in this format '/var/www/example.com/...' why the wkhtmltopdf redirect the action to http://

**Comment by PhilterPaper** [comment]
I don't understand your statement about "I everywhere use links in this format"... /var/www/example.com/ would be an include in PHP, not some link in HTML. Are you talking about a path relative to the HTML root (or BASEDIR path)?

If you omit just the protocol (http: or https:), it should use whatever protocol the current page is under. The same should hold if you also omit the domain, and just use a relative or absolute path on the same site. Perhaps there's a bug in WebKit or wkHTMLtoPDF where someone hard coded http: instead of something that would respect the current page's protocol?

A redirect such as you give would return a new address with a 301 status code to the browser. A browser would then resubmit the request with the new address. How wkHTMLtoPDF handles this I don't know. I would assume that someone would have noticed by now if wkHTMLtoPDF was going into a loop or something (not using the new address) when it got a redirect back, but maybe you're the first to use it with a redirect to https: ? I take it that this redirect works properly with a browser.

**Comment by Tomsgu** [comment]
Closing as there is no response.
