### ISSUE TITLE
HTML having text with font-family as Myriad pro comes as image in output pdf

### ISSUE THREAD

**Issue by nchandrasheker** [wkhtmltopdf/wkhtmltopdf#3130]
HTML having text with font-family as Myriad pro comes as image in output pdf. Faced this issue with webkit version: 0.12.1

Following is HTML and the generated PDF:

[MyriadFontTest.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/479384/MyriadFontTest.zip)

**Note:** Reported issue was faced in **Windows**

**Comment by PhilterPaper** [comment]
`font-family:myriad pro;` is a problem, because it will interpret it as "Use _Myriad_ font face, and then fall back to _Pro_ font face". Start by properly specifying the font family name: quoted string "Myriad Pro" or perhaps Myriad-Pro. Then see if the behavior  changes.

BTW, Myriad Pro is not a widely installed font. If I display the HTML in a browser, it just comes up with the default (Arial?). Do you need to embed the font in the PDF? Is that what it's already doing? I can't read PDF files well enough to tell if that's an image or an embedded font.

**Comment by nchandrasheker** [comment]
Tried all the possible combinations namely, 
a) font-family "Myriad Pro" inside double quotes and single quotes. This results in image and not the text.
b) font-family "Myriad-Pro", i.e. with dash in between. This results in text instead of image in PDF, but the font-family changes to Tahoma instead of retaining "Myriad Pro"

Is there any other thing that we need to try.

By the way, we tried converting word document containing Myriad pro font and converted the doc file to pdf using MS word save as option. That also resulted in PDF with image instead of text.

**Comment by PhilterPaper** [comment]
I don't have a copy of Myriad Pro, so I can't test it for sure. Once you have it properly defined in the style attribute, how can you tell that it's an image and not text? Did you unpack the PDF using some tool (e.g., PDFtk), and see there was no text (intact or broken up into sections) "This text is in Myriad Pro", but there _was_ an embedded image? The "stream" in the file could be either an image or just compressed content -- you can't assume it's an image just because it's binary.

I take it that Myriad Pro displays correctly in your browser. I'm not sure if WebKit is then using _that_ font to create the PDF (and embedding the font in the file), or if it's looking for a different form of Myriad Pro. I would think there would be some diagnostic messages if the desired font file wasn't found, but maybe not. In any case, I've never heard of either HTML or PDF presenting text in image format, without explicit request from the programmer. Is that something wkHTMLtoPDF is supposed to do automatically?

**Comment by PhilterPaper** [comment]
I just got around to uncompressing the doc1.pdf (using PDFtk), and lo and behold, it _is_ being presented as an image (m, l, c, and h **drawing operators**). Is that normal behavior for a PDF if the font is not embedded, or just for wkHTMLtoPDF? Do you have to explicitly tell wkHTMLtoPDF to embed a font, if you don't want it to draw text rather than rendering on the fly? Drawing (rather than bitmapped images) _should_ scale arbitrarily.

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author.
