### ISSUE TITLE
How to handle "Header Tags (paragraph header) not to be in last line"

### ISSUE THREAD

**Issue by sreedhar-drg** [wkhtmltopdf/wkhtmltopdf#3190]
While generating PDF in some scenarios Header Tags (paragraph header) is above page and paragraph text is in next page. How to make sure Paragraph header and content minimum 1 line should be in same page. Detail in attachment. 
![para_heading](https://cloud.githubusercontent.com/assets/13451635/19969998/9c68d8a6-a200-11e6-8926-d19d14c61e2e.jpg)

**Comment by PhilterPaper** [comment]
You might look at two things: settings for widows and orphans handling (but that may not keep headings together with content), and adding CSS to forbid a page break _after_ the heading.

Unfortunately, I'm not sure that WebKit (the rendering engine) can properly tell wkHTMLtoPDF about the purpose of various bits of output, so that either party can try to keep them together.

**Comment by Tomsgu** [comment]
Does the provided solution work for you?

**Comment by sreedhar-drg** [comment]
No I think so.

From: Tomsgu
Reply-To: wkhtmltopdf/wkhtmltopdf
Date: Wednesday, August 8, 2018 at 5:10 PM
To: wkhtmltopdf/wkhtmltopdf
Cc: "Prabhu, Sreedhar", Author
Subject: Re: [wkhtmltopdf/wkhtmltopdf] How to handle "Header Tags (paragraph header) not to be in last line" (#3190)


Does the provided solution work for you?

**Comment by Tomsgu** [comment]
We should than wait until #2457 is fixed.
