### ISSUE TITLE
Malware detection (again)

### ISSUE THREAD

**Issue by henweigh** [wkhtmltopdf/wkhtmltopdf#3198]
It looks like several malware/virus scanners are again reporting mkhtmltopdf as a malware/trojan.  The detection ratio is 2/55 on VirusTotal.

https://www.virustotal.com/en/file/e7df45c7ff3b703c5938b66ea3dc0bd951c8e4ed07285e16fbd609e1db431fed/analysis/1479056397/

While this is more than likely a false positive, it should be something that the developer and community is aware of.

**Comment by sijones-uk** [comment]
My local installation of Malwarebytes Anti-Malware quarantined the installation file with the same warning (Trojan.MalPack.NSIS). The file was `wkhtmltox-0.12.3.2_msvc2013-win64.exe`.

**Comment by ashkulz** [comment]
Nothing we can do about it, honestly.

**Comment by sijones-uk** [comment]
You can report a false positive to [Malwarebytes here](https://support.malwarebytes.com/customer/portal/articles/1835387-how-do-i-report-a-false-positive-found-using-malwarebytes-anti-malware-for-business-?b_id=6442). VirusTotal's approach to false positives are [outlined here](http://www.securityweek.com/virustotal-starts-marking-trusted-files-reduce-false-positives). I would be concerned because it makes your software look like it's been compromised (I assume it hasn't?). Especially as it seems that more than virus scanner is picking this up. There are definitely things you can do to get the installer off the virus blacklists.

**Comment by ashkulz** [comment]
The recommended way of checking authenticity is to compare it against the checksums (MD5, SHA1 and SHA256), which are present beside the files on the download site e.g. [for 0.12.3](http://download.gna.org/wkhtmltopdf/0.12/0.12.3/).

If you feel strongly about it, you might do that reporting yourself ... unless there is a specific virus detected (instead of generic threats due to incorrect heuristics, which keep on getting updated all the time) I'm not going to take any action.
