### ISSUE TITLE
How to undo setup-schroot-generic

### ISSUE THREAD

**Issue by craigfrancis** [wkhtmltopdf/wkhtmltopdf#3209]
If you run:

    sudo scripts/build.py setup-schroot-generic

It installs lots of dependencies.

If you decide to install wkhtmltopdf via a different method (or in my case, simply use `xvfb` with the Debian supplied package of `wkhtmltopdf`), how do you remove everything that has been installed?

Maybe instructions could be added to INSTALL.md, or a new option could be added to the build.py script?

---

It looks like it started with:

    apt-get install --assume-yes git debootstrap schroot rinse debian-archive-keyring build-essential ruby ruby-dev libffi-dev tar xz-utils

And there might have been Ruby Gems as well:

    gem install fpm --no-ri --no-rdoc

There is a new file at:

    /etc/schroot/chroot.d/wkhtmltox

Which creates the chroot's in:

    /var/chroot/wkhtmltox-generic-*

Which are listed in:

    schroot --list
    chroot:wkhtmltox-generic-amd64
    chroot:wkhtmltox-generic-i386

**Comment by ashkulz** [comment]
You're right. Would love a PR where the setup is done via Vagrant instead of directly in host OS :smile:

**Comment by craigfrancis** [comment]
I'll have to leave that for someone else, as I don't have much experience with Vagrant (plus, I have a few too many jobs on at the moment).

Thanks for doing this setup though, from the bit I saw, it worked very well :-)

**Comment by steenzout** [comment]
@ashkulz would be interested in having the build environment on a docker container?

**Comment by ashkulz** [comment]
@steenzout: using Vagrant looks to be more flexible. You get easy 32-bit support (not fully supported in Docker) plus multi OS support (i.e. you can get OS X and Windows boxes). It becomes more repeatable and easier to use than switching between VMs as I primarily use Linux.

**Comment by steenzout** [comment]
@ashkulz ok.

the reason I said docker was just because you could then probably use [travis-ci](https://travis-ci.org/) and a different docker images to automatically build your software and upload the .package artifacts to GitHub directly (I have done this in the past so I know it's possible).

I am building an ansible role ([ansiblebit/wkhtmltopdf](https://github.com/ansiblebit/wkhtmltopdf/)) and I usually do my tests on Vagrant boxes (debian: jessie+wheezy, ubuntu: precise+trusty+xenial+yakkety) + (32/64 bits).

with this role I can easily setup any Vagrant box.
is this something you would be interested?
if you had this would it be possible to have debian and rpm packages?
I had never used `chroot` before but I'm assuming that you wouldn't need this anymore, correct?

I'm willing to help with this.
I just need some direction.
Let me know what are you requirements and ideas and I'll send you a PR for review.

**Comment by ashkulz** [comment]
@steenzout: I don't think it'd work on TravisCI because of the build timeouts; compiling QtWebKit itself often takes more than an hour (leaving aside time for pulling the base docker image).

I have a WIP for the Vagrant-based build system (8225292f9830818ac1842a5d97e64f8084ab595f) which shows how I think it should work but still a lot to port from the previous build system. If you're interested in taking it up, I'll be glad to review/guide you on the same.

**Comment by steenzout** [comment]
Yes, I'm interested.What is the next step?Build/publish a vbox image with chroot environment ready to be used?Do you have preliminary work on this or shall I start from scratch?I just tested and with my ansible role I can build the chroot environment for Ubuntu and Debian releases fir the latest release which means I can easily build a vbox image.If I got it right, older releases had a different setup Christ command but I think I saw the code already and I can easily adapt what I have.---I noticed, when I build from source, chroot takes a long time to setup but after it is done I can create a snapshot or make a vbox release so next time would be quicker.Building the code also took a bit.I can measure that tomorrow easily to see what takes longer.On Dec 7, 2016 9:54 PM, Ashish Kulkarni <notifications@github.com> wrote:@steenzout: I don't think it'd work on TravisCI because of the build timeouts; compiling QtWebKit itself often takes more than an hour (leaving aside time for pulling the base docker image).
I have a WIP for the Vagrant-based build system (8225292) which shows how I think it should work but still a lot to port from the previous build system. If you're interested in taking it up, I'll be glad to review/guide you on the same.

**Comment by steenzout** [comment]
I just saw the commit hash from your previous comment.I'll start with that.On Dec 7, 2016 9:54 PM, Ashish Kulkarni <notifications@github.com> wrote:@steenzout: I don't think it'd work on TravisCI because of the build timeouts; compiling QtWebKit itself often takes more than an hour (leaving aside time for pulling the base docker image).
I have a WIP for the Vagrant-based build system (8225292) which shows how I think it should work but still a lot to port from the previous build system. If you're interested in taking it up, I'll be glad to review/guide you on the same.

**Comment by themightychris** [comment]
I've been working with habitat a lot lately, it might provide a good vehicle for being able to do builds within docker containers. habitat handles a lot of what it looks like the current chroot build system deals with, but it's multi-platform support isn't very mature yet

**Comment by efx** [comment]
@steenzout I can definitely help test the vagrant setup as I need to compile from master or particular versions.

**Comment by steenzout** [comment]
@efx , I had setup the vagrant boxes using ansible (#3237 and #3245) which I could easily maintain and test but the author here didn't like it so I dropped this for now.

Feel free to look at #3245 .
If you need help or need for me to publish the vbox just ping me on twitter (same user as in GitHub).

**Comment by ashkulz** [comment]
Please open a new issue in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) if you want to continue this discussion, as it is using docker containers now.
