### ISSUE TITLE
pre tag tab issue 

### ISSUE THREAD

**Issue by prakhargvp** [wkhtmltopdf/wkhtmltopdf#3239]
![screenshot from 2016-12-08 17 18 12](https://cloud.githubusercontent.com/assets/7056772/21009139/22adf75e-bd6b-11e6-9e7c-66dc31c9457c.png)
![screenshot from 2016-12-08 17 18 21](https://cloud.githubusercontent.com/assets/7056772/21009140/23443d54-bd6b-11e6-8bd8-308dd6485630.png)
![screenshot from 2016-12-08 17 18 30](https://cloud.githubusercontent.com/assets/7056772/21009141/24bb8db8-bd6b-11e6-9164-2ea417cba8f1.png)

**Comment by PhilterPaper** [comment]
Do you know if the source (temp.html) indentation is a **tab** or a **run of spaces**? If it's a tab, it looks like it's being replaced by a single space. If it's a run of spaces (blanks), it looks like WebKit or somebody is collapsing them to a single space, which is normal for HTML, but should not be done for `pre` text. Neither behavior is correct.

**Comment by prakhargvp** [comment]
Hey, I want tabs indentation How can i do ?

**Comment by PhilterPaper** [comment]
I'm not sure how to consistently use tabs in either HTML or in wkHTMLtoPDF. Tab behavior is something usually hard coded into an operating system or browser, although I seem to recall Unix systems being able to specify how much to expand a tab, and some editors can be told to save runs of spaces as tabs. To be able to specify "tab stops" (columns) where the next tab goes to might be a nice feature, although you would need to define the units, since proportional fonts are almost always used (ems or absolute size, such as inches, from the left or right [for bidi] margin). To define tabs as runs of spaces would result in uneven columns.

**Comment by Tomsgu** [comment]
Closing as the answer was provided. Please feel free to comment if you have still a problem.
