### ISSUE TITLE
How to set the name of the output.pdf with the title of the html?

### ISSUE THREAD

**Issue by ergunpp** [wkhtmltopdf/wkhtmltopdf#3268]
Is there a way to name the generated pdf files using the html <title>?

**Comment by ashkulz** [comment]
Nope. That's a bad idea

- you have indeterministic file name which can clash
- won't work in multiple input URL scenario
- no way to map filename to input URL

**Comment by SDP190** [comment]
I must argue that i don't understand whats the issue,  in my opinion this is a very very critical task to implement the option of saving files according to the name of the HTML <Title>, in fact this is what keeps me from using this tool since i have lot's of URL's to save, i don't want to have to explicitly write the name for each file, but i should only have to specify the directory folder, and the tool should be responsible to determine the name of each file according to it's HTML<title>.
Also why would it be a problem for multiple input URL scenario? each Input URL should save its to source page title?

The only claim i understand is that there is "No way to map filename to input URL".

But still to my opinion this is a very necessary task in particular when doing batch operation and saving multiple html pages it should at least be an "option" to automatically save the PDF to the HTML<title> name, and to solve the issue that there is no way to map filenames, i thing a good solution would be that the tool should output a mappings file with all mapping info to the output directory. in that way if anybody needs mapping info, he can find the info in that page.

One more issue i can see, is because not every html page has a title, so what if the tool comes across a page witch has no title tag?

But for that also you can just still skip that page, and output the error info, and for when doing batch operation with multiple pages there should be an "argument" option where the user can choose what the tool should do when it came's across such a scenario, if it should just skip the page and go to the next input URL, or it should cancel\revert the whole operation.
