### ISSUE TITLE
unable to parse json string

### ISSUE THREAD

**Issue by arzoni1** [wkhtmltopdf/wkhtmltopdf#3281]
I have a javascript with JSON.parse metod to convert string to json object. this work good in application but in wkhtmltopdf I get error "unable to parse json string". do you can help me?

**Comment by nitroamos** [comment]
I'm wondering if I'm having the same problem. I *do not* have this problem when I run wkhtmltopdf on the command line (OSX), but I do get it when trying to use the wkhtmltopdf grails plugin (I don't know how they're different). Basically, my generated html (gsp) looks like this:

```
    console.log("here0");
    var test = JSON.parse("{&quot;a&quot;:true}");
    console.log("here2");
```

and when run using the plugin with the following commands:
[/usr/local/bin/wkhtmltopdf, --dpi, 300, --page-size, Letter, --debug-javascript, --encoding, UTF-8, --window-status, done, -, -]

I get the error message:

```
Warning: file:///var/folders/zw/l06lt6sd637fq8j4sf_8ht6jzkc0tg/T/wktemp-cbbc67ec-243e-4475-93b0-4d4d9ff3bf49.html:54 here0
Warning: undefined:0 SyntaxError: Unable to parse JSON string
Warning: undefined:0 TypeError: 'undefined' is not an object
```

I'm trying to find a way to pass my data to the gsp so that wkhtmltopdf can read it, but so far everything I've tried fails. I have tried to inject javascript in directly, but it seems grails keeps giving me "&quot;" characters, and wkhtmltopdf is giving me parse errors on those too.

I'm using wkhtmltopdf version 0.12.4 on OSX and grails 2.5.5.

Am I doing something wrong as far as wkhtmltopdf is concerned?

**Comment by Tomsgu** [comment]
This is a JS issue. Not something connected with wkhtmltopdf. It doesn't even work in a browser.

**Comment by MigdaliyrArchitect** [comment]
I'm having this same issue when consuming a restful API call. In a browser it's fine. In WKHtmltopdf it gives the above mentioned error. So since it works in one and not the other if it *is* a JS issue, then it's a problem with the rendering from wkhtmltopdf.
