### ISSUE TITLE
Request  : Reader view like this plugin

### ISSUE THREAD

**Issue by llamapixel** [wkhtmltopdf/wkhtmltopdf#3318]
https://addons.mozilla.org/en-US/firefox/addon/activate-reader-view/

Is this possible?

**Comment by PhilterPaper** [comment]
What exactly are you trying to accomplish with this? From reading about this plugin, it sounds more or less like something to set up a browser page for a voice screen reader -- remove the clutter and simplify it. Couldn't you do something similar with "print" media CSS or even an overriding CSS file? Is the finished PDF intended to be read aloud, or are you looking for something to be easier on the eyes? Either way, the appropriate CSS might be a better choice.

**Comment by llamapixel** [comment]
Hi PhilterPaper, I am trying to extract the contents of the website without any website cruft or navigation.

So far  I have this string. 

wkhtmltopdf  --no-header-line --no-footer-line  --no-background --disable-forms --minimum-font-size 16 --print-media-type  https://en.wikipedia.org/wiki/Main_Page wikipedia.pdf	

Please advise on how to improve with your understanding.

**Comment by PhilterPaper** [comment]
So the plugin itself just tries to force Firefox's Reader View mode, something built in to Firefox to simplify the page. The plugin is not doing the page content simplification.

I'm not sure how they can do it in a very general way, as each HTML page will have its own way of presenting navigation, ads, etc. Maybe it just looks for certain HTML5 elements and _assumes_ they can be ignored? You could do the same in overriding CSS by making those elements `visibility: hidden` or `display: none`. It would take some poking around in the code wrapper, but maybe you could intercept requests for disallowed ad URLs (images and Javascript) and suppress them (a blocklist)? This might be a good place to start: `http://stackoverflow.com/questions/30661650/how-does-firefox-reader-view-operate`. It might even be easier to grab the page source (HTML + aux files) and preprocess it, rather than trying to play with a live remote page. You might even just grab the raw text (and basic formatting) and tune it to your own needs.

Your intent is to make a simplified PDF document that's easy on the eyes, and not to extract text from it?

**Comment by llamapixel** [comment]
Hi PhilterPaper, I am trying to extract the contents of the website without any website cruft or navigation. I would prefer to have a pdf without unwanted data other than the subject matter.

The plugin above is very accurate and does a great job. Perhaps I should automate the browser with actions instead of attempting to go down this programs road.

A Readability and wkhtmltopdf combination would be an excellent combination.


Do you know of any other strings I can use in the mix to reduce the web content?.
Is there a way to remove content by div name perhaps? 
If you have any other insights on this aux files element, that would be great.

**Comment by PhilterPaper** [comment]
I think that anything you do will have to be tuned to a specific page or site, which means reading through the HTML and seeing what elements are in use and what the naming conventions are. Firefox may have come up with a good algorithm to do this automatically (see the link I provided), but it's not going to be guaranteed to work perfectly. You could lose desired content, or retain stuff you want to get rid of.

To remove content from a named (id=) div, `#name { display: none; }`

Maybe you could tell us what you are hoping to end up with, and for what purpose. Is it intended to be printed (hard copy), or only viewed? If only viewed, using Firefox with Reader View might be a lot easier (even with saving the HTML and browsing that). It might even print satisfactorily. Are you scraping web sites to build up PDF documents -- a personal library? Simply as an academic exercise, to "extract contents without cruft or navigation" doesn't seem useful. Do you have vision problems, and need to modify pages to make them readable for you? Maybe there's a better way to get where you want to go...

**Comment by llamapixel** [comment]
Hi PhilterPaper,

I just want the document article contents.

This could be very beneficial for the blind as you say, my angle is for educational material.

I am a game developer who also works as an educator. 
The main purpose is to remove the advertising content ( perhaps I use an adblock plugin here, or block at my local router [blacklist] ) as well as the website page navigation ( header / sidebar and footer ) from tutorials that do not count to the educational and archiving purposes of the page. 

I read the link you provided and the system they use appears to be detecting div names and div structures. The Firefox 'alg.' has not failed in the years I have saved content this way manually.  Perhaps I should look at that further for its reasoning in code to remove and isolate the article div. 

I have been saving the contents manually with that reader feature and some extra plugins but would like to achieve it via the command line with this tool.

P.S. thank you for the information about the named div content removal.

**Comment by ashkulz** [comment]
@llamapixel I think this doesn't make sense to have it in wkhtmltopdf itself, maybe you can add use some JS via `--run-script` or custom CSS via `--user-style-sheet` to achieve what you want.
