### ISSUE TITLE
Promise is not working in wkthmltopdf

### ISSUE THREAD

**Issue by santhoshmanikandan** [wkhtmltopdf/wkhtmltopdf#3334]
Tried converting a html to pdf which uses [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). But getting a blank page as output. When tried enabling debug javascript got a error that cant find variable Promise.

**Comment by efx** [comment]
@santhoshmanikandan this is because the underlying QT web engine does not necessarily support all of the ECMAScript6 features (see this in depth link for various engine support: http://kangax.github.io/compat-table/es6/). phantomjs has similar problems. You'll have to poly fill the `Promise` using something like https://babeljs.io/docs/usage/polyfill/.

**Comment by Tomsgu** [comment]
Closing as ES6 is not supported and there are already a lot of issues with the same.
