### ISSUE TITLE
Centos upgrade wkhmltopdf

### ISSUE THREAD

**Issue by kironet** [wkhtmltopdf/wkhtmltopdf#3393]
Hello, 

I've installed wkhmltopdf through this tutorial 
https://jaimegris.wordpress.com/2015/03/04/how-to-install-wkhtmltopdf-in-centos-7-0/

But now I realised that it's version 0.12.2.

Is there any way to upgrade it? 

Thanks

**Comment by johnny-bit** [comment]
Hi!

Sure there is! I'd recommend ditching those tutorials since rpm builds are not generally available and instead, rely on files provided.

first - remove installed rpm package. run `rpm -qa | grep wkhtmlto` to get packages, one of those will be wkhtmlto.. once you have it, do `rpm -e <name>` so that whole install is clear.

Once your system is clear grab yourself a nice copy of wkhtmltopdf from https://wkhtmltopdf.org/downloads.html

You are most likely to want this one: https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

Download selected one and unpack it by running `tar -xvJf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz`

Now all left to do is:
```
cd wkhtmltox
cp -rv ./ /usr/local/
```

That will install new files along with manpages to /usr/local
In order to update in future, all you'll have to do is follow above steps and in the last step agree to all overwrites.

That's all there is to it :)

Side note: wkthmltox has dependencies on shared libraries. If you've installed rpm version, then you should've all dependencies met. Anyway, for reference, here's how to install required dependencies:
`yum install fontconfig-devel libfontenc libXfont ghostscript-fonts xorg-x11-fonts-75dpi xorg-x11-fonts-Type1 fontconfig xorg-x11-font-utils freetype libX11 libXext libXrender`

**Comment by amjo** [comment]
hello, this gave me the below error when i ran wkhtmltopdf --version:

> -bash: /usr/bin/wkhtmltopdf: No such file or directory

is it possible i had to do the below?

> cp -rv ./ /usr/local/
