### ISSUE TITLE
Throw Exit with code 1 due to network error: ProtocolUnknownError

### ISSUE THREAD

**Issue by BDhara** [wkhtmltopdf/wkhtmltopdf#3473]
I tried code:
C:\Program Files\wkhtmltopdf\bin>wkhtmltopdf.exe    --heade
r-html "C:\inetpub\wwwroot\header.html" --footer-html "C:\inetpub\wwwroot\footer.html"
 "C:\inetpub\wwwroot\hf.html" "C:\inetpub\wwwroot\123.pdf" in cmd prompt .. 
If I put ` --load-error-handling` then it shows `Invalid argument(s) parsed to --load-error-handling `

HTML is
<!DOCTYPE html>
<html>
<head>
<title>test</title>
</head>
<body>
    <header>
        <h3>Header</h3>
    </header>
</body>

</html>

same with footer html..

**Comment by JavierSossa** [comment]
white_check_mark SOLUTION:
This is for those with the error: Exit with code 1 due to network error: ProtocolUnknownError
If you get an error when uploading an image/media, you have to upload that image to your own http server or hosting, for example in XAMPP. Put the complete link of the image in the html, example: img src='https: // 127.0.0.1/web/chart.jpg'> In this way the images will be loaded well at the time of passing them to pdf. When creating the pdf, you can already delete the image from the hosting or remove the server.
