### ISSUE TITLE
if the url contains '&'       wkhtmltopdf  can't work 

### ISSUE THREAD

**Issue by suxianbaozi** [wkhtmltopdf/wkhtmltopdf#3516]
if url contains '&'       wkhtmltopdf  can't work

**Comment by jordanambra** [comment]
If you're running wkhtmltopdf from a shell, then the ampersand (&) has a special meaning and needs to be enclosed in quotes (single or double).

For example:

This will fail: `wkhtmltopdf http://myurl.com?a=b&c=d output.pdf`

This will succeed: `wkhtmltopdf 'http://my.url.com?a=b&c=d' output.pdf`

**Comment by akk1984** [comment]
I am calling a java servlet page using 
wkhtmltopdf "http://s2.ku.edu.pk:7778/ts/servlet?paperr&port=ad.jsp" d:\test.pdf

It gives following error 
Loading pages (1/6)
Error: Failed loading page http://s2.ku.edu.pk:7778/ts/servlet?paperr&port=ad.jsp (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error.

then I used the command 
wkhtmltopdf "http://s2.ku.edu.pk:7778/ts/servlet?paperr&port=ad.jsp" d:\test.pdf --load-error-handling ignore

but that error remain persist. Please help me in resolving the issue.

**Comment by suxianbaozi** [comment]
"s2.ku.edu.pk"  can't resolved

**Comment by akk1984** [comment]
Thank you for the quick response, but I gave an imaginary link to you. You can check any URL but with atleast two parameter in that URL, where & (ampersand) must be used.
I guess the main problem is associated with & (ampersand) symbol.

**Comment by suxianbaozi** [comment]
$ wkhtmltopdf "http://suidi.cn?action=1&xx=2&yy=4" test.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

it works when wraped the url with "

mac os , wkhtmltopdf 0.12.4
