### ISSUE TITLE
wkhtmltopdf license

### ISSUE THREAD

**Issue by arzoni1** [wkhtmltopdf/wkhtmltopdf#3584]
I wish to use wkhtmltopdf in my web program which will run on a central server where my customers will connect to my program.  My program calls wkhtmltopdf via a Java class. 
I do not distribute wkhtmltopdf and do not modify it.
Is there any limitation on this?  
The language of GNU LESSER GENERAL PUBLIC LICENSE is difficult to understand.  Therefore I am asking you my question to get a clear answer.

**Comment by PhilterPaper** [comment]
It sounds to me like what you want to do with wkHTMLtoPDF is permitted, but I will defer to the owner or a trained lawyer for the final word on this. I am not a lawyer -- I merely play one on a hit TV show. ;)

My understanding of the GPL and LGPL are that they are primarily concerned with ensuring that when you modify and/or redistribute software under that license, you can't further restrict the rights of others to in turn modify and/or redistribute the software. When it comes to _profiting_ off of [L]GPL-licensed software, it gets a little murky there. Whether or not you can _sell_ the software itself is not entirely clear to me (you can certainly sell _services_ around the software, but whether that covers selling the _output_ of wkHTMLtoPDF is a bit hazy). I suspect you're clear to do so, otherwise merely editing a program using GNU Emacs or some other free editor would put your program into the public domain!

I used to work for IBM (back when it was a good company), and when the GPL first came out, the edict came down that we couldn't use any GPL-licensed software because the way the license was written, it could be argued _in court_ that anything else that software touched (including editors and compilers) became public. Not until version 2 of the license came out, which clarified the language, were we permitted to use such software.

**Comment by ashkulz** [comment]
You don't have a problem in the scenario described, it's LGPL not AGPL.
