### ISSUE TITLE
odoo 10 error 

### ISSUE THREAD

**Issue by hazemdardar** [wkhtmltopdf/wkhtmltopdf#3594]
hello 
i have 
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-81-generic x86_64)
and 
odoo v 10 installed in digitalocean
after i update my upuntu using
sudo apt-get update & upgrade 
i can't print anything in odoo it show this error 

Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display
![erroe](https://user-images.githubusercontent.com/28004356/29035863-cb1e3e00-7ba5-11e7-862a-7844b88ad2c9.JPG)

how to fix that :(

**Comment by NiR-** [comment]
You've two errors here:
> The switch --header-spacing is not support using unpatched qt...

I guess you downloaded a newer version of wkhtmltopdf package when you upgraded your system. The error message means that you can't use header-html/footer-html with this version. You can rather use the version available on [wkhtml website](https://www.wkhtmltopdf.org/downloads.html).

> DXcbConnection: Could not connect to display

You need to install `xvfb` package on your server. And in order to use it the simplest is to wrap calls to wkhtmltopdf with xvfb-run: `xvfb-run -a -s "0 1024x768x24" wkhtmltopdf https://google.com /tmp/test.pdf`.

**Comment by Tomsgu** [comment]
Closing as there is no response and solution was provided.
