### ISSUE TITLE
Dinamic images added with jQuery aren't showing in PDF

### ISSUE THREAD

**Issue by Mariuch** [wkhtmltopdf/wkhtmltopdf#3666]
I'm trying to add some images dinamically with jQuery but there aren't showing in generated pdf.

If I use a static image with src from beggining, the PDF shows it without problems, but if I add some image dinamically, it doesn't show at all. 

What could be the problem? Thanks in advance.

**Comment by AnilK2016** [comment]
Make sure it will be added after the dom is ready.Use the document.ready function I guess it will fix this issue.

**Comment by Mariuch** [comment]
Nope. I was using document.ready already and I still have the same problem. The images src is a base64 URL but I read that is supported in latest version right?

**Comment by AnilK2016** [comment]
If there is no issue using a static image which means that there is no problem with base64 right?I am assuming that WKTOHTML converts the HTML to the image added to the DOM.Set a time delay for the PDF conversion in the python(like setTimeout in javascript)may help to fix this issue.

**Comment by NiR-** [comment]
@Mariuch Did you try to dynamically add some text rather than image? And which version of jquery do you use btw? It might be an issue when jquery is loaded due to some missing browser features. Or it might be due to too short `--javascript-delay`, as mentioned by @AnilK2016. Also `--debug-javascript` might be useful in your case.

**Comment by Tomsgu** [comment]
Closing as there is no response from 2017.
