### ISSUE TITLE
Long pauses

### ISSUE THREAD

**Issue by andrewrocktime** [wkhtmltopdf/wkhtmltopdf#3752]
wkhtmltopdf version 0.12.4
Windows Server 2012, 64 bit

When generating PDFs it seems if external references are included on the page to PDF we get a long pause. After a number of experiments we found that having references to scripts that are not within our network cause a pause of approximately 20 secs.

For example we had a simple HTML page as below. This takes about 23 seconds to generate a PDF.

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>testing</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
    <p>Test PDF generation</p>
</body>
</html>

If we replace the jquery line with a relative path, e.g. <script src="/scripts/jquery.min.js"></script> the PDF generates within seconds

If the line is replaced with the following <script src="http://vlsloyalty.essilor.co.uk/JavaScript/jquery-1.9.1.min.js"></script> which is a different site to the one generating the PDF but it is within the same network the PDF again generates within seconds.

Is there a known issue with referencing resources outside of the network that is running the WKHTMLTOPDF component?

**Comment by Sicos1977** [comment]
I made something similar than wkHtmlToPdf but then with Chrome. Try it out and see if that fixes your problem. https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by PhilterPaper** [comment]
So anything living outside your local network takes forever to handle, while anything inside the network (including different domains) is fast? Do you have any sort of firewall around your local network that might be doing some sort of checking or scanning of files? Is it looking up external sites to see if they're on any sort of malware blacklist? I think you'll need to talk to your local IT to see what kind of things they're doing when you reach into the dirty and dangerous outside world to get a file. Does the same thing happen when you try to browse a web page that uses the same external resource? If not, you need to ask what the difference is -- if browser requests are expedited or cached, perhaps you can get wkHTMLtoPDF treated like a browser. Otherwise, can you make local copies of such files, and use those instead?

**Comment by Tomsgu** [comment]
Closing as there is no response since 2017.
