### ISSUE TITLE
generate image with part of html content beyond the default max height ?

### ISSUE THREAD

**Issue by luoyjx** [wkhtmltopdf/wkhtmltopdf#3763]
wkhtmltoimage version 0.12.3
OSX 10.13.1

I had generated a image from html content that content might has a very large height, but i found there might be a limitation which about 32000 px i guess。

The image which is OK with about 30623 px height
![18](https://user-images.githubusercontent.com/4217102/34336149-c8859212-e98f-11e7-9e86-c93a3c4893d1.jpg)

The image which is not OK with about 33723 px height
![22](https://user-images.githubusercontent.com/4217102/34336168-ea4011b6-e98f-11e7-85a4-7c6563fe31ff.jpg)

Is that a bug or something with default settings? I cannot get the real size with the html content before generation.

**Comment by PhilterPaper** [comment]
Your "22" (not OK) image won't display due to file corruption. If this was the original image file, make sure it's good before trying to use it in wkHTMLtoPDF.

32000px translates to about what size (in inches)? 32000 _Points_ is 444 inches, which is beyond the 200 inch limit of PDF page sizes. 32000px at about 150dpi would be about the limit (200 inches). There is a way to go beyond 200 inches in PDF 1.6 or 1.7, using a scaling factor.

**Comment by luoyjx** [comment]
hmmm... i'm using node.js wrapper of wkhtmltoimage .In my situation , there is no problem exporting the same html content to PDF files .

I'm wondering if there is any way to export image correctly .

Here is my options when using wkhtmltoimage.

```
quality: 100,
'disable-smart-width': true,
width: 884,
zoom: 1,
output: 'export.jpg'
```

**Comment by PhilterPaper** [comment]
So you're saying that this HTML displays correctly in a browser, and wkHTMLtoPDF converts it (without reported errors) to a PDF which can be successfully displayed, but wkHTMLtoImage fails? Is there an error message, or the image produced is simply corrupted? I wonder if there is a signed 16 bit limit (32767) somewhere either in wkHTMLtoImage or in the JPEG spec? What happens if you output a PDF (via wkHTMLtoPDF), and read it into an image processor such as The GIMP or Photoshop, and write out a JPEG file? Is the file still bad then?

**Comment by Tomsgu** [comment]
Closing as there is no response from 2017.
