### ISSUE TITLE
cpu 100%

### ISSUE THREAD

**Issue by jinzhanyougithub** [wkhtmltopdf/wkhtmltopdf#3774]
Excuse me, why does wkhtmltopdf consume so much CPU, each process is 100% consumed.

**Comment by PhilterPaper** [comment]
Does it come to and end and produce correct results? If it doesn't end, there's an endless loop somewhere. If it doesn't create a correct PDF, that's a separate problem. If it is at 100% CPU but ends with the correct result, that simply means that it's CPU-bound rather than limited by I/O operations. That's no problem.

**Comment by jinzhanyougithub** [comment]
Thank you for your reply, but I want to ask why the wkhtmltopdf CPU consumption is very high when the PDF is generated.

**Comment by jinzhanyougithub** [comment]
It's the right end and it's okay, but when the PDF is generated, the CPU consumption is really big.

**Comment by PhilterPaper** [comment]
If your operating system permits priority setting, you might be able to "nice" wkHTMLtoPDF down to a lower priority, consuming less CPU and allowing other stuff to run faster (which I presume is the issue here). Otherwise, it's not a bug and it's not any problem with wkHTMLtoPDF -- it's simply CPU-bound (does little I/O) and tends to eat the entire processor until it's done. If you lower the priority, it may take longer to run (wall clock time).

**Comment by jinzhanyougithub** [comment]
thanks

**Comment by xushuai2** [comment]
The Java call found more time-consuming, and how to optimize the high under the time-consuming problem.

**Comment by cdeisler** [comment]
Understand this is an old issue, ran across it searching for a solution. Running this on azure web app, something causes a race condition that requires process restart to fix.  Problem will persist over time requiring health monitor or other such remedy.  
Leaving this here for reference.

![image](https://user-images.githubusercontent.com/2393923/128741480-a343c53e-2415-4e71-83df-0a1b69ab3073.png)

**Comment by wapenshaw** [comment]
@cdeisler were you able to solve the issue? I am having the exact same problem and I have to restart my app on azure to get the CPU usage back down to normal.
