### ISSUE TITLE
Pdf Merge

### ISSUE THREAD

**Issue by keremozer** [wkhtmltopdf/wkhtmltopdf#3814]
PdfOne        PdfTwo
PO_Page1   PT_Page1
PO_Page2   PT_Page2
PO_Page3
PO_Page4
PO_Page5

How can I merge these two pdf
[outputPdf]
PO_Page1  
PO_Page2
+PT_Page1
+PT_Page2
PO_Page3
PO_Page4
PO_Page5

**Comment by PhilterPaper** [comment]
That doesn't really have anything to do with wkHTMLtoPDF. There are plenty of free PDF utilities out there, some of which can merge pages into a new PDF. You might find one that will drop an entire PDF between two pages of another, or you might have to first split PO in two, and then merge the three PDFs.

If you need to renumber pages or otherwise alter the _content_ of pages, that is a much bigger problem. It may take custom-written code to overwrite page numbers, using a library such as PDF::Builder (in Perl) or something else. However, there should be plenty of tools out there to do a simple merge.

**Comment by alloylab** [comment]
@ashkulz close out
