### ISSUE TITLE
Start page or page enum?

### ISSUE THREAD

**Issue by grig27** [wkhtmltopdf/wkhtmltopdf#3818]
Hello!
How to set start page or page enum list for translate to pdf?

**Comment by PhilterPaper** [comment]
Are you asking for wkHTMLtoPDF to output just a _range_ or list of pages, rather than the entire document? I'm not sure there is such a way, but you can always post-process the complete document with a PDF utility to extract individual pages (or a range) into a new PDF document. You might have to extract into individual pages and then merge them back into the final document.
