### ISSUE TITLE
Topage (page number) issue

### ISSUE THREAD

**Issue by loic911** [wkhtmltopdf/wkhtmltopdf#3889]
Hi,

**Problem**
See header in [result.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1937196/result.pdf).
My pdf pages goes from "Page 1 of 5" to "Page 4 of 5". There is only 4 pages.
Sometimes I get 2 extra invisible pages.

**What I expect**
"Page 1 of 4" to "Page 4 of 4"

**Step to reproduce**
Extract this zip containing body, header and footer.html: [html.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1937202/html.zip)

Run
`wkhtmltopdf --dpi 300 --disable-smart-shrinking --margin-top 5mm --zoom 1 --header-spacing 35 --footer-spacing 20 --header-html header.html --footer-html footer.html body.html result.pdf`

Is it a bug or a bad use?

Thanks :-)

**Comment by hakimio** [comment]
Does it happen if you leave out "dpi" setting?

**Comment by myself379** [comment]
I had the same issue, I did not use the --dpi settings as it screwed up the words, especially if the sentences is in between pages. I use --disable-smart-shrinking because it corrects itself to 14px font-size. Most of the time I get the correct number of [page] and [toPage]. But in quite a numbered occasion the [toPage] has extra 1 page.

For my case, it show 11 / 12, even though the last page is page 11.

**Comment by Tomsgu** [comment]
This should be fixed in #3952. Can you try it with 0.12.6 version (not released yet)?

**Comment by stmlange** [comment]
Is there any public version of 0.12.6 available or do I need to build from source myself?

(Note: since travis already seems to tests the build could it perhaps publish the artifacts too? (see https://docs.travis-ci.com/user/deployment/releases/ perhaps just publish it with `prerelease: true`)

**Comment by ashkulz** [comment]
@stmlange: you can build 0.12.6 yourself, it's quite easy -- see the packaging repository. You can also try an [older dev build](https://builds.wkhtmltopdf.org/0.12.6-dev/) -- I'll try to have it updated by this weekend.

**Comment by beyondcreed** [comment]
Hi,

We are needing this on production FreeBSD system. However the official latest package version is: 0.12.5_5. Any chance you can make a public release so port maintainer can update it. I think he is waiting for official release. Otherwise we will need to look into building from source. Thanks.

https://www.freshports.org/converters/wkhtmltopdf/

**Comment by stmlange** [comment]
See the discussion in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4578

Perhaps you could try to install the latest pre-release from https://github.com/wkhtmltopdf/packaging/releases/

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
