### ISSUE TITLE
CMYK color values

### ISSUE THREAD

**Issue by pixelmachine** [wkhtmltopdf/wkhtmltopdf#39]
Would it be possible to implement the device-cmyk color value syntax?
See: http://dev.w3.org/csswg/css-color/#cmyk-colors

I would have thought setting colors in cmyk for print ready PDFs would be pretty useful.

**Comment by akshayodesk** [comment]
hi 
any patch released for this issue
Wkhtmltopdf itself convert cmyk images to pdf rgb which is the actual problem

**Comment by akshayodesk** [comment]
@ashkulz 
Hi i am currently modifying the qtwebkit 4.8.x
It has got many files.I know basic c/c++ /qt.
Can u help me guiding how to  integrate cmyk feature  so that while conversion to pdf(using wkhtmltopdf) the resultant images  in pdf are in cmyk format
Please advise

Thanks

**Comment by Rikijs** [comment]
@akshayodesk - Had you had any luck with necessary changes in order to acquire support for CMYK colors?

**Comment by JHGitty** [comment]
Same issue here - did anybody fix this issue already to support CMYK JPEG files?

**Comment by MicWit** [comment]
I need this as well, seems strange that if your creating a PDF (quite often for print) that you can't follow a basic standard like CMYK. As stated before, even the images going in as CMYK are being converted to RGB!

I would also like to suggest that you have a way of mapping colors as options. Something like send in an associative array as $array["RBG"] = "CMYK". eg $array["#00bfff"] = "cmyk(100%, 25%, 0%, 0%)", so that wherever wkhtmltopdf see's "#00bfff" in the CSS, it replaces it with "cmyk(100%, 25%, 0%, 0%)". That way if you are doing something to be previewed on the screen and then go to print, you can match your text colors exactly and put any images in as CMYK so they don't need to be converted.

**Comment by JHGitty** [comment]
We use wkhtmltopdf in combination with PHP. To bypass this issue we currently convert all JPEG CMYK images to normal JEPG RGB images before using them with "wkhtmltopdf". This bypass is very bad but the only possible solution we found yet.

Did anybody found a better solution?

**Comment by danielhjames** [comment]
Hi, this is really a case of the right tool for the job. As wkhtmltopdf is based on a web browser engine designed for screen display it has no need for CMYK support. If you take a look at [https://github.com/w3c/csswg-drafts/issues/301](url) you'll see there's not even a consensus about CMYK support being a web standard, let alone being implemented in browsers.

Converting from RGB to CMYK or back again is not a straightforward task, as it depends on the printing machine and the paper being used, which is why pre-press workflows use ICC profiles. It makes no sense to convert digital images such as JPEG which are natively RGB to CMYK unless you already know what the output target is, in which case you probably won't be creating PDFs on the fly.

So, if you want to use wkhtmltopdf, I suggest you use a pure RGB workflow and don't worry about CMYK. If you are doing pre-press work, please consider using a specialised HTML to PDF renderer such as [https://github.com/mpdf/mpdf](url) which does support CMYK and spot colours.

**Comment by JHGitty** [comment]
@danielhjames Normal browser don't have issues to display JPEG that are in "CMYK" mode. But wkhtmltopdf generated pdfs don't show these JPEGs. This is a bug and not a feature-request.

**Comment by danielhjames** [comment]
Hi @JHGitty I suggest you file that issue as a separate bug. This issue was originally about CMYK values in CSS.

A browser showing a CMYK image on your screen is converting it back to RGB. You could probably make wkhtmltopdf do that, but it wouldn't be right for pre-press. This is why I suggested using a specialised renderer or keeping your JPEGs RGB to begin with.
