### ISSUE TITLE
Server load and optimization

### ISSUE THREAD

**Issue by elainebyrne** [wkhtmltopdf/wkhtmltopdf#3909]
Hi,

I'm using the latest version of wkhtmltopdf and generating PDF. I'm on DigitalOcean with 1GB RAM and 1CPU.

Generating PDF with just a simple 1-page html without css takes about 1.5-2 seconds and uses approximately 50% of the CPU!

The PDF has just "hello world" and nothing else.

Is this a normal CPU/serve usage? What could I possibly be doing wrong?

**Comment by alagiyanirav** [comment]
I am also facing the same issue on DigitalOcean. 
Any help?

**Comment by elainebyrne** [comment]
No, i'm still waiting for input from the core team here.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by elainebyrne** [comment]
@alloylab WTF bro? I have mentioned the version and also the specifics in the original post. I'm on Ubuntu obviously. Using nginx. Don't think it matters whether I'm on Nginx or Apache.

You simply just want to close issues without resolving them!!

**Comment by Tomsgu** [comment]
I don't see **any** version specification. Is the latest version 0.12.4 or was it already 0.12.5? Is the version with patched qt or not? What is the command that you run? Also for you it's obvious to be on Ubuntu, but not for us. 

Please see also #2018.

We are closing issues, because there are a lot of duplicates or invalid ones. If there is no complete information (versions, step to reproduce, minimal test case) and author is not responding, we try to close the issue that we cannot reproduce.
