### ISSUE TITLE
Does not support ES6.

### ISSUE THREAD

**Issue by Riotsmurf2** [wkhtmltopdf/wkhtmltopdf#4010]
I spent the longest time trying to figure out why my JS was not loading. I am using laravel-snappy package to use wkhtmltopdf in a nice php way. So i could not see any logs. Eventually i decided to make a pdf using the command line and it kept giving me a parse error on my js file i was including in the html. I changed all my 'lets'' to 'vars' and removed any es6 functions that i was using and BAM! it works.

My issue is that 1. It does not support es6 and es6 has been out for a while now. and 2. it does not say anywhere in your documentation that it does not support es6. There are a lot of open issues where people are having problems rendering graphs that use JS(using es6) that could be solved and closed by adding to your documentation "Does not support ES6 and further"

**Comment by Tomsgu** [comment]
You don't need to remove all features to be able to use ES6. There are compilers/polifylls for these kind of things. Even though it exists a long time, there isn't full support in some browsers/apps yet. 

The ES6 support depends on qtwebkit library update. You can find a 0.13 branch that can improve a situation, but it's still in development.

I think a majority of issues with javascript are because of SVG rendering (maybe I am wrong). 

Honestly, have you read a whole documentation before posting an issue? Apart of ES6 there are other things that are not supported. List them all and maintain it can take a lot of time and effort. But you can always make a PR to improve a situation.

**Comment by Tomsgu** [comment]
Yeah I also have no problems with es6 support. Unfortunately I have to take care (in our apps) of people who uses old browsers. That's why babel is still needed imo. Note that there is already ES7 (and what about 8). 

As I said there are quite a few issues that could be resolved with webkit update (there is **no workaround** for them). Unfortunately it's not something that can be done easily. Especially when @ashkulz is the only developer at the moment.
