### ISSUE TITLE
Support CMYK for PDF

### ISSUE THREAD

**Issue by vladislavsky** [wkhtmltopdf/wkhtmltopdf#4021]
Hello everyone
Is there any CMYK preferences for the tool??
Thanks

**Comment by PhilterPaper** [comment]
Meaning, exactly what? Do you have CMYK color model images that aren't being handled properly? I seem to vaguely recall seeing reports of such problems a year or two ago -- have you searched, and what image format? 

On the other hand, is it supporting CMYK images OK, but you'd like to tweak the images a bit, perhaps for a non-standard gamma? I don't recall hearing anything about that -- it might better be handled in a photo editor such as The GIMP or Photoshop.

**Comment by vladislavsky** [comment]
I need pdf converted to CMYK regardles what images it has inside: RGB or CMYK, thx

**Comment by Tomsgu** [comment]
Have you tried it? What problem do you have with it exactly? What version do you have? Whats the actual problem.

This is an issue tracker not a help desk. Please ask in stack overflow if you have any questions.

**Comment by Tomsgu** [comment]
Closing as there is no feedback.

**Comment by PhilterPaper** [comment]
I would assume then that the purpose in having all images (and presumably, all other colors in text and graphics) as CMYK is for printing purposes. You might want to look around for utilities that separate a PDF into 4 separate passes (color separations), regardless of the color model used for a particular image or graphic. I vaguely recall seeing such things, although I can't point to one at the moment. At any rate, I've never heard of having to do all images as CMYK due to color separations need.
