### ISSUE TITLE
Static binary

### ISSUE THREAD

**Issue by bibstha** [wkhtmltopdf/wkhtmltopdf#4043]
From https://wkhtmltopdf.org/downloads.html FAQ section, I saw

> The above binaries depend on packages provided by your distribution. Due to incompatibilities between library versions provided by each distribution, the only option is to use static linking – hence removed for now.

What does this sentence mean? Shouldn't a static binary be compatible with any linux distribution?
Is static binary not distributed from the website above anymore?

**Comment by hakimio** [comment]
Dependencies are no longer statically linked and each package provided there requires some dependencies from distro's official repositories.

**Comment by Tomsgu** [comment]
Closing as the response was given.

**Comment by hello983834** [comment]
Hello,

Could you please provide static binaries again?
We have problems with the dynamic builds because they do not support the libraries we use.

You can statically link 100% of all libraries used by wkhtml with the only exception of getaddrinfo() from glibc, but this function is usually always ABI compatible.
