### ISSUE TITLE
Incorrect position of elements  pls HELP

### ISSUE THREAD

**Issue by VPeykovski** [wkhtmltopdf/wkhtmltopdf#4305]
Hello!
I am using version 0.12.5 and i have problem with elements positions.
In my html elements are in correct position but in pdf elements arent in correct position.Some of them are above the coordinates some of them are under.  
[test.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3007367/test.txt)
[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3007371/test.pdf)

**Comment by PhilterPaper** [comment]
Could you clarify what you mean by "aren't in correct position"? Is this X and Y position on the page? You have a left margin in the PDF which has pushed everything to the right. I see some diagrams cut across two pages. I didn't see any obvious "under/over" differences (z-position). Since you're cutting one long HTML page into multiple PDF pages, it's quite likely that pages will not divide quite evenly (did you adjust top and bottom margins to try to effect pagination?). The PDF will add in its own top and bottom margins (unless you've explicitly set them to 0).

P.S. Adding "pls HELP" to the title is not useful to anyone reading this group -- it's just noise if everyone is trying to claw their way to the top of the list by updating the title.

**Comment by VPeykovski** [comment]
Hi
By "aren't in correct position" i mean my top isn't in correct position.I create my pdf by exlicitly setting margin.I use page size A4, DPI 150,margin top 113px ,margin bottom 113px,margin left 105px,margin right 105px.You can see the difference between my custom margin and explicitly set margin to 0.
[testWithMargin.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3047581/testWithMargin.pdf)
[testWithoutMargin.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3047588/testWithoutMargin.pdf)
I tried to show you  in the pdfs what displacement i have. 
This is the html for both pdf .
[testHTML.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3047609/testHTML.txt)
You can see that the elemets in my html are in correct TOP position.
P.S. Sorry for adding "pls HELP".

**Comment by PhilterPaper** [comment]
So, you are setting page margins in an attempt to manually paginate the PDF? It looks like the upper left corner is in the correct place, and there is a bottom margin. Content at the bottom of the page is being split across pages. I assume you wanted it to go to the next page.

Have you tried running with the `--disable-smart-shrinking` option? I understand it cures a lot of strange behavior like this. That's all I can think of at this time.

**Comment by VPeykovski** [comment]
I tried with and without smart shrinking but in both case there is no difference.Page being split across the pages isn't problem for me .I  just want my element top position to be correct placed.

**Comment by PhilterPaper** [comment]
I ran it twice (0.12.5 on Windows), first with
```
wkHTMLtoPDF -s A4 -d 150 -T 113px -B 113px -L 105px -R 105px --javascript-delay 10000 test.html newtest.pdf
```
and then (without Smart Shrinking)
```
wkHTMLtoPDF -s A4 -d 150 -T 113px -B 113px -L 105px -R 105px --javascript-delay 10000 --disable-smart-shrinking test.html nosstest.pdf
```
newtest.pdf appears to match your supplied example test.pdf. nosstest.pdf shows that Smart Shrinking had shrunk down the page by about 50%. Disabling it cut off and discarded the right half, and output twice as many pages as before. So, basically, it looks like your input HTML is about twice as wide (without shrinking) as you can fit on an A4 sheet with those margins. I'm still not sure about what you're finding "out of position" about your top elements, but you may want to first think about how much this stuff has to be shrunk down to fit a page. When you say "top", are you talking about z-index or a stack of elements, rather than "low y value" top-of-page positioning?

I hope you didn't pay too much for whatever software produced this thing. The HTML it produced is absolutely hideous, with empty 20px high row after empty row, to position a few yellow boxes (_and_ repeating the CSS attributes for each one), rather than drawing divs and filling them at absolute positions, or even tables with varying row heights and column widths. Rather than outputting inline GIF images, it should have drawn the charts in SVG (does wkHTMLtoPDF handle SVG well enough?).

**Comment by VPeykovski** [comment]
I mean  "low y value" top-of-page positioning.
