### ISSUE TITLE
Path escaping issue

### ISSUE THREAD

**Issue by Pohui-Nahui** [wkhtmltopdf/wkhtmltopdf#4349]
Arch Linux

When i'm trying to convert chm with spaces in chapters name i get these error messages
![image](https://user-images.githubusercontent.com/50049567/57192175-26b7af00-6f36-11e9-942f-34f53a1db20f.png)

**Comment by PhilterPaper** [comment]
I'm not familiar with chm-to-pdf, but it looks like one of a number of possible things happened: you forgot to enclose a path with spaces in quotes, so they're treated as a single unit instead of two names, or you _did_ quote such strings, but the quotes weren't stripped off correctly (maybe try " instead), or your OS doesn't like spaces in names (be sure to check if you can manually create a **Chapter 1**), or an ASCII space x20 got replaced by some other kind of space (e.g., non-breaking space xA0), or something else entirely. It will probably take some trial and error to see what's allowed on your OS, and how things are quoted at various stages, and whether spaces are swapped out for something else in path strings.

**Comment by ashkulz** [comment]
Assuming this tool uses wkhtmltopdf internally, please file a bug report with them as it looks like they need to escape CLI arguments properly.
