### ISSUE TITLE
Get pdf document without css style

### ISSUE THREAD

**Issue by VolodymyrPN** [wkhtmltopdf/wkhtmltopdf#4448]
I get a generated document without stylesheets, though I don't get any errors about it.
Anyone get it too?

wkhtmltopdf -V
- wkhtmltopdf 0.12.5 (with patched qt)
-----------------------------------------
root@estel:/usr/local/bin# wkhtmltopdf  http://google.com google.pdf
- Loading pages (1/6)
- Counting pages (2/6)                                               
- Resolving links (4/6)                                                       
- Loading headers and footers (5/6)                                           
- Printing pages (6/6)
- Done                                                                      
---
[google.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3524924/google.pdf)

**Comment by PhilterPaper** [comment]
Works fine for me (Windows 10, same wkHTMLtoPDF version and command line). The page in question appears to carry all its CSS with it, so it doesn't sound like your local system is blocking CSS files. I do see that there is a massive amount of in-line JavaScript to get through. You might try some of the flags to extend timeouts, just in case that's happening. Otherwise, if you're using a reasonably current version of wkHTMLtoPDF, there shouldn't be any CSS in there so advanced that it breaks the program. I'm out of ideas if none of that helps.
