### ISSUE TITLE
Problem with Binay 0.12.5 on shared hosting.

### ISSUE THREAD

**Issue by ciltocruz** [wkhtmltopdf/wkhtmltopdf#4471]
Hi.

I have developed a tool that requires PDF generation. For this I used the wonderful wkhtmltopdf.

On my Linux system it works perfectly.
On my Windows system it works perfectly.

My surprise is when I went to use it in my public hosting. It is a shared hosting promoted by Siteground.

My surprise is when I try wkhtmltopdf with my binary built into the application and I get all these errors.

- wkhtmltopdf-amd64: /lib64/libc.so.6: version `GLIBC_2.9 'not found;
- wkhtmltopdf-amd64: /lib64/libc.so.6: version `GLIBC_2.10 'not found;
- wkhtmltopdf-amd64: /lib64/libc.so.6: version `GLIBC_2.7 'not found;

I have tried between several versions and the problems resemble:
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error

And even this error:
Fontconfig error: Cannot load default config file

I'm desperate. From the hosting they tell me that they cannot update the libraries because the server is shared and that I must hire a dedicated server for a lot of money.
The current versions of the libraries on my shared server are:

**OpenSSL version: 1.0.2r 26 Feb 2019**
OpenSSL 1.0.2r 26 Feb 2019
built on: reproducible build, date unspecified
platform: linux-x86_64
options: bn (64,64) rc4 (16x, int) des (idx, cisc, 16, int) idea (int) blowfish (idx)
compiler: gcc -I. -I ../ include -I .. -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DSSL_ALLOW_ADH -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/ usr / local / openssl / ssl"

**libc.so.6: version: 2.5**
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PURPOSE PARTICULAR.
Compiled by GNU CC version 4.1.2 20080704 (Red Hat 4.1.2-48).
Compiled on a Linux 2.6.9 system on 2010-07-27.
Available extensions:
The C stubs add-on version 2.1.2.
crypt add-on version 2.1 by Michael Glad and others
GNU Libidn by Simon Josefsson
GNU Libyan by Per Bothner
NIS (YP) / NIS + NSS modules 0.19 by Thorsten Kukuk
Native POSIX Threads Library by Ulrich Drepper et al
BIND-8.2.3-T5B
RT using linux kernel aio

What options do I have to use a version of WKHTMLTOPDF on my shared server?

I have read github topics about static versions that include all the necessary libraries. But I can't find a way to make it work if it can be done.

I cannot update outdated libraries or change environment variables. Could I download and compile the libraries manually and upload them to the dedicated server on another route and have the binary take them from there?

Greetings and thank you

**Comment by PhilterPaper** [comment]
As you have found, many hosting companies do not want arbitrary large programs running on their servers, fearing that they will bog down the servers and lead to poor performance and loss of customers. They remove various libraries and tools needed for running other than PHP and the like. If you can come up with a statically linked program that doesn't need the server to supply certain libraries, and it isn't so CPU-hungry that it will draw the host's attention, you might be able to run wkHTMLtoPDF on your server.

One thing you should do first is to review your workflow, and see if you _really_ need to run wkHTMLtoPDF on the **server**, rather than offline on your PC. If you're offering a service to convert random websites to PDF, that may be too heavy-duty for a shared server. On the other hand, if you just have some static PDFs to produce (or update) once in a while, you may find it better to do it on your PC and upload the PDF to the server. Your host will certainly be happier with such an approach.

**Comment by ciltocruz** [comment]
Yes, it needs to run on the server. Wkhtmltopdf is working to generate budgets and invoices in PDF dynamically on the website.

**Comment by PhilterPaper** [comment]
Well, if you're generating documents from scratch (rather than converting existing HTML), consider a library to help you generate PDF directly. There's PDF::Builder (on CPAN), but requires running on Perl (most servers have it, but it might be difficult to integrate with a PHP-based website). There are probably PHP-based PDF-generator libraries you could look at. So long as it's a relatively simple and straightforward document, this might be feasible.

**Comment by ciltocruz** [comment]
I will investigate that of PERL...

**Comment by ashkulz** [comment]
@ciltocruz: you can always switch to a VPS, which will give you full control and install whichever libraries you want.
