### ISSUE TITLE
Lambda function convert HTML to PDF using wkhtmltopdf failed after upgraded the runtime from Node.js 8.10 to 10.x deployed on Amazon Linux 2

### ISSUE THREAD

**Issue by joechwong** [wkhtmltopdf/wkhtmltopdf#4523]
**wkhtmltopdf version(s) affected**: 0.12.5 (with patched qt)

**OS information**
Error happened after deployed to AWS (new AWS Linux 2 with node.js 10.x runtime).  It was working with node.js 8.10 runtime with previous AWS Linux.

**Description**
Due to end of life support of Node.js 8.10 runtime for AWS Lambda function, we are currently undergoing an upgrade to Node.js 10.x runtime which runs on a new version of Amazon Linux called the Amazon Linux 2. 

Once deployed my application to AWS, I received the following errors: 

{ [Error: ENOENT: no such file or directory, open '/tmp/pdf.out']
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/tmp/pdf.out' }

I then narrowed down to specific wkhtmltopdf error below: 

Error: wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory 
wkhtmltopdf exited with code 127
at handleError (/var/task/payment/index.js:3715:16)
at ChildProcess.<anonymous> (/var/task/payment/index.js:3683:7)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

**How to reproduce**
We didn't change the following codes that's currently working with node.js 8.10 with AWS Linux.  It failed after changing to node.js 10.x and deployed the lambda to AWS cloud.

const wkhtmltopdf = require('wkhtmltopdf');
const shell = require('shelljs');

const FileWorkingDirectory = process.env.IS_OFFLINE ? './tmp' : '/tmp';

const generatePdf = htmlMessage => {
  console.log('Generating PDF');

  if (!process.env.IS_OFFLINE) {
    shell.exec('ls -la');
    shell.cd('payment');
    shell.exec('ls -la');
    shell.exec('cp wkhtmltopdf /tmp');
    shell.exec('chmod 777 /tmp/wkhtmltopdf');
    console.log('copied wkhtmltopdf to /tmp');
  }
  return new Promise((resolve, reject) => {
    wkhtmltopdf(htmlMessage, { output: `${FileWorkingDirectory}/pdf.out`, pageSize: 'letter' }, (err, stream) => {
      if (err) {
        console.error('generatePdf wkhtmltopdf error ', err);
        reject(err);
      }
      console.log('pdfService - generated PDF from HTML');
      resolve(stream);
    });
  });
};

module.exports = {
  generatePdf,
};

**Expected behavior**
I will continue to convert HTML to PDF without error.

**Comment by 0xR** [comment]
Seems like libxrender is not available in the NodeJS 10 runtime: https://gist.github.com/vladgolubev/439559fc7597a4fb51eaa9e97b72f319

**Comment by ashkulz** [comment]
Maybe you just need to install the package?
```
$ docker run --rm -it amazonlinux:2
bash-4.2# yum list libXrender
Loaded plugins: ovl, priorities
Available Packages
libXrender.i686                                                                                     0.9.10-1.amzn2.0.2                                                                                   amzn2-core
libXrender.x86_64                                                                                   0.9.10-1.amzn2.0.2                                                                                   amzn2-core
```
Either way, this is something that belongs in the [packaging](https://github.com/wkhtmltopdf/packaging) repository.

**Comment by yashdeep-credivia** [comment]
Hi @ashkulz @0xR @joechwong 

We have recently faced the same issue while migrating our Html to pdf conversion lambda function from node 8.10 to 10.x. And We saw your response here. After investigating some more we found that we can add shared libraries to our deployment package for lambda by including them in the lib folder.  Then with the help of this article https://aws.amazon.com/premiumsupport/knowledge-center/lambda-linux-binary-package/, we downloaded the libxrender shared objects and other share objects and included those in our lambda function deployment package. And boom it worked as before.

**Comment by deniszatsepin** [comment]
Hi guys,
We faced the same problem, and I followed the advice from @yashdeep-credivia (thank you!).
I just want to add the list of libraries that you need to grab from AMI image to make wkhtmltopdf work in nodejs12.x lambda environment:
```
libexpat.so.1
libexpat.so.1.6.0
libfontconfig.so.1
libfontconfig.so.1.4.4
libfreetype.so.6
libfreetype.so.6.3.22
libX11.so.6
libX11.so.6.3.0
libX11-xcb.so.1
libX11-xcb.so.1.0.0
libXau.so.6
libXau.so.6.0.0
libxcb.so.1
libxcb.so.1.1.0
libXext.so.6
libXext.so.6.4.0
libXrender.so.1
libXrender.so.1.3.0
```
Additionaly, you will need to put `fonts` directory with `fonts.conf` and some trutype fonts (we use ubuntu) in you lambda image, and set env variable `FONTCONFIG_PATH=/var/task/fonts`

Good luck!

**Comment by c-py** [comment]
I followed the instructions from @deniszatsepin and was able to get this working in AWS Lambda node 12.x with wkhtmltopdf 0.12.4.

I have a lambda layer with the following structure:
```
.
│
└───bin
│   │   wkhtmltopdf
│
└───lib
│   │   libX11-xcb.so.1
│   │   libX11.so.6
│   │   libXau.so.6
│   │   libXext.so.6
│   │   libXrender.so.1
│   │   libexpat.so.1
│   │   libfontconfig.so.1
│   │   libfreetype.so.6
│   │   libxcb.so.1
│
└───fonts
│   │   fonts.conf
│   │   fonts.dtd
│   │ 
│   └───Type1
│   └───conf.avail
│   └───conf.d
│   └───fonts
│   │   │
        └───dejavu

```

The `./lib/` directory files were directly copied from the `/lib64/` directory an **Amazon Linux 2** EC2 instance.

The following directories were copied from an **Amazon Linux 1** EC2 instance:

The `./fonts` directory was copied from `/etc/fonts`
The `./fonts/Type1` directory was copied from `/usr/share/X11/fonts/Type1`
The `./fonts/fonts` directory was copied from `/usr/share/fonts`

I modified the font directory list in `fonts.conf` to point to the new paths:
```
<!-- Font directory list -->

        <dir>/opt/fonts/fonts</dir>
        <dir>/opt/fonts/Type1</dir>

<!--
```

Finally, I added `FONTCONFIG_PATH=/opt/fonts` as an environment variable to the lamba function.

If you have your fonts folder directly in your lambda package, the prefix will be `/var/task` not `/opt`. (As is @deniszatsepin's case)

**Comment by dockleryxk** [comment]
Thanks everyone who supplied solutions, my day would have been so much worse without you

**Comment by Cabooser69** [comment]
This saved me a lot of headaches. Thank you all so much.
Not being able to edit / save a business critical lambda because it was stuck on node 8 was not okay.

For the next guy trying this I have the following tips:
use GREP to find the files that are mentioned above, not everything is in one easy to find folder, you gotta make a copy of it all.
I was able to find everything I needed in just one amazon Linux 2 instance with grep.
When creating a lambda layer you will need to chmod 777 all the files before you zip them or will get permissions issues from your lambda.

"And boom it worked as before."

**Comment by ashkulz** [comment]
@Cabooser69 did you use the Amazon Linux 2 RPM? I'd appreciate a PR which documents it in detail -- as I said on the downloads page, it's not a setup that I use 👍

**Comment by jeremymoritz** [comment]
@Cabooser69 , @yashdeep-credivia, or @c-py , could I hire you one of you to help me with this exact same problem you solved?  I have followed the instructions on here, and i believe I'm very close (I have all of the dependencies in a lambda layer), but it's still not working when i run it with real html and options (and it used to work with these same inputs back when it was Node 8.10).  I'll pay well if you can help me fix this!

**Comment by jeremymoritz** [comment]
I have all of the dependencies I need in the lambda layer, but I'm getting the error: 

`wkhtmltopdf: cannot connect to X server`.  

The permissions on all the libs are 777 (or `-rwxr-xr-x@` on the wkhtmltopdf binary).  I'm not sure what more i can do.

**Comment by jeremymoritz** [comment]
It's working for me now on NodeJS 12.x Runtime Environment!  

Many thanks to @ashkulz for creating the 0.12.6 rpm package that i needed (https://github.com/wkhtmltopdf/packaging/issues/42) and to @deniszatsepin, @yashdeep-credivia, and @c-py for their invaluable posts

In case one more perspective can help any other poor schmoes like myself, i will try to detail the steps i followed.  In truth, there was WAY more trial and error than what I'm documenting of course (I was so outside my element with this that the whole process took me around 12 hours), but I'm hoping this can be done swiftly by others who find themselves in this same struggle in the future:

1. I got a lot of help from AWS support staff
2. I downloaded ashkulz's 0.12.6 file for Amazon Linux 2 x86_64 at https://wkhtmltopdf.org/downloads.html#release-candidate
3. I spun up a new EC2 instance running Amazon Linux 2 and ssh'ed into it
4. I scp'ed the file from my local machine (running Mac OS) to the EC2 instance
5. On EC2 instance, I created a /tmp directory for the file, cd'ed into it and then ran `sudo yum install wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm`
6. `which wkhtmltopdf` responded with /usr/local/bin/wkhtmltopdf
7. `ldd /usr/local/bin/wkhtmltopdf` yielded the following list of dependency libs:

```
    linux-vdso.so.1        <---- (ignore this one; it's like a system file or something)
    /lib64/libjpeg.so.62
    /lib64/libpng15.so.15
    /lib64/libXrender.so.1
    /lib64/libfontconfig.so.1
    /lib64/libfreetype.so.6
    /lib64/libXext.so.6
    /lib64/libX11.so.6
    /lib64/libssl.so.10
    /lib64/libcrypto.so.10
    /lib64/libz.so.1
    /lib64/libdl.so.2
    /lib64/librt.so.1
    /lib64/libpthread.so.0
    /lib64/libstdc++.so.6
    /lib64/libm.so.6
    /lib64/libgcc_s.so.1
    /lib64/libc.so.6
    /lib64/ld-linux-x86-64.so.2
    /lib64/libexpat.so.1
    /lib64/libuuid.so.1
    /lib64/libbz2.so.1
    /lib64/libxcb.so.1
    /lib64/libgssapi_krb5.so.2
    /lib64/libkrb5.so.3
    /lib64/libcom_err.so.2
    /lib64/libk5crypto.so.3
    /lib64/libXau.so.6
    /lib64/libkrb5support.so.0
    /lib64/libkeyutils.so.1
    /lib64/libresolv.so.2
    /lib64/libselinux.so.1
    /lib64/libpcre.so.1
```

8. All of these in the same place, so it was easy enough to use scp to pull them all down and onto my local machine
9. I also scp'ed down the /usr/local/bin/wkhtmltopdf binary file.
10. I then spun up a new EC2 instance running Amazon Linux 1 (not 2) and ssh'ed into it in order to collect the Fonts files (as described by @c-py above)
11. I used scp from local machine to get those font files from the Linux 1 EC2 instance and then turned off the instance as it was no longer needed.
12. In my local machine, I made a file structure like so:

```
    wkhtml-lambda-layer
    ├── bin
    │   └── wkhtmltopdf
    ├── fonts
    │   ├── Type1
    │   ├── conf.avail
    │   ├── conf.d
    │   ├── fonts
    │   ├── fonts.conf
    │   └── fonts.dtd
    └── lib
        ├── ld-linux-x86-64.so.2
        ├── libX11.so.6
        ├── libXau.so.6
        ├── libXext.so.6
        ├── libXrender.so.1
        ├── libbz2.so.1
        ├── libc.so.6
        ├── libcom_err.so.2
        ├── libcrypto.so.10
        ├── libdl.so.2
        ├── libexpat.so.1
        ├── libfontconfig.so.1
        ├── libfreetype.so.6
        ├── libgcc_s.so.1
        ├── libgssapi_krb5.so.2
        ├── libjpeg.so.62
        ├── libk5crypto.so.3
        ├── libkeyutils.so.1
        ├── libkrb5.so.3
        ├── libkrb5support.so.0
        ├── libm.so.6
        ├── libpcre.so.1
        ├── libpng15.so.15
        ├── libpthread.so.0
        ├── libresolv.so.2
        ├── librt.so.1
        ├── libselinux.so.1
        ├── libssl.so.10
        ├── libstdc++.so.6
        ├── libuuid.so.1
        ├── libxcb.so.1
        └── libz.so.1
```

13. I then highlighted the bin, fonts, and lib folders and compressed them into a zip folder (did not include the top folder).
14. I uploaded the folder to s3 (not required)
15. I created a new Lambda layer with this zip folder (in my case i used the s3 path option, `s3://my-lambda-layers-bucket/my-wkhtml-lambda-layer.zip`, but i could've alternatively used the direct upload option)
16. In the Lambda function configurations, i set the environment variable for the fonts: `FONTCONFIG_PATH=/opt/fonts`
17. I then attached the Lambda layer i created
18. I downloaded the Lambda function to my machine
19. I unzipped the Lambda, and removed the wkhtml binary and supporting files so i was left with only the readable .js files in this tree:

```
    my-wkhtmltopdf-lambda
    ├── index.js
    └── utils
        ├── error.js
        └── wkhtmltopdf.js
```

20. I then zipped that structure into an archive (not including the top folder) and re-uploaded it as a new version to replace my old lambda
21. Ran the tests and it worked!

Hope this helps!

**Comment by ashkulz** [comment]
Quick question: why do you need the fonts from AmazonLinux 1?

**Comment by malavancs** [comment]
@jeremymoritz what is the runtime you used for the layer

**Comment by ashkulz** [comment]
The reason for the question is, I'd be happy to accept PRs in wkhtmltopdf/packaging to automate this and make a `.zip` for the layer and I'm not sure about this part :smile:

**Comment by jeremymoritz** [comment]
> Quick question: why do you need the fonts from AmazonLinux 1?

@ashkulz , I'm not sure why/if I needed the fonts, but I suspected i needed them based on @c-py 's answer above.  

I can provide the zip file for the layer I'm using if you'd like to make it available for others to download.

**Comment by deniszatsepin** [comment]
Fonts are required for the X libraries used by wkhtmltopdf to generate pdf files with text. Starting from Node.js 10 the AWS Linux image was changed to Amazon Linux 2. X libraries copied from the previous Linux image (Amazon Linux 1), expecting to find fonts in places where they were in the previous Linux image. That's why this fonts are required to be placed in the lambda image or layer.

**Comment by ashkulz** [comment]
@deniszatsepin I assume you used the CentOS 6 package for 0.12.5 earlier. Is this still required for the AmazonLinux 2 specific RPM which was released for 0.12.6? It would be weird if so, as it was built with that version.

**Comment by deniszatsepin** [comment]
@ashkulz we use 0.12.4, because it's the last version with generic wkhtmltopdf executable. It worked in Amazon Linux 1, and we just copied required dependencies from Amazon Linux 1 to Amazon Linux 2, to be able to use it with Node.js version 10 and above.
If it's possible to use newer version package, like rpm and unpack it with all dependencies and put it into a lambda layer it would be awesome. But we haven't tried it.

**Comment by ashkulz** [comment]
Okay, so can someone check what are the _minimal_ steps for 0.12.6?

**Comment by deniszatsepin** [comment]
I may check it during the weekend.

**Comment by itaylaufer** [comment]
Just in case someone comes across this issue, here are the few simple steps that worked for me:
1. from https://wkhtmltopdf.org/downloads.html download https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-4/wkhtmltox-0.12.6-4.amazonlinux2_lambda.zip
(this file will be our layer with all the necessary files)
2. create a layer from the file we downloaded
3. create your lambda with the layer we created
4. add to the lambda an environment variable named `FONTCONFIG_PATH` with a value of `/opt/fonts`
5. that's it.
