### ISSUE TITLE
Certificate is invalid on https://downloads.wkhtmltopdf.org/

### ISSUE THREAD

**Issue by notsag** [wkhtmltopdf/wkhtmltopdf#4637]
**wkhtmltopdf version(s) affected**: *.*.* 

**OS information**

N/A

**Description**

This morning I was not able to download the .deb as I had a NET::ERR_CERT_DATE_INVALID.

**How to reproduce**

Go to https://downloads.wkhtmltopdf.org/ or try to download any version such as https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb

**Expected behavior**

The page is accessible/the package is downloaded.

**Possible Solution**  

Renew certificate.

**Comment by mcundiff3** [comment]
Getting the same issues (looks like it expired two days ago)

**Comment by devrck** [comment]
Seems like the download page redirects to github release https://wkhtmltopdf.org/downloads.html

**Comment by joshterry55** [comment]
I am having the same issue

**Comment by mattgen88** [comment]
Same

**Comment by notimewaste** [comment]
meanwhile github release page oaths are working fine 

so instead of this url https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb

 below url can be used 
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb

**Comment by drsharp** [comment]
The problem is: `brew install Caskroom/cask/wkhtmltopdf` uses the `https://downloads.wkhtmltopdf.org/` URL and it can't handle the redirect because curl fails: `curl: (60) SSL certificate problem: certificate has expired`

So while I, as a person, can navigate past that, `homebrew` can't.

Please renew the SSL cert for `downloads.wkhtmltopdf.org`!

**Comment by ashkulz** [comment]
Thanks, fixed it. But please note that they'll be disabled from 2020-03-31 -- please use the GitHub URLs instead of them. See ba575ea7777a1cc2f3002a3feda4ee2a3e5b2664

**Comment by drsharp** [comment]
> Thanks, fixed it. But please note that they'll be disabled from 2020-03-31 -- please use the GitHub URLs instead of them. See [ba575ea](https://github.com/wkhtmltopdf/wkhtmltopdf/commit/ba575ea7777a1cc2f3002a3feda4ee2a3e5b2664)

I'm not a `homebrew` expert, but do you know who would then be responsible for updating the `cask` so that it points directly to the github URL? I suspect it's a very easy fix but I have no idea where to start or whether that's something that's done here https://github.com/Homebrew/brew or done elsewhere.

Anyway, thanks for the quick fix for now! 👍

**Comment by ashkulz** [comment]
Created Homebrew/homebrew-cask#79114
