### ISSUE TITLE
Can wkhtmltopdf benefit by running on GPU?

### ISSUE THREAD

**Issue by leandrosilva** [wkhtmltopdf/wkhtmltopdf#4747]
I was wondering about running wkhtmltopdf on GPU to speed it up, looked over the documentation but could not find anything about it.

Since its very work is to generate PDF and images, I'd like to suggest have some section on documentation talking about GPU support or not.

Thanks a lot.

**Comment by PhilterPaper** [comment]
I'm not sure that a GPU would be useful in most cases. A GPU architecture is to do hundreds or even thousands of parallel operations on similar data, such as an array of pixels. You're just not going to see that much application in something more serial like processing an HTML file into a PDF. Perhaps in some limited areas where images need to be transformed, but otherwise a GPU is not going to be worth the effort to port the code to it. If someone happens to come out with a WebKit that runs on a GPU, it might be worth modifying the C++ code to use it too, but otherwise I can't see it being worth the effort.

**Comment by ashkulz** [comment]
@leandrosilva that's not possible, as the output is a PDF/image it cannot do that because the rendering backends are different.
