### ISSUE TITLE
Consistent versioning please

### ISSUE THREAD

**Issue by igoratencompass** [wkhtmltopdf/wkhtmltopdf#4811]
**Description**
First let me say I appreciate all the effort around maintaining the project, great job and I'm very thankful for that. But please, please settle down on a proper package versioning like SemVer and stick to it, it is very inconstant making auto downloads a PITA. Every time I visit your site the download links have changed structure and can't understand why is that necessary like once they are `wkhtmltox_0.12.5-1.linux-xenial-amd64.deb` and next time `wkhtmltox_0.12.6-1.xenial_amd64.deb`. Or the directory structure like `/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb` and `/download/0.12.6-1/wkhtmltox_0.12.6-1.xenial_amd64.deb`

**Comment by ashkulz** [comment]
I'm not sure I get your first 0.12.5 example, as it's [wkhtmltox_0.12.5-1.xenial_amd64.deb](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb) -- in 0.12.6, it's practically the same.

In 0.12.5, a separate packaging repository was created. I didn't move the releases there for 0.12.5 but did it for 0.12.6  -- hence the differences there. The reason is, the wkhtmltopdf version and the "packaging" version are NOT the same -- as an example, the mxe build links to openssl statically. It's a good practice to release a new build -- but what do you call it? As a recent example take a look at the [packaging releases](https://github.com/wkhtmltopdf/packaging/releases) -- 0.12.6-1 was the initial release and there were two followup releases (one for fixing macOS builds, second for adding ArchLinux support). In a way, the suffix is similar to what distributions implement.

I'm pretty sure you've read on the website why packaging it is challenging 🤷‍♂️
